-- Reverses 000168_sandbox_review_checkout_gen.up.sql. With the column goes
-- every sandbox's record of the gen that can check out a review's head. A
-- binary without 000168 does not read it; a binary with it that runs
-- 000168 again reads every sandbox as unable to check out until its next
-- ready.
--
-- RUN IT WITH THE CONTROL PLANE SCALED TO ZERO, then deploy a binary without
-- 000168. Do not run it against live pods of a binary that carries 000168:
-- every query of that binary that returns a whole sandbox row names the
-- column (sqlc writes each SELECT * and RETURNING * out as a column list),
-- so each fails with SQLSTATE 42703 and no sandbox is spawned or read until
-- the older binary replaces the pod; and a pod that restarts first applies
-- 000168 again at boot, which locks the older binary out again.
-- Guarded: IF EXISTS, so it also runs when the column is already gone. The
-- drop is a catalog change: it rewrites nothing, but takes ACCESS EXCLUSIVE
-- on sandboxes for the file's one implicit transaction, and touches no
-- other table.
ALTER TABLE sandboxes DROP COLUMN IF EXISTS review_checkout_gen;
