-- Technical plan §21.1 and §30.4: a review turn reads the commit it
-- recorded. A turn of a pull request's review session that records a head
-- (turns.review_head_sha) stays pending until its sandbox reports holding
-- that head: the session actor sends the sandbox a checkout command naming
-- the pull request's ref and the head, and dispatches the turn's prompt
-- only once the stored checkout_result says the worktree holds it
-- (internal/app/sessionactor/reviewcheckout.go). The checkout is data on
-- the pending turn, never a turn state or edge, like §3.3's prompt
-- receipts. This file adds the turn's columns; 000168 adds the sandbox's,
-- in a file of its own (see Locks).
--
-- turns.checkout_message_id, checkout_gen: the messageId of the turn's
-- latest checkout command and the sandbox gen it was sent to. The reply
-- is the event the agent stores under 'checkout_result:{messageId}', read
-- by that key through events_session_id_message_id_idx, whichever binary
-- stored it.
--
-- turns.checkout_requested_at: when the turn's first checkout on that gen
-- was asked for, on the database's clock -- the start of
-- ReviewCheckoutTimeout and ReviewCheckoutRefLagWindow. A new gen starts a
-- new bound; a later send on the same gen keeps it.
--
-- turns.checkout_sent_at, checkout_sent_ready_seq: when the latest command
-- was sent, and the gen's ready_seq then. A ready counted since means the
-- sandbox reconnected, and a command lost with its socket is sent again.
--
-- turns.checkout_sends, checkout_failures: how many commands were sent on
-- the gen, and how many of their replies said failed; NULL, read as 0,
-- until the turn's first request. ReviewCheckoutFailuresBeforeRetire
-- failed replies retire the gen once per turn, so the next one boots fresh
-- -- a stale index.lock or a broken index a killed git left in the
-- worktree fails every checkout on that gen -- and a gen that answered
-- failed at least once is retired the same way at the bound.
--
-- turns.checkout_retired_gen: the gen this turn's failed checkouts
-- retired, NULL until they retire one. A turn retires at most one.
--
-- turns.checked_out_sha: the commit the sandbox reported holding, written
-- in the commit that dispatches the turn. NULL for every turn that is not
-- checked out.
--
-- No backfill, no index, no default. Every turn that exists when this runs
-- has sent no checkout, so a pending review turn is asked for one at its
-- next dispatch evaluation. Every column is nullable with no default, so a
-- turn that is never checked out -- every turn but a pull request
-- review's -- stores nothing for them: its row is no wider on disk, and no
-- read of turns pages more.
--
-- # Locks
--
-- golang-migrate sends this whole file as one batch, which Postgres runs as
-- one implicit transaction. Each ADD COLUMN is nullable with no default, a
-- catalog change that rewrites nothing, but each takes ACCESS EXCLUSIVE on
-- turns, held until the file ends -- an instant once granted. It conflicts
-- with every other lock: the migration waits behind any open transaction
-- that has read or written turns (a long read, a backup, an actor's
-- dispatch evaluation), and while it waits, every new read and write of
-- turns queues behind it. controlplane/migrate.go sets no lock_timeout, so
-- a long transaction on turns holds the boot's migration, and every turn
-- read with it, until it ends.
--
-- The file touches turns alone, so it holds nothing while it waits, and
-- cannot deadlock. A file that also altered sandboxes would hold turns
-- while it asked for sandboxes, and the session actor's transactions read
-- sandboxes before turns (planDispatch reads the sandbox, then lists the
-- turns): one such transaction holding its read of sandboxes while it
-- queued behind the migration on turns would make a cycle, and Postgres
-- would abort whichever of the two waited first: the actor's evaluation,
-- or the migration, leaving version 167 dirty and every boot refused until
-- `migrate force`. 000168 alters sandboxes in a transaction of its own for
-- that reason. migration000167_lock_integration_test.go runs an
-- actor-shaped transaction against both, and against the two as one
-- file, where Postgres aborts one side as a deadlock.
--
-- # Rolling deploy
--
-- The previous binary works with these columns present:
--   - Every statement it sends names its columns (sqlc writes each
--     SELECT * and RETURNING * out as a column list), so it neither reads
--     nor writes them.
--   - It dispatches every review turn unchecked, as it always did,
--     including one this release left pending on its checkout.
-- migration000167_integration_test.go runs the previous binary's own
-- statements against the columns.
--
-- # Rolling back
--
-- Every control-plane boot runs the embedded migrations up
-- (controlplane/migrate.go), and golang-migrate refuses a database whose
-- version it has no file for. So once this migration is applied, the
-- previous binary cannot boot ("no migration found for version 167"). A
-- rollback therefore takes one of two steps first, with the control plane
-- scaled to zero:
--   - Keep the columns: with the golang-migrate CLI, `migrate force 166`.
--     The previous binary then boots, since 166 is a version it has, and
--     works with the columns present as above. When this release is
--     deployed again, this file runs again and leaves the columns and
--     their values as they are.
--   - Drop them: run the downs of 000168 and this migration (goto 166) with
--     this release's migrations. The down files say what they remove.
-- Nothing else needs undoing: no timer kind or event type is added. The
-- checkout command and its checkout_result event are contracts 1.24.0's.
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_message_id TEXT;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_gen INTEGER;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_requested_at TIMESTAMPTZ;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_sent_at TIMESTAMPTZ;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_sent_ready_seq INTEGER;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_sends INTEGER;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_failures INTEGER;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checkout_retired_gen INTEGER;
ALTER TABLE turns ADD COLUMN IF NOT EXISTS checked_out_sha TEXT;
