-- events_token_window_idx: backs ListTokenFramesInWindow
-- (queries/events.sql), the read every reader of a turn's final text makes
-- (sessionactor.ReadWindowFinal): the approval's cut check and its
-- snapshot, the decision inbox, the Slack and Linear replies to an awaiting
-- plan, GET /plans' fallback, the session result's summary and the plan
-- notices. It reads one turn's window of the session's `token` frames --
-- id above the turn's dispatch watermark and, for any turn but the
-- session's last, at or below the next dispatched turn's -- newest first,
-- at most 2000.
--
-- No index held that read to the window. events_token_part_idx (000144)
-- keys a session's frames by part id ahead of id, so id is no seek key in
-- it: under a generic plan the read walked every `token` frame of the
-- session and fetched the heap row of each one above the window, to test
-- an upper bound written `upper_id IS NULL OR id <= upper_id`, which no
-- plan can seek on. A custom plan took that walk or, by the log's
-- statistics, events_pkey across the window's id range, reading every
-- event every session logged inside it. Both grew with what the session or
-- the deployment had logged, not with the turn.
--
-- This partial index holds a session's `token` frames by id, written
-- id + 0, and the read puts both its bounds and its order on that
-- expression, the upper bound as a range even when the window is open
-- above (COALESCE(upper_id, the largest bigint)). The expression is the
-- point: neither events_pkey nor events_session_id_id_idx can serve a
-- range or an order on id + 0, so no plan can trade the read for a scan of
-- the window's range across every session, or of the session's whole log,
-- which an index on plain (session_id, id) still left open to the planner.
-- Every plan then reads this index's range from the window's upper bound
-- to its lower one and nothing else: a generic plan as a backward index
-- scan, a custom plan as that scan or as a bitmap scan of the same range
-- whose rows -- the window's frames, no others -- it then sorts. Either
-- way it reads a few index pages and the heap pages of the window's own
-- frames, and removes no row by a filter.
-- event_tokenwindow_plan_integration_test.go holds every plan to that
-- across a matrix of logs: at most 45 buffers for a window of 40 frames,
-- where the read before this index took up to 3,225 and removed up to
-- 52,360 rows on the same logs.
--
-- # What it costs a write
--
-- Every `token` row stored adds one entry here, a session id and a bigint,
-- as it does to events_token_part_idx; a row of any other type adds
-- nothing.
--
-- # A plain build, not CONCURRENTLY
--
-- This builds the index in the migration's own transaction and holds a
-- SHARE lock on events for the whole build, so every insert into events
-- -- every session's sandbox events, across all sessions -- waits until it
-- ends. 000144 measured the same kind of build, a partial index of the
-- `token` rows, on Postgres 17 with events at 3M rows (2 GB, 600k of them
-- `token`), warm cache: about 0.6 s, with concurrent inserts waiting up to
-- 0.65 s. The build scans the whole table whatever the partial predicate,
-- so the stall grows linearly with the table, and more on a cold cache;
-- and with no lock_timeout, a transaction already holding ROW EXCLUSIVE on
-- events when the build starts delays its lock, with every later insert
-- queued behind it.
--
-- CREATE INDEX CONCURRENTLY is not safe under this runner, for the reason
-- 000144 gives: golang-migrate serializes migrators with a blocking
-- pg_advisory_lock, a migrator waiting there holds a snapshot, and a
-- concurrent build waits for every older snapshot -- a deadlock Postgres
-- breaks by cancelling the build (an INVALID index, this version dirty,
-- every control plane refusing to boot) or the waiter (its boot fails). A
-- fresh install of deploy/control-plane (replicas: 2) runs two migrators
-- at once. A plain build takes no snapshot wait, so the waiter simply
-- waits.
--
-- # Operator guidance for a large events table
--
-- To avoid the stall, build the index concurrently yourself before
-- deploying this version, from psql, while no control plane is starting:
--
--   CREATE INDEX CONCURRENTLY IF NOT EXISTS events_token_window_idx
--       ON events (session_id, (id + 0)) WHERE type = 'token';
--
-- then check it is valid:
--
--   SELECT indisvalid FROM pg_index WHERE indexrelid = 'events_token_window_idx'::regclass;
--
-- This migration then finds the valid index and builds nothing, and takes
-- no lock on events: the block below looks the index up in the catalog and
-- runs the CREATE only when there is none. (A bare CREATE INDEX IF NOT
-- EXISTS would not do: it queues for the SHARE lock on events before it
-- sees that the index exists, so it would still wait behind every open
-- insert into events, and stall every new one behind it.) If that
-- concurrent build fails it leaves an INVALID index behind, which the
-- block below drops so the index is rebuilt here, in this transaction --
-- or drop it yourself (DROP INDEX CONCURRENTLY events_token_window_idx)
-- and retry the concurrent build first.
--
-- # An INVALID leftover
--
-- A name check alone would keep an INVALID index of this name -- one a
-- failed concurrent build left -- and Postgres never plans with an invalid
-- index, so every read of a turn's text would walk the session's text
-- instead. It is dropped first, in the same transaction, and built again.
--
-- # Rolling deploy
--
-- The previous binary works with the index present: it adds no column and
-- changes no statement's result, only the plans the planner may choose. Its
-- text of the read keeps its bounds on id, which this index cannot seek
-- on, so a generic plan of it may walk the session's `token` frames here
-- rather than on events_token_part_idx, at about the same cost: the plan
-- test's matrix, run on that text with the index present, read up to 1,662
-- buffers on the logs where it read 1,761 without it. Its pods read as
-- they did until they are replaced.
--
-- # Rolling back
--
-- Every control-plane boot runs the embedded migrations up
-- (controlplane/migrate.go), and golang-migrate refuses a database whose
-- version it has no file for. So once this migration is applied, the
-- previous binary cannot boot ("no migration found for version 161"). A
-- rollback therefore takes one of two steps first, with the control plane
-- scaled to zero:
--   - Keep the index: with the golang-migrate CLI, `migrate force 160`.
--     The previous binary then boots, since 160 is a version it has, and
--     works with the index present as above. When this release is deployed
--     again, this file runs again and keeps the valid index.
--   - Drop it: run this migration's down (goto 160) with this release's
--     migrations. The down file says what it removes.
-- Nothing else needs undoing: no column, timer kind or event type is added.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_index
        WHERE indexrelid = to_regclass('events_token_window_idx') AND NOT indisvalid
    ) THEN
        DROP INDEX events_token_window_idx;
    END IF;
    IF to_regclass('events_token_window_idx') IS NULL THEN
        CREATE INDEX events_token_window_idx
            ON events (session_id, (id + 0)) WHERE type = 'token';
    END IF;
END $$;
