// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyFailureStrike = `-- name: ApplyFailureStrike :one
UPDATE automations
SET consecutive_failures = $2,
    status = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

type ApplyFailureStrikeParams struct {
	ID                  pgtype.UUID      `json:"id"`
	ConsecutiveFailures int32            `json:"consecutive_failures"`
	Status              AutomationStatus `json:"status"`
}

// Records automation.EvaluateFailureStrike's own verdict -- called only
// while still holding LockAutomationForUpdate's own row lock, in the SAME
// transaction.
func (q *Queries) ApplyFailureStrike(ctx context.Context, arg ApplyFailureStrikeParams) (Automation, error) {
	row := q.db.QueryRow(ctx, applyFailureStrike, arg.ID, arg.ConsecutiveFailures, arg.Status)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const claimCronFire = `-- name: ClaimCronFire :one
UPDATE automations
SET last_cron_fired_at = $2
WHERE id = $1 AND (last_cron_fired_at IS NULL OR last_cron_fired_at < $2)
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

type ClaimCronFireParams struct {
	ID              pgtype.UUID        `json:"id"`
	LastCronFiredAt pgtype.Timestamptz `json:"last_cron_fired_at"`
}

// The CAS half of the cron trigger pump's own per-automation fire guard:
// "UPDATE ... WHERE last_cron_fired_at IS NULL OR last_cron_fired_at <
// <this minute's own start>" -- guards against firing the SAME scheduled
// minute twice (a slow previous tick, clock jitter, a second pod's own
// concurrent pump), while still allowing every LATER minute's own match to
// fire again -- unlike automation_invocations.fanned_out_at's one-way
// NULL-to-non-NULL flip, this guard is a recurring per-minute bucket, not
// a permanent latch. $2 is the current UTC minute's own truncated start
// instant, used both as the new last_cron_fired_at value and as the
// guard's own comparison point.
func (q *Queries) ClaimCronFire(ctx context.Context, arg ClaimCronFireParams) (Automation, error) {
	row := q.db.QueryRow(ctx, claimCronFire, arg.ID, arg.LastCronFiredAt)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const clearAutomationCreatorUnauthorized = `-- name: ClearAutomationCreatorUnauthorized :execrows
UPDATE automations
SET creator_unauthorized_since = NULL
WHERE id = $1 AND creator_unauthorized_since IS NOT NULL
`

// The self-healing half of MarkAutomationCreatorUnauthorized immediately
// above: called the moment a machine-origin dispatch for this SAME
// automation is authorized again (a maintainer re-attributed it, or its
// existing creator's account was re-enabled/re-promoted) -- "AND
// creator_unauthorized_since IS NOT NULL" is the identical no-op-avoidance
// guard ResetConsecutiveFailures above already establishes for this
// table, never a correctness requirement (clearing an already-NULL column
// twice is harmless).
func (q *Queries) ClearAutomationCreatorUnauthorized(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, clearAutomationCreatorUnauthorized, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAutomation = `-- name: CreateAutomation :one

INSERT INTO automations (
    name, prompt, repos, created_by,
    trigger_type, trigger_config, webhook_token_hash,
    sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path,
    env_vars
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

type CreateAutomationParams struct {
	Name                  string                `json:"name"`
	Prompt                *string               `json:"prompt"`
	Repos                 []byte                `json:"repos"`
	CreatedBy             pgtype.UUID           `json:"created_by"`
	TriggerType           AutomationTriggerType `json:"trigger_type"`
	TriggerConfig         []byte                `json:"trigger_config"`
	WebhookTokenHash      *string               `json:"webhook_token_hash"`
	SandboxPathScope      []byte                `json:"sandbox_path_scope"`
	SandboxMockConfigured bool                  `json:"sandbox_mock_configured"`
	SandboxContractsPath  *string               `json:"sandbox_contracts_path"`
	EnvVars               []byte                `json:"env_vars"`
}

// Queries backing AutomationStore ("automations: engine", §3.5;
// "automations: triggers & extras", §8.4), migrations/
// 000051_automations.up.sql, migrations/
// 000055_automations_triggers_and_extras.up.sql.
// §8.4's own real caller: httpapi.CreateAutomation (POST
// /api/automations). trigger_type/trigger_config/webhook_token_hash back
// this Step's own condition builder; sandbox_path_scope/
// sandbox_mock_configured/sandbox_contracts_path back §8.4's own
// "sandboxSettings honored on automation sessions"; env_vars back
// §8.4's own "per-automation env vars" (plain config, never a secret --
// see internal/domain/automation/doc.go's own deferral writeup).
func (q *Queries) CreateAutomation(ctx context.Context, arg CreateAutomationParams) (Automation, error) {
	row := q.db.QueryRow(ctx, createAutomation,
		arg.Name,
		arg.Prompt,
		arg.Repos,
		arg.CreatedBy,
		arg.TriggerType,
		arg.TriggerConfig,
		arg.WebhookTokenHash,
		arg.SandboxPathScope,
		arg.SandboxMockConfigured,
		arg.SandboxContractsPath,
		arg.EnvVars,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const getAutomation = `-- name: GetAutomation :one
SELECT id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since FROM automations
WHERE id = $1
`

func (q *Queries) GetAutomation(ctx context.Context, id pgtype.UUID) (Automation, error) {
	row := q.db.QueryRow(ctx, getAutomation, id)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const getAutomationByWebhookTokenHash = `-- name: GetAutomationByWebhookTokenHash :one
SELECT id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since FROM automations
WHERE webhook_token_hash = $1
`

// Backs the webhook trigger's own inbound-auth lookup (internal/adapters/
// inbound/httpapi's own automationwebhook.go): the presented bearer token
// is hashed (platform.HashToken, the SAME convention ws_tokens.token_hash
// already establishes) and looked up directly -- never a table scan
// comparing a plaintext token against every row, and never comparing an
// unhashed value against webhook_token_hash.
func (q *Queries) GetAutomationByWebhookTokenHash(ctx context.Context, webhookTokenHash *string) (Automation, error) {
	row := q.db.QueryRow(ctx, getAutomationByWebhookTokenHash, webhookTokenHash)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const listActiveCronAutomations = `-- name: ListActiveCronAutomations :many
SELECT id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since FROM automations
WHERE trigger_type = 'cron' AND status = 'active'
ORDER BY last_cron_fired_at ASC NULLS FIRST
`

// Backs the cron trigger pump's own per-tick scan (app/automation's own
// new triggerpump.go) -- every active, cron-triggered automation, oldest
// last_cron_fired_at first (NULLS FIRST: an automation that has never
// fired at all is always evaluated before one that has, on a tie, though
// in practice each row is evaluated every tick regardless of this
// ordering -- this just keeps output deterministic for tests).
func (q *Queries) ListActiveCronAutomations(ctx context.Context) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listActiveCronAutomations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.Repos,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.WebhookTokenHash,
			&i.LastCronFiredAt,
			&i.SandboxPathScope,
			&i.SandboxMockConfigured,
			&i.SandboxContractsPath,
			&i.EnvVars,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.ArtifactSummary,
			&i.CreatorUnauthorizedSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGitHubAutomations = `-- name: ListActiveGitHubAutomations :many
SELECT id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since FROM automations
WHERE trigger_type = 'github' AND status = 'active'
ORDER BY id ASC
`

// Backs the live GitHub webhook dispatch path (§8.4, app/automation's
// own githubdispatch.go, called inline from internal/adapters/inbound/
// github's own handler.go) -- every active, github-triggered automation,
// evaluated against each dispatchable webhook delivery. Mirrors
// ListActiveCronAutomations' own shape exactly, one row over, ordered by
// id only for deterministic test output (unlike the cron pump, there is no
// "last fired" column this trigger type advances).
func (q *Queries) ListActiveGitHubAutomations(ctx context.Context) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listActiveGitHubAutomations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.Repos,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.WebhookTokenHash,
			&i.LastCronFiredAt,
			&i.SandboxPathScope,
			&i.SandboxMockConfigured,
			&i.SandboxContractsPath,
			&i.EnvVars,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.ArtifactSummary,
			&i.CreatorUnauthorizedSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLinearAutomations = `-- name: ListActiveLinearAutomations :many
SELECT id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since FROM automations
WHERE trigger_type = 'linear' AND status = 'active'
ORDER BY id ASC
`

// The Linear twin of ListActiveGitHubAutomations immediately above --
// backs app/automation's own lineardispatch.go, called inline from
// internal/adapters/inbound/linear's own webhook.go.
func (q *Queries) ListActiveLinearAutomations(ctx context.Context) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listActiveLinearAutomations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.Repos,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.WebhookTokenHash,
			&i.LastCronFiredAt,
			&i.SandboxPathScope,
			&i.SandboxMockConfigured,
			&i.SandboxContractsPath,
			&i.EnvVars,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.ArtifactSummary,
			&i.CreatorUnauthorizedSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutomations = `-- name: ListAutomations :many
SELECT id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since FROM automations
WHERE ($1::uuid IS NULL OR created_by = $1)
  AND ($2::automation_status IS NULL OR status = $2)
ORDER BY created_at DESC
`

type ListAutomationsParams struct {
	CreatedBy pgtype.UUID       `json:"created_by"`
	Status    *AutomationStatus `json:"status"`
}

// Backs GET /api/automations (§8.4's own "creator/status
// filters"). Both filters are OPTIONAL and independent -- sqlc.narg's own
// "IS NULL OR" idiom means an absent (nil) filter matches every row, a
// present one narrows -- so this single query serves "all automations",
// "my automations" (createdBy set), "only paused" (status set), or both
// combined, with no dynamic SQL string-building on the Go side. Unbounded
// (no pagination), matching this codebase's own established "expected to
// stay small" precedent for a workspace-wide list (ListMembers's own
// identical shape).
func (q *Queries) ListAutomations(ctx context.Context, arg ListAutomationsParams) ([]Automation, error) {
	rows, err := q.db.Query(ctx, listAutomations, arg.CreatedBy, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Automation
	for rows.Next() {
		var i Automation
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prompt,
			&i.Repos,
			&i.Status,
			&i.ConsecutiveFailures,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TriggerType,
			&i.TriggerConfig,
			&i.WebhookTokenHash,
			&i.LastCronFiredAt,
			&i.SandboxPathScope,
			&i.SandboxMockConfigured,
			&i.SandboxContractsPath,
			&i.EnvVars,
			&i.LastRunAt,
			&i.LastRunStatus,
			&i.ArtifactSummary,
			&i.CreatorUnauthorizedSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAutomationForUpdate = `-- name: LockAutomationForUpdate :one
SELECT id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since FROM automations
WHERE id = $1
FOR UPDATE
`

// Row-level lock backing the failure-strike accounting step
// (app/automation's own closeout.go): taken in the SAME transaction as
// MarkAutomationInvocationFailureCounted (queries/automationinvocations.sql)
// so two invocations belonging to the SAME automation that close (fail)
// concurrently apply their own automation.EvaluateFailureStrike
// consequence one at a time, never as a lost update racing against each
// other's own read-then-write of consecutive_failures.
func (q *Queries) LockAutomationForUpdate(ctx context.Context, id pgtype.UUID) (Automation, error) {
	row := q.db.QueryRow(ctx, lockAutomationForUpdate, id)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const markAutomationCreatorUnauthorized = `-- name: MarkAutomationCreatorUnauthorized :execrows
UPDATE automations
SET creator_unauthorized_since = now()
WHERE id = $1 AND creator_unauthorized_since IS NULL
`

// U8 audit fix -- backs app/automation's own dispatchOneGitHubAutomation/
// dispatchOneLinearAutomation, called the moment a machine-origin
// dispatch is denied because this automation's own created_by is not a
// linked, non-disabled account holding authz.ActionCreateSession
// (migrations/000138_automations_creator_unauthorized.up.sql's own doc
// comment). "AND creator_unauthorized_since IS NULL" makes this
// idempotent AND preserves the FIRST denial's own timestamp -- a
// still-broken automation firing its trigger repeatedly must not keep
// sliding this forward, or a maintainer reading it would see only "just
// now", never how long this has actually been broken.
func (q *Queries) MarkAutomationCreatorUnauthorized(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAutomationCreatorUnauthorized, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const pauseAutomation = `-- name: PauseAutomation :one
UPDATE automations
SET status = 'paused',
    updated_at = now()
WHERE id = $1 AND status = 'active'
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

// The manual-admin twin of ResumeAutomation below: backs internal/domain/
// automation.TriggerAutoPause applied by a direct admin action (POST
// /api/automations/{id}/pause) rather than the auto-pause path -- automation.
// go's own doc comment on TriggerAutoPause already anticipates exactly
// this reuse ("Transition supports the edge regardless, since pausing and
// auto-pausing land on the identical Status either way"). Guarded by "AND
// status = 'active'" so a non-active automation's own pause attempt
// affects zero rows, mirroring ResumeAutomation's own identical "AND
// status = 'paused'" guard.
func (q *Queries) PauseAutomation(ctx context.Context, id pgtype.UUID) (Automation, error) {
	row := q.db.QueryRow(ctx, pauseAutomation, id)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const resetConsecutiveFailures = `-- name: ResetConsecutiveFailures :execrows
UPDATE automations
SET consecutive_failures = 0,
    updated_at = now()
WHERE id = $1 AND consecutive_failures <> 0
`

// A succeeded invocation resets its own automation's streak to zero --
// idempotent (no CAS guard needed the way the failure path needs one,
// §3.5's own "at-most-one failure strike" requirement does not apply to a
// success: applying this reset twice is harmless, unlike double-counting
// a failure). "AND consecutive_failures <> 0" is a pure no-op-avoidance
// optimization (skip a write when there is nothing to reset), never a
// correctness guard.
func (q *Queries) ResetConsecutiveFailures(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resetConsecutiveFailures, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resumeAutomation = `-- name: ResumeAutomation :one
UPDATE automations
SET status = 'active',
    consecutive_failures = 0,
    updated_at = now()
WHERE id = $1 AND status = 'paused'
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

// Backs automation.TriggerResume (internal/domain/automation) -- no HTTP
// caller exists yet in this Step (§8.4/§10 own the actual "Resume"
// button, mockups.html's own Automations view), reserved so that surface
// needs no store-layer change to use it. Guarded by "AND status =
// 'paused'" so a non-paused automation's own resume attempt affects zero
// rows rather than silently no-op-writing an already-active row.
func (q *Queries) ResumeAutomation(ctx context.Context, id pgtype.UUID) (Automation, error) {
	row := q.db.QueryRow(ctx, resumeAutomation, id)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const revokeAutomationWebhookToken = `-- name: RevokeAutomationWebhookToken :one
UPDATE automations
SET webhook_token_hash = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

// Review fix, same finding as RotateAutomationWebhookToken above -- backs
// DELETE /api/automations/{automationID}/webhook-token. Clears
// webhook_token_hash to NULL unconditionally (no trigger_type guard,
// unlike rotate): clearing an already-NULL hash on a non-webhook
// automation is a harmless no-op, and the caller (httpapi.
// RevokeAutomationWebhookToken) already runs its own existence check
// first, mirroring Pause/Resume's identical "existence check, then a
// guarded/unconditional single-row UPDATE" shape. Once this commits, the
// automation has NO webhook_token_hash at all -- every future call to its
// own inbound webhook endpoint 401s (GetAutomationByWebhookTokenHash
// simply never matches a NULL-hash row, since that lookup only ever
// searches by a hashed VALUE, never by presence/absence) until a
// subsequent RotateAutomationWebhookToken mints a new one.
func (q *Queries) RevokeAutomationWebhookToken(ctx context.Context, id pgtype.UUID) (Automation, error) {
	row := q.db.QueryRow(ctx, revokeAutomationWebhookToken, id)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const rotateAutomationWebhookToken = `-- name: RotateAutomationWebhookToken :one
UPDATE automations
SET webhook_token_hash = $2,
    updated_at = now()
WHERE id = $1 AND trigger_type = 'webhook'
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

type RotateAutomationWebhookTokenParams struct {
	ID               pgtype.UUID `json:"id"`
	WebhookTokenHash *string     `json:"webhook_token_hash"`
}

// Review fix ("webhook token has no rotation/revocation/expiry"): backs
// POST /api/automations/{automationID}/webhook-token. Mints a FRESH
// webhook_token_hash (the caller has already generated a new plaintext
// token via platform.GenerateToken()/HashToken(), the SAME mint step
// CreateAutomation itself already runs) and overwrites the old one
// outright -- the old hash stops matching GetAutomationByWebhookTokenHash
// the instant this commits, with no grace period. Guarded by "AND
// trigger_type = 'webhook'" so rotating a token on a non-webhook
// automation (which never had a webhook_token_hash to begin with) affects
// zero rows rather than silently writing a hash column that
// GetAutomationByWebhookTokenHash's own trigger_type check
// (automationwebhook/handler.go) would never actually honor anyway.
func (q *Queries) RotateAutomationWebhookToken(ctx context.Context, arg RotateAutomationWebhookTokenParams) (Automation, error) {
	row := q.db.QueryRow(ctx, rotateAutomationWebhookToken, arg.ID, arg.WebhookTokenHash)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}

const updateAutomationLastRun = `-- name: UpdateAutomationLastRun :one
UPDATE automations
SET last_run_at = $2,
    last_run_status = $3,
    artifact_summary = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, prompt, repos, status, consecutive_failures, created_by, created_at, updated_at, trigger_type, trigger_config, webhook_token_hash, last_cron_fired_at, sandbox_path_scope, sandbox_mock_configured, sandbox_contracts_path, env_vars, last_run_at, last_run_status, artifact_summary, creator_unauthorized_since
`

type UpdateAutomationLastRunParams struct {
	ID              pgtype.UUID                 `json:"id"`
	LastRunAt       pgtype.Timestamptz          `json:"last_run_at"`
	LastRunStatus   *AutomationInvocationStatus `json:"last_run_status"`
	ArtifactSummary *string                     `json:"artifact_summary"`
}

// Backs §8.4's own "last_run + artifact_summary populated" -- called by
// app/automation's own closeout.go, the SAME closeInvocation call site
// that already resets/increments consecutive_failures, the moment an
// invocation's own outcome is decided. last_run_status reuses
// automation_invocation_status verbatim (never a new, parallel taxonomy).
func (q *Queries) UpdateAutomationLastRun(ctx context.Context, arg UpdateAutomationLastRunParams) (Automation, error) {
	row := q.db.QueryRow(ctx, updateAutomationLastRun,
		arg.ID,
		arg.LastRunAt,
		arg.LastRunStatus,
		arg.ArtifactSummary,
	)
	var i Automation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Prompt,
		&i.Repos,
		&i.Status,
		&i.ConsecutiveFailures,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TriggerType,
		&i.TriggerConfig,
		&i.WebhookTokenHash,
		&i.LastCronFiredAt,
		&i.SandboxPathScope,
		&i.SandboxMockConfigured,
		&i.SandboxContractsPath,
		&i.EnvVars,
		&i.LastRunAt,
		&i.LastRunStatus,
		&i.ArtifactSummary,
		&i.CreatorUnauthorizedSince,
	)
	return i, err
}
