// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one

WITH session_row AS MATERIALIZED (
    SELECT sessions.id FROM sessions WHERE sessions.id = $1 FOR NO KEY UPDATE
)
INSERT INTO events (session_id, type, message_id, payload)
SELECT $1, $2::text, $3::text, $4::jsonb
FROM session_row
ON CONFLICT (session_id, message_id) DO UPDATE SET type = events.type
RETURNING id, session_id, type, payload, created_at, message_id, (xmax = 0) AS inserted
`

type CreateEventParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Type      string      `json:"type"`
	MessageID string      `json:"message_id"`
	Payload   []byte      `json:"payload"`
}

type CreateEventRow struct {
	ID        int64              `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	Type      string             `json:"type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	MessageID string             `json:"message_id"`
	Inserted  bool               `json:"inserted"`
}

// Queries backing EventStore (§4.3, §6.1's append-only per-session event
// log). CreateEvent appends; ListEventsForSession is the cursor-paginated
// read this same table's own migration comment predicted ("reads
// (cursor-paginated fetch_history) land with the client WS hub") -- this
// is that work, backing both the client WS hub's own
// fetch_history/replay and the REST GET .../events endpoint (one
// implementation, two callers).
// Upsert-on-(session_id, message_id) (§6.1: "receiver dedupes by
// upsert-on-messageId") -- a resend of an already-seen messageId hits the
// unique index (migrations/000019_events_message_id.up.sql) and this
// DO UPDATE (a deliberate, self-referential no-op: type is set back to
// its own current value) guarantees RETURNING yields exactly one row
// either way for an existing session, so callers never need a separate
// "0 rows means duplicate" branch. `(xmax = 0) AS inserted` is the
// standard Postgres idiom for "was this row just inserted by THIS
// statement" (xmax is 0 only immediately after a fresh insert, non-zero
// after any update) -- callers use it to decide whether to (re-)broadcast
// this event to live subscribers.
//
// # Why the session row is locked before the id is drawn
//
// Every `id > cursor` reader of this table -- ListEventsForSession's own
// REST/fetch_history pagination, the web client's backfill (web/src/ws/
// sessionStream.ts, highestId()), MaxEventIDForSession's high-water
// mark -- relies on one guarantee: within one session, ids are allocated
// in commit order. events.id is a single global sequence, and nextval
// runs when the row is formed, not when it commits, so that guarantee
// only holds if every insert for a session is serialized on something
// per-session BEFORE nextval runs.
//
// The session actor already serializes its own writes on the session row
// (GetSessionActorEpochForUpdate, FOR UPDATE, the first statement of
// every transact). Writers outside the actor -- httpapi's upload confirm,
// uploadsweep, ShadowSCMWriteStore.AppendSuppressionEvent -- did not: a
// plain INSERT reaches the session row only through the foreign-key
// check, which runs at the end of the statement, after nextval. Such a
// writer drew id N, then blocked on the actor's lock; the actor's next
// event drew N+1 and committed first; a reader between the two commits
// saw N+1, moved its cursor past N, and never saw N.
//
// session_row takes that per-session lock inside this statement, so it
// covers every caller -- in a transaction or autocommit, present or
// future -- without any of them having to remember to. In the plan the
// CTE is a LockRows node under the CTE Scan whose output projection is
// where nextval('events_id_seq') is evaluated, so the id is drawn only
// once the lock is granted. MATERIALIZED states that ordering rather
// than enabling it: Postgres 17 plans the NOT MATERIALIZED form
// identically.
//
// FOR NO KEY UPDATE is the weakest mode that conflicts both with itself
// (two outside writers serialize) and with the actor's FOR UPDATE, while
// not conflicting with FOR KEY SHARE, so it never blocks the foreign-key
// checks of inserts into other tables that reference sessions. FOR KEY
// SHARE or FOR SHARE here would still wait behind the actor, but would
// let two outside writers interleave exactly as before. Inside the
// actor's own transaction it waits for nothing: that transaction already
// holds FOR UPDATE. The lock is held until the inserting transaction
// ends, which is exactly the window in which a later id must not become
// visible first.
//
// A nonexistent session yields no session_row, so nothing is inserted and
// RETURNING yields no row: the caller gets pgx.ErrNoRows (previously the
// foreign-key violation, SQLSTATE 23503). Every caller treats either as a
// failure; none inspects the error code.
//
// Two sqlc-driven details: the CTE qualifies sessions.id because sqlc
// resolves it with the INSERT's target table in scope (a bare `id` is
// reported ambiguous), and the select list inserts sqlc.arg(session_id)
// rather than session_row.id -- the same value, gated by FROM
// session_row either way -- so sqlc numbers session_id $1 and
// CreateEventParams keeps its field order.
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.SessionID,
		arg.Type,
		arg.MessageID,
		arg.Payload,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
		&i.MessageID,
		&i.Inserted,
	)
	return i, err
}

const getBootP95InWindow = `-- name: GetBootP95InWindow :one
SELECT
    COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY (payload->>'seconds')::float8), 0)::float8 AS p95_seconds,
    COUNT(*)::bigint AS sample_size
FROM events
WHERE type = 'boot_timing'
  AND payload->>'metric' = 'boot_duration'
  AND created_at >= $1
  AND (payload->>'failed' IS NULL OR payload->>'failed' = 'false')
`

type GetBootP95InWindowRow struct {
	P95Seconds float64 `json:"p95_seconds"`
	SampleSize int64   `json:"sample_size"`
}

// §12.2 item 6's own "Boot p95" KPI tile. Reads the SAME
// best-effort "boot_timing" sandbox-ws event (§33.3, contracts/sandbox-ws/
// v1/events.schema.json's own BootTiming def) internal/app/sessionactor's
// own recordBootTiming (boottiming.go) already relays into the
// sandbox_agent_boot_duration_seconds OTel histogram -- this is a
// DIFFERENT consumer of the identical already-persisted fact (every
// recognized event type is persisted verbatim, unconditionally,
// appendRawEvent's own "persist ALWAYS" contract), not a second
// measurement.
//
// metric = 'boot_duration' selects the ONE of the four boot_timing
// metrics that measures a whole boot-to-ready sequence (the other three
// -- hook_rerun/git_fetch/git_checkout -- are sub-phases, not what "Boot
// p95" names). failed IS NULL OR failed = 'false' excludes a boot attempt
// that measured a duration but did not actually succeed -- "p95 boot
// latency" answers "how long does a boot normally take", which a failed
// attempt's own elapsed time (however long the sandbox spent failing to
// boot) does not honestly represent; a failed-boot rate is a separate,
// NOT-yet-built concern this tile does not conflate itself with.
//
// p95_seconds is percentile_cont(0.95) over every admitted sample's own
// (payload->>'seconds')::float8, COALESCEd to 0 rather than left NULL --
// mirrors GetPlatformCostSummaryInWindow's own identical
// median_cost_usd_per_session treatment (queries/turns.sql) and for the
// same reason: the caller gates on sample_size alone and must never read
// this column when the gate fails, so collapsing NULL to a real,
// always-scannable 0::float8 here avoids depending on sqlc's own
// nullability inference for an aggregate expression (which does not
// reliably mark this NULLable) and the runtime "cannot scan NULL into
// *float64" it would otherwise risk for the empty/too-few-samples case.
// sample_size is additionally the input to a SECOND gate the caller
// applies on top of "zero samples" -- a real but small sample count
// (fewer than platformanalytics.MinBootP95Samples) still renders "too
// few samples", because a percentile computed over a handful of points
// is not a percentile anyone should trust, even though Postgres will
// always compute SOME number for it.
//
// Bounded by events_boot_timing_created_at_idx (migrations/
// 000125_platform_analytics_indexes.up.sql).
func (q *Queries) GetBootP95InWindow(ctx context.Context, createdAt pgtype.Timestamptz) (GetBootP95InWindowRow, error) {
	row := q.db.QueryRow(ctx, getBootP95InWindow, createdAt)
	var i GetBootP95InWindowRow
	err := row.Scan(&i.P95Seconds, &i.SampleSize)
	return i, err
}

const listEventsForSession = `-- name: ListEventsForSession :many
SELECT id, session_id, type, payload, created_at, message_id FROM events
WHERE session_id = $1 AND id > $2
ORDER BY id ASC
LIMIT $3
`

type ListEventsForSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	ID        int64       `json:"id"`
	Limit     int32       `json:"limit"`
}

// afterID = 0 means "from the beginning" -- matches a null fetch_history
// cursor / a REST ?cursor= default. The monotonic BIGSERIAL id is the
// natural pagination cursor (events_session_id_id_idx,
// migrations/000008_events.up.sql's own doc comment).
func (q *Queries) ListEventsForSession(ctx context.Context, arg ListEventsForSessionParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForSession, arg.SessionID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEventsForSession = `-- name: ListRecentEventsForSession :many
SELECT id, session_id, type, payload, created_at, message_id FROM events
WHERE session_id = $1
ORDER BY id DESC
LIMIT $2
`

type ListRecentEventsForSessionParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Limit     int32       `json:"limit"`
}

// The mirror-image pagination direction from ListEventsForSession's own
// oldest-first cursor page: returns up to $2 of session_id's own MOST
// RECENT events, newest id first -- for a caller that needs only the TAIL
// of a possibly-long event log (e.g. sessionactor.planContentText's own
// best-effort plan-content extraction, §8.1) without scanning forward
// from the very beginning of a session's entire history, which for a
// long-lived session (many prior turns) could leave the CURRENT turn's
// own events entirely outside a bounded oldest-first window. Same
// events_session_id_id_idx index (migrations/000008_events.up.sql) serves
// this DESC scan equally well.
func (q *Queries) ListRecentEventsForSession(ctx context.Context, arg ListRecentEventsForSessionParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRecentEventsForSession, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubTaskFinishEventsForTurn = `-- name: ListSubTaskFinishEventsForTurn :many
SELECT id, session_id, type, payload, created_at, message_id FROM events
WHERE session_id = $1
  AND type = 'sub_task_finish'
  AND (payload->>'gen')::int = $2::int
  AND id > $3::bigint
ORDER BY id ASC
`

type ListSubTaskFinishEventsForTurnParams struct {
	SessionID         pgtype.UUID `json:"session_id"`
	Gen               int32       `json:"gen"`
	DispatchedEventID int64       `json:"dispatched_event_id"`
}

func (q *Queries) ListSubTaskFinishEventsForTurn(ctx context.Context, arg ListSubTaskFinishEventsForTurnParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSubTaskFinishEventsForTurn, arg.SessionID, arg.Gen, arg.DispatchedEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubTaskStartEventsForTurn = `-- name: ListSubTaskStartEventsForTurn :many

SELECT id, session_id, type, payload, created_at, message_id FROM events
WHERE session_id = $1
  AND type = 'sub_task_start'
  AND (payload->>'gen')::int = $2::int
  AND id > $3::bigint
ORDER BY id ASC
`

type ListSubTaskStartEventsForTurnParams struct {
	SessionID         pgtype.UUID `json:"session_id"`
	Gen               int32       `json:"gen"`
	DispatchedEventID int64       `json:"dispatched_event_id"`
}

// (§26.4/§7.1's own post-hoc sub-task corroboration): the two
// queries below are this codebase's FIRST use of a payload->>'gen' JSONB
// extraction filter -- checked against the rest of this file and every
// other file in this directory before writing these, since there is no
// existing precedent for filtering events by a field INSIDE payload
// rather than by one of the table's own real columns (session_id, type,
// id). Every sandbox-ws wire event, sub_task_start and sub_task_finish
// included, carries its own "gen" field in the common envelope
// (contracts/sandbox-ws/v1/events.schema.json) -- the SAME sandbox
// generation the emitting sandbox process was live at when it produced
// the event, distinct from the events TABLE's own session-scoped id
// column, which has no gen concept of its own at all.
//
// # gen alone is NOT sufficient -- see the dispatched_event_id bound below
//
// An earlier version of these two queries (this same Step, before an
// adversarial review of the PR caught this) scoped strictly to
// (session_id, type, gen) on the theory that gen alone uniquely identifies
// a turn's own dispatch. It does not: turns.dispatched_sandbox_gen
// (migrations/000026_turn_dispatch_gen.up.sql) reuses sandboxes.gen, the
// fencing idiom bumped ONLY on a fresh spawn/restore/resume
// (internal/app/sessionactor's own planFreshSpawn/planRestore/planResume,
// `gen = gen + 1`) -- NEVER on an ordinary dispatch to an already-live
// (Ready/Suspect) sandbox. tryPlanDispatch (dispatch.go), the path used
// whenever a Pending turn is dispatched to a sandbox that is already up,
// stamps dispatched_sandbox_gen := sandboxRow.Gen VERBATIM, with no bump.
// So a session whose sandbox stays alive across multiple review turns --
// the ORDINARY case §24's automatic re-review on new commits describes,
// not a rare corner case -- dispatches every one of those turns at the
// SAME gen. Scoping by gen alone therefore lets an EARLIER turn's own
// real, genuinely-completed counter-review trace spuriously corroborate a
// LATER turn's self-report, simply because both turns happened to run on
// the same still-live sandbox incarnation: exactly the unverified-self-
// report bypass this whole Step exists to close, reopened.
//
// The fix: an ADDITIONAL `id > sqlc.arg('dispatched_event_id')` lower
// bound, using the turn-being-verdicted's own turns.dispatched_event_id
// (migrations/000089_turns_dispatched_event_id.up.sql): the events-log
// high-water mark, MAX(events.id) for this session, stamped in the same
// transaction as the dispatch itself. turns_one_processing_per_session's
// own unique partial index (migrations/000005_turns.up.sql) guarantees
// turns execute strictly sequentially per session, so every event
// genuinely belonging to THIS turn has an id above this turn's own
// watermark, and every event belonging to an EARLIER turn on the same
// session was inserted before this turn was ever dispatched -- excluded by
// this bound regardless of whether gen happens to match.
//
// This bound was originally written as `created_at >= dispatched_at`, and
// that version was NOT sound: it compared events.created_at (stamped by
// the POSTGRES server's own now(), migrations/000008_events.up.sql)
// against turns.dispatched_at (a Go time.Time supplied by the APPLICATION
// process, on a different host in any real deployment). Two clocks, agreeing
// only to whatever precision NTP happens to hold -- and asymmetric in their
// failure: an app clock running BEHIND the database widens the window and
// readmits an earlier turn's trace, eroding exactly the cross-turn guard
// this bound exists to provide. events.id is a BIGSERIAL assigned by the
// one database (migrations/000008_events.up.sql), so this comparison now
// has no clock in it at all. See that migration's own doc comment for why
// turns.dispatched_at is deliberately left in place and untouched (it has
// a genuine same-clock consumer in turn.EvaluateTurnDeadline).
//
// Neither condition alone is enough; both stay, because each closes a
// DIFFERENT, independent gap:
//   - gen alone: as above, cannot distinguish two turns dispatched to the
//     SAME live sandbox incarnation (no gen bump between them).
//   - dispatched_event_id alone: cannot distinguish a genuinely different,
//     now-dead sandbox INCARNATION's stale, late-arriving event from a
//     current one -- a sub_task_finish sent by an old sandbox process
//     right before it died can be delivered late over the network and land
//     in Postgres (and so receive an id) AFTER a LATER turn's own
//     watermark, even though it carries the OLD gen in its own payload.
//     The gen filter is what excludes that stale cross-incarnation row;
//     the id bound alone would not.
//
// Together: gen excludes cross-INCARNATION contamination (a different,
// dead sandbox process); dispatched_event_id excludes cross-TURN-same-
// incarnation contamination (an earlier turn dispatched to the SAME
// still-live sandbox). The `::int` cast on gen is safe here specifically
// because "gen" is schema-typed as a JSON integer on every event this
// filters (never a string, unlike some other payload fields elsewhere in
// this schema) -- a malformed/absent "gen" on some hypothetical future
// producer would fail the cast (or NULL-compare against the arg, matching
// nothing) rather than silently matching every gen, so this filter fails
// toward "matches nothing", never toward "over-matches" -- the same
// fail-conservative direction this codebase's own closed-enum defaults
// already commit to elsewhere (review/doc.go's "fail-conservative policy
// for every closed enum" section). The caller (corroborateCounterReview,
// internal/adapters/inbound/httpapi/reviewverdict.go) applies the
// identical fail-conservative treatment when dispatched_event_id itself is
// NULL (should be unreachable -- a turn being verdicted is by definition
// already dispatched -- but never assumed).
func (q *Queries) ListSubTaskStartEventsForTurn(ctx context.Context, arg ListSubTaskStartEventsForTurnParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSubTaskStartEventsForTurn, arg.SessionID, arg.Gen, arg.DispatchedEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxEventIDForSession = `-- name: MaxEventIDForSession :one
SELECT COALESCE(MAX(id), 0)::bigint AS max_event_id FROM events WHERE session_id = $1
`

// The events-log high-water mark for one session, stamped into
// turns.dispatched_event_id at dispatch (tryPlanDispatch/tryPlanReenqueue,
// internal/app/sessionactor/dispatch.go) and used as the lower bound of
// the two corroboration queries above. COALESCE to 0 so a session with no
// events yet yields a real watermark rather than NULL -- 0 is below every
// BIGSERIAL id (which starts at 1), so a turn dispatched before any event
// exists correctly admits every event that follows it.
//
// A high-water mark is only sound because, within one session, ids are
// allocated in commit order: every insert takes the session row lock
// before drawing its id and holds it until its transaction ends
// (CreateEvent above). So every event of this session that this read
// cannot see yet -- in flight or still to come -- gets an id above every
// id it can see, and `id > watermark` misses none of them. The id is
// drawn at insert, not at commit; it is the per-session lock, not the
// sequence, that makes id order commit order.
func (q *Queries) MaxEventIDForSession(ctx context.Context, sessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, maxEventIDForSession, sessionID)
	var max_event_id int64
	err := row.Scan(&max_event_id)
	return max_event_id, err
}
