// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_oauth_access_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPOAuthAccessToken = `-- name: CreateMCPOAuthAccessToken :one

INSERT INTO mcp_oauth_access_tokens (grant_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, grant_id, token_hash, expires_at, created_at
`

type CreateMCPOAuthAccessTokenParams struct {
	GrantID   pgtype.UUID        `json:"grant_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries backing MCPOAuthGrantStore's access-token half (technical plan
// §43.16, migrations/000141_mcp_oauth.up.sql).
//
// LookupMCPOAuthAccessToken is the /mcp bearer check's ONE query per
// call: the token, its grant, its client and its user in a single join, so
// every fact that can revoke the call (token or grant expiry, a deleted
// grant, a disabled or deleted client, a disabled user, a changed role, a
// foreign resource) is re-read on every request. There is no cache of any
// kind in front of it (auth.RequireMCPBearer's own doc comment).
func (q *Queries) CreateMCPOAuthAccessToken(ctx context.Context, arg CreateMCPOAuthAccessTokenParams) (McpOauthAccessToken, error) {
	row := q.db.QueryRow(ctx, createMCPOAuthAccessToken, arg.GrantID, arg.TokenHash, arg.ExpiresAt)
	var i McpOauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredMCPOAuthAccessTokens = `-- name: DeleteExpiredMCPOAuthAccessTokens :execrows
DELETE FROM mcp_oauth_access_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredMCPOAuthAccessTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMCPOAuthAccessTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lookupMCPOAuthAccessToken = `-- name: LookupMCPOAuthAccessToken :one
SELECT t.id AS token_id, t.expires_at AS token_expires_at,
       g.id AS grant_id, g.scopes, g.resource, g.expires_at AS grant_expires_at, g.last_used_at,
       c.client_id AS client_public_id, c.disabled_at AS client_disabled_at,
       u.id AS user_id, u.role AS user_role, u.primary_email, u.disabled AS user_disabled
FROM mcp_oauth_access_tokens t
JOIN mcp_oauth_grants g ON g.id = t.grant_id
JOIN mcp_oauth_clients c ON c.id = g.client_id
JOIN users u ON u.id = g.user_id
WHERE t.token_hash = $1
`

type LookupMCPOAuthAccessTokenRow struct {
	TokenID          pgtype.UUID        `json:"token_id"`
	TokenExpiresAt   pgtype.Timestamptz `json:"token_expires_at"`
	GrantID          pgtype.UUID        `json:"grant_id"`
	Scopes           []string           `json:"scopes"`
	Resource         string             `json:"resource"`
	GrantExpiresAt   pgtype.Timestamptz `json:"grant_expires_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	ClientPublicID   string             `json:"client_public_id"`
	ClientDisabledAt pgtype.Timestamptz `json:"client_disabled_at"`
	UserID           pgtype.UUID        `json:"user_id"`
	UserRole         UserRole           `json:"user_role"`
	PrimaryEmail     string             `json:"primary_email"`
	UserDisabled     bool               `json:"user_disabled"`
}

func (q *Queries) LookupMCPOAuthAccessToken(ctx context.Context, tokenHash string) (LookupMCPOAuthAccessTokenRow, error) {
	row := q.db.QueryRow(ctx, lookupMCPOAuthAccessToken, tokenHash)
	var i LookupMCPOAuthAccessTokenRow
	err := row.Scan(
		&i.TokenID,
		&i.TokenExpiresAt,
		&i.GrantID,
		&i.Scopes,
		&i.Resource,
		&i.GrantExpiresAt,
		&i.LastUsedAt,
		&i.ClientPublicID,
		&i.ClientDisabledAt,
		&i.UserID,
		&i.UserRole,
		&i.PrimaryEmail,
		&i.UserDisabled,
	)
	return i, err
}
