// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_oauth_clients.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPOAuthClient = `-- name: CreateMCPOAuthClient :one

INSERT INTO mcp_oauth_clients (client_id, kind, client_name, client_uri, redirect_uris, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_id, kind, client_name, client_uri, redirect_uris, created_by, created_at, disabled_at
`

type CreateMCPOAuthClientParams struct {
	ClientID     string             `json:"client_id"`
	Kind         McpOauthClientKind `json:"kind"`
	ClientName   string             `json:"client_name"`
	ClientUri    *string            `json:"client_uri"`
	RedirectUris []string           `json:"redirect_uris"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
}

// Queries backing MCPOAuthClientStore (technical plan §43.15,
// migrations/000141_mcp_oauth.up.sql): the OAuth clients an MCP client
// program identifies itself as. client_id is the public identifier a
// client sends; id is the internal key every other mcp_oauth_* table
// references. DeleteMCPOAuthClient cascades every grant, pending
// authorization request, code and access token issued to the client.
func (q *Queries) CreateMCPOAuthClient(ctx context.Context, arg CreateMCPOAuthClientParams) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, createMCPOAuthClient,
		arg.ClientID,
		arg.Kind,
		arg.ClientName,
		arg.ClientUri,
		arg.RedirectUris,
		arg.CreatedBy,
	)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Kind,
		&i.ClientName,
		&i.ClientUri,
		&i.RedirectUris,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const deleteMCPOAuthClient = `-- name: DeleteMCPOAuthClient :one
DELETE FROM mcp_oauth_clients
WHERE id = $1
RETURNING id, client_id, kind, client_name, client_uri, redirect_uris, created_by, created_at, disabled_at
`

func (q *Queries) DeleteMCPOAuthClient(ctx context.Context, id pgtype.UUID) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, deleteMCPOAuthClient, id)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Kind,
		&i.ClientName,
		&i.ClientUri,
		&i.RedirectUris,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getMCPOAuthClientByClientID = `-- name: GetMCPOAuthClientByClientID :one
SELECT id, client_id, kind, client_name, client_uri, redirect_uris, created_by, created_at, disabled_at FROM mcp_oauth_clients
WHERE client_id = $1
`

func (q *Queries) GetMCPOAuthClientByClientID(ctx context.Context, clientID string) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, getMCPOAuthClientByClientID, clientID)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Kind,
		&i.ClientName,
		&i.ClientUri,
		&i.RedirectUris,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const getMCPOAuthClientByID = `-- name: GetMCPOAuthClientByID :one
SELECT id, client_id, kind, client_name, client_uri, redirect_uris, created_by, created_at, disabled_at FROM mcp_oauth_clients
WHERE id = $1
`

func (q *Queries) GetMCPOAuthClientByID(ctx context.Context, id pgtype.UUID) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, getMCPOAuthClientByID, id)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Kind,
		&i.ClientName,
		&i.ClientUri,
		&i.RedirectUris,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.DisabledAt,
	)
	return i, err
}

const listMCPOAuthClients = `-- name: ListMCPOAuthClients :many
SELECT id, client_id, kind, client_name, client_uri, redirect_uris, created_by, created_at, disabled_at FROM mcp_oauth_clients
ORDER BY created_at, id
`

func (q *Queries) ListMCPOAuthClients(ctx context.Context) ([]McpOauthClient, error) {
	rows, err := q.db.Query(ctx, listMCPOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []McpOauthClient
	for rows.Next() {
		var i McpOauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Kind,
			&i.ClientName,
			&i.ClientUri,
			&i.RedirectUris,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.DisabledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
