// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_oauth_refresh_tokens.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPOAuthRefreshToken = `-- name: CreateMCPOAuthRefreshToken :one

INSERT INTO mcp_oauth_refresh_tokens (grant_id, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, grant_id, token_hash, scopes, expires_at, created_at, rotated_at, superseded_by
`

type CreateMCPOAuthRefreshTokenParams struct {
	GrantID   pgtype.UUID        `json:"grant_id"`
	TokenHash string             `json:"token_hash"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries backing MCPOAuthGrantStore's refresh-token half (technical plan
// §43.16, migrations/000142_mcp_oauth_refresh_tokens.up.sql).
//
// RotateMCPOAuthRefreshToken is the single-use step: it marks a refresh
// token replaced at most once. When it returns nothing, the token was
// already rotated (or is gone): presenting it was a replay, and
// mcpauth's refresh grant then revokes its grant.
// GetMCPOAuthRefreshTokenByHash reads a token whether or not it was
// rotated, which is how a replay is recognised as one.
func (q *Queries) CreateMCPOAuthRefreshToken(ctx context.Context, arg CreateMCPOAuthRefreshTokenParams) (McpOauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createMCPOAuthRefreshToken,
		arg.GrantID,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i McpOauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.SupersededBy,
	)
	return i, err
}

const deleteExpiredMCPOAuthRefreshTokens = `-- name: DeleteExpiredMCPOAuthRefreshTokens :execrows
DELETE FROM mcp_oauth_refresh_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredMCPOAuthRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMCPOAuthRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMCPOAuthRefreshTokenByHash = `-- name: GetMCPOAuthRefreshTokenByHash :one
SELECT id, grant_id, token_hash, scopes, expires_at, created_at, rotated_at, superseded_by FROM mcp_oauth_refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetMCPOAuthRefreshTokenByHash(ctx context.Context, tokenHash string) (McpOauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getMCPOAuthRefreshTokenByHash, tokenHash)
	var i McpOauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.SupersededBy,
	)
	return i, err
}

const rotateMCPOAuthRefreshToken = `-- name: RotateMCPOAuthRefreshToken :one
UPDATE mcp_oauth_refresh_tokens
SET rotated_at = now(), superseded_by = $1
WHERE id = $2 AND rotated_at IS NULL
RETURNING id, grant_id, token_hash, scopes, expires_at, created_at, rotated_at, superseded_by
`

type RotateMCPOAuthRefreshTokenParams struct {
	SupersededBy pgtype.UUID `json:"superseded_by"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) RotateMCPOAuthRefreshToken(ctx context.Context, arg RotateMCPOAuthRefreshTokenParams) (McpOauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, rotateMCPOAuthRefreshToken, arg.SupersededBy, arg.ID)
	var i McpOauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.GrantID,
		&i.TokenHash,
		&i.Scopes,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.SupersededBy,
	)
	return i, err
}
