// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_oauth_grants.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPOAuthGrant = `-- name: CreateMCPOAuthGrant :one

INSERT INTO mcp_oauth_grants (user_id, client_id, scopes, resource, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, client_id, scopes, resource, created_at, expires_at, last_used_at
`

type CreateMCPOAuthGrantParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ClientID  pgtype.UUID        `json:"client_id"`
	Scopes    []string           `json:"scopes"`
	Resource  string             `json:"resource"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Queries backing MCPOAuthGrantStore's grant half (technical plan §43.16,
// migrations/000141_mcp_oauth.up.sql). A grant row exists iff the
// authorization is live: deleting it IS revocation, and every code and
// access token issued under it cascades with it.
//
// TouchMCPOAuthGrantLastUsed is the bearer check's own coalesced write:
// it only updates a row whose last_used_at is NULL or older than
// stale_before, so a busy client costs one write per interval, not one per
// call.
func (q *Queries) CreateMCPOAuthGrant(ctx context.Context, arg CreateMCPOAuthGrantParams) (McpOauthGrant, error) {
	row := q.db.QueryRow(ctx, createMCPOAuthGrant,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
		arg.Resource,
		arg.ExpiresAt,
	)
	var i McpOauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Resource,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredMCPOAuthGrants = `-- name: DeleteExpiredMCPOAuthGrants :execrows
DELETE FROM mcp_oauth_grants
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredMCPOAuthGrants(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMCPOAuthGrants)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMCPOAuthGrant = `-- name: DeleteMCPOAuthGrant :execrows
DELETE FROM mcp_oauth_grants
WHERE id = $1
`

func (q *Queries) DeleteMCPOAuthGrant(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMCPOAuthGrant, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMCPOAuthGrantForUser = `-- name: DeleteMCPOAuthGrantForUser :one
DELETE FROM mcp_oauth_grants
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, client_id, scopes, resource, created_at, expires_at, last_used_at
`

type DeleteMCPOAuthGrantForUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMCPOAuthGrantForUser(ctx context.Context, arg DeleteMCPOAuthGrantForUserParams) (McpOauthGrant, error) {
	row := q.db.QueryRow(ctx, deleteMCPOAuthGrantForUser, arg.ID, arg.UserID)
	var i McpOauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Resource,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getMCPOAuthGrant = `-- name: GetMCPOAuthGrant :one
SELECT id, user_id, client_id, scopes, resource, created_at, expires_at, last_used_at FROM mcp_oauth_grants
WHERE id = $1
`

func (q *Queries) GetMCPOAuthGrant(ctx context.Context, id pgtype.UUID) (McpOauthGrant, error) {
	row := q.db.QueryRow(ctx, getMCPOAuthGrant, id)
	var i McpOauthGrant
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.Resource,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listMCPOAuthGrantsForClient = `-- name: ListMCPOAuthGrantsForClient :many
SELECT id, user_id FROM mcp_oauth_grants
WHERE client_id = $1
ORDER BY created_at, id
`

type ListMCPOAuthGrantsForClientRow struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListMCPOAuthGrantsForClient(ctx context.Context, clientID pgtype.UUID) ([]ListMCPOAuthGrantsForClientRow, error) {
	rows, err := q.db.Query(ctx, listMCPOAuthGrantsForClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPOAuthGrantsForClientRow
	for rows.Next() {
		var i ListMCPOAuthGrantsForClientRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPOAuthGrantsForUser = `-- name: ListMCPOAuthGrantsForUser :many
SELECT g.id, g.scopes, g.created_at, g.expires_at, g.last_used_at,
       c.client_id AS client_public_id, c.client_name, c.kind AS client_kind
FROM mcp_oauth_grants g
JOIN mcp_oauth_clients c ON c.id = g.client_id
WHERE g.user_id = $1 AND g.expires_at > now()
ORDER BY g.created_at DESC, g.id
`

type ListMCPOAuthGrantsForUserRow struct {
	ID             pgtype.UUID        `json:"id"`
	Scopes         []string           `json:"scopes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	ClientPublicID string             `json:"client_public_id"`
	ClientName     string             `json:"client_name"`
	ClientKind     McpOauthClientKind `json:"client_kind"`
}

func (q *Queries) ListMCPOAuthGrantsForUser(ctx context.Context, userID pgtype.UUID) ([]ListMCPOAuthGrantsForUserRow, error) {
	rows, err := q.db.Query(ctx, listMCPOAuthGrantsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMCPOAuthGrantsForUserRow
	for rows.Next() {
		var i ListMCPOAuthGrantsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.ClientPublicID,
			&i.ClientName,
			&i.ClientKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchMCPOAuthGrantLastUsed = `-- name: TouchMCPOAuthGrantLastUsed :exec
UPDATE mcp_oauth_grants
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < $2)
`

type TouchMCPOAuthGrantLastUsedParams struct {
	ID          pgtype.UUID        `json:"id"`
	StaleBefore pgtype.Timestamptz `json:"stale_before"`
}

func (q *Queries) TouchMCPOAuthGrantLastUsed(ctx context.Context, arg TouchMCPOAuthGrantLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchMCPOAuthGrantLastUsed, arg.ID, arg.StaleBefore)
	return err
}
