// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_oauth_authorization_requests.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindMCPOAuthAuthorizationRequest = `-- name: BindMCPOAuthAuthorizationRequest :one
UPDATE mcp_oauth_authorization_requests
SET user_id = $1, csrf_nonce_hash = $2
WHERE id = $3
  AND (user_id IS NULL OR user_id = $1)
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, client_id, user_id, redirect_uri, scopes, state, code_challenge, code_challenge_method, resource, csrf_nonce_hash, expires_at, consumed_at, created_at
`

type BindMCPOAuthAuthorizationRequestParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	CsrfNonceHash *string     `json:"csrf_nonce_hash"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) BindMCPOAuthAuthorizationRequest(ctx context.Context, arg BindMCPOAuthAuthorizationRequestParams) (McpOauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, bindMCPOAuthAuthorizationRequest, arg.UserID, arg.CsrfNonceHash, arg.ID)
	var i McpOauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Resource,
		&i.CsrfNonceHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeMCPOAuthAuthorizationRequest = `-- name: ConsumeMCPOAuthAuthorizationRequest :one
UPDATE mcp_oauth_authorization_requests
SET consumed_at = now()
WHERE id = $1
  AND user_id = $2
  AND csrf_nonce_hash IS NOT NULL
  AND consumed_at IS NULL
  AND expires_at > now()
RETURNING id, client_id, user_id, redirect_uri, scopes, state, code_challenge, code_challenge_method, resource, csrf_nonce_hash, expires_at, consumed_at, created_at
`

type ConsumeMCPOAuthAuthorizationRequestParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) ConsumeMCPOAuthAuthorizationRequest(ctx context.Context, arg ConsumeMCPOAuthAuthorizationRequestParams) (McpOauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, consumeMCPOAuthAuthorizationRequest, arg.ID, arg.UserID)
	var i McpOauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Resource,
		&i.CsrfNonceHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countPendingMCPOAuthAuthorizationRequests = `-- name: CountPendingMCPOAuthAuthorizationRequests :one
SELECT count(*) FROM mcp_oauth_authorization_requests
WHERE client_id = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

// CountPendingMCPOAuthAuthorizationRequests counts the client's requests
// still waiting for a decision -- unexpired and not consumed, bound to a
// user or not -- which the pending-request cap bounds (technical plan
// §43.14). Run it under LockMCPOAuthClientForNewRequest, as a statement of
// its own: its snapshot is then taken once the lock is granted, so it
// counts every request an authorization that held the lock before it
// committed.
func (q *Queries) CountPendingMCPOAuthAuthorizationRequests(ctx context.Context, clientID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingMCPOAuthAuthorizationRequests, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMCPOAuthAuthorizationRequest = `-- name: CreateMCPOAuthAuthorizationRequest :one

INSERT INTO mcp_oauth_authorization_requests
    (client_id, redirect_uri, scopes, state, code_challenge, code_challenge_method, resource, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, client_id, user_id, redirect_uri, scopes, state, code_challenge, code_challenge_method, resource, csrf_nonce_hash, expires_at, consumed_at, created_at
`

type CreateMCPOAuthAuthorizationRequestParams struct {
	ClientID            pgtype.UUID        `json:"client_id"`
	RedirectUri         string             `json:"redirect_uri"`
	Scopes              []string           `json:"scopes"`
	State               *string            `json:"state"`
	CodeChallenge       string             `json:"code_challenge"`
	CodeChallengeMethod string             `json:"code_challenge_method"`
	Resource            string             `json:"resource"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
}

// Queries backing MCPOAuthGrantStore's authorization-request half
// (technical plan §43.14, migrations/000141_mcp_oauth.up.sql): one row per
// validated GET /oauth/authorize, waiting for the consent decision.
//
// BindMCPOAuthAuthorizationRequest is the consent page's own render step:
// it binds the request to the rendering user the FIRST time (user_id IS
// NULL) and refuses any other user afterwards, and it replaces the stored
// CSRF nonce hash with the hash of the nonce this render embeds -- in one
// statement, so two users racing to render the same request cannot both
// bind it. ConsumeMCPOAuthAuthorizationRequest is the decision's own
// single-use step: it succeeds at most once, only for the bound user,
// only once a nonce was ever minted, and only before expiry.
func (q *Queries) CreateMCPOAuthAuthorizationRequest(ctx context.Context, arg CreateMCPOAuthAuthorizationRequestParams) (McpOauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, createMCPOAuthAuthorizationRequest,
		arg.ClientID,
		arg.RedirectUri,
		arg.Scopes,
		arg.State,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Resource,
		arg.ExpiresAt,
	)
	var i McpOauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Resource,
		&i.CsrfNonceHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredMCPOAuthAuthorizationRequests = `-- name: DeleteExpiredMCPOAuthAuthorizationRequests :execrows
DELETE FROM mcp_oauth_authorization_requests
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredMCPOAuthAuthorizationRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMCPOAuthAuthorizationRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMCPOAuthAuthorizationRequest = `-- name: GetMCPOAuthAuthorizationRequest :one
SELECT id, client_id, user_id, redirect_uri, scopes, state, code_challenge, code_challenge_method, resource, csrf_nonce_hash, expires_at, consumed_at, created_at FROM mcp_oauth_authorization_requests
WHERE id = $1
`

func (q *Queries) GetMCPOAuthAuthorizationRequest(ctx context.Context, id pgtype.UUID) (McpOauthAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, getMCPOAuthAuthorizationRequest, id)
	var i McpOauthAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.Scopes,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Resource,
		&i.CsrfNonceHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
