// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owedreviewrequests.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOwedReviewRequest = `-- name: DeleteOwedReviewRequest :one
DELETE FROM owed_review_requests
WHERE id = $1
RETURNING id, session_id, requested_by, trigger, request_text, is_review_attempt, context_moves, moved_turn_id, created_at
`

// The consumer's delete of the request it serves, in the transaction that
// inserts its re-run turn or drops it. pgx.ErrNoRows when the row is
// already gone -- a person's stop dropped it while the consumer read the
// pull request -- and then nothing is re-run.
func (q *Queries) DeleteOwedReviewRequest(ctx context.Context, id pgtype.UUID) (OwedReviewRequest, error) {
	row := q.db.QueryRow(ctx, deleteOwedReviewRequest, id)
	var i OwedReviewRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestedBy,
		&i.Trigger,
		&i.RequestText,
		&i.IsReviewAttempt,
		&i.ContextMoves,
		&i.MovedTurnID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOwedReviewRequestsForStop = `-- name: DeleteOwedReviewRequestsForStop :many
DELETE FROM owed_review_requests
WHERE session_id = $1
  AND created_at <= $2
RETURNING id, session_id, requested_by, trigger, request_text, is_review_attempt, context_moves, moved_turn_id, created_at
`

type DeleteOwedReviewRequestsForStopParams struct {
	SessionID       pgtype.UUID        `json:"session_id"`
	StopRequestedAt pgtype.Timestamptz `json:"stop_requested_at"`
}

// A person's stop drops every request owed when it was made: the rows
// created at or before the session's standing stop request, the rule the
// stop timer deletes the session's work-creating timers by
// (sessionactor's disarmWorkCreatingTimers), compared with the same
// database clock. A request owed after the stop was made by a turn created
// after it, which the stop did not ask to drop.
func (q *Queries) DeleteOwedReviewRequestsForStop(ctx context.Context, arg DeleteOwedReviewRequestsForStopParams) ([]OwedReviewRequest, error) {
	rows, err := q.db.Query(ctx, deleteOwedReviewRequestsForStop, arg.SessionID, arg.StopRequestedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwedReviewRequest
	for rows.Next() {
		var i OwedReviewRequest
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.RequestedBy,
			&i.Trigger,
			&i.RequestText,
			&i.IsReviewAttempt,
			&i.ContextMoves,
			&i.MovedTurnID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const existsOwedReviewRequest = `-- name: ExistsOwedReviewRequest :one
SELECT EXISTS (
    SELECT 1 FROM owed_review_requests o
    WHERE o.session_id = $1
) AS owed
`

// Whether the session is still owed a request: the consumer re-arms its
// timer due at once when it is, and deletes it when it is not.
func (q *Queries) ExistsOwedReviewRequest(ctx context.Context, sessionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsOwedReviewRequest, sessionID)
	var owed bool
	err := row.Scan(&owed)
	return owed, err
}

const getOldestOwedReviewRequest = `-- name: GetOldestOwedReviewRequest :one
SELECT id, session_id, requested_by, trigger, request_text, is_review_attempt, context_moves, moved_turn_id, created_at FROM owed_review_requests
WHERE session_id = $1
ORDER BY created_at, id
LIMIT 1
`

// The session's oldest owed request, the one the owed_review_request
// timer's consumer serves next. id breaks a created_at tie, so the pick is
// reproducible. pgx.ErrNoRows: nothing is owed.
func (q *Queries) GetOldestOwedReviewRequest(ctx context.Context, sessionID pgtype.UUID) (OwedReviewRequest, error) {
	row := q.db.QueryRow(ctx, getOldestOwedReviewRequest, sessionID)
	var i OwedReviewRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestedBy,
		&i.Trigger,
		&i.RequestText,
		&i.IsReviewAttempt,
		&i.ContextMoves,
		&i.MovedTurnID,
		&i.CreatedAt,
	)
	return i, err
}

const insertOwedReviewRequest = `-- name: InsertOwedReviewRequest :one

INSERT INTO owed_review_requests (session_id, requested_by, trigger, request_text, is_review_attempt, context_moves, moved_turn_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, session_id, requested_by, trigger, request_text, is_review_attempt, context_moves, moved_turn_id, created_at
`

type InsertOwedReviewRequestParams struct {
	SessionID       pgtype.UUID `json:"session_id"`
	RequestedBy     pgtype.UUID `json:"requested_by"`
	Trigger         string      `json:"trigger"`
	RequestText     *string     `json:"request_text"`
	IsReviewAttempt bool        `json:"is_review_attempt"`
	ContextMoves    int32       `json:"context_moves"`
	MovedTurnID     pgtype.UUID `json:"moved_turn_id"`
}

// Queries backing OwedReviewRequestStore: technical plan §24.9's owed
// human review requests (migrations/000160). A person's review attempt
// (the label, the web button, a mention) that waited behind another turn
// and found its pull request moved past the context it recorded ends
// context_moved, and its request becomes a row here, owed to its
// requester; the session actor's owed_review_request timer consumes the
// rows oldest first. Every statement is scoped to one session and served
// by owed_review_requests_session_id_idx (session_id, created_at), or by
// the primary key.
// The dispatching transaction that ends a person's review attempt
// context_moved owes its request (sessionactor's oweReviewRequest), in the
// same transaction as that end and the arm of the owed_review_request
// timer. created_at is the database's now: the instant a person's stop
// compares with.
func (q *Queries) InsertOwedReviewRequest(ctx context.Context, arg InsertOwedReviewRequestParams) (OwedReviewRequest, error) {
	row := q.db.QueryRow(ctx, insertOwedReviewRequest,
		arg.SessionID,
		arg.RequestedBy,
		arg.Trigger,
		arg.RequestText,
		arg.IsReviewAttempt,
		arg.ContextMoves,
		arg.MovedTurnID,
	)
	var i OwedReviewRequest
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RequestedBy,
		&i.Trigger,
		&i.RequestText,
		&i.IsReviewAttempt,
		&i.ContextMoves,
		&i.MovedTurnID,
		&i.CreatedAt,
	)
	return i, err
}
