// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releasemanifestchecks.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestReleaseManifestCheck = `-- name: GetLatestReleaseManifestCheck :one
SELECT id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at, composition_reviewed_at, composition_findings, composition_decision, composition_decision_by, composition_decision_at, composition_head_sha, composition_diff_truncated FROM release_manifest_checks
WHERE repo_full_name = $1 AND pr_number = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestReleaseManifestCheckParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// (repo_full_name, pr_number)'s own most-recently-computed check --
// mirrors GetLatestReviewVerdict's own identical "one indexed lookup,
// ORDER BY created_at DESC LIMIT 1" shape. pgx.ErrNoRows means no
// manifest check has ever been persisted for this PR (a row predating
// or a check whose own Run() insert failed and was only ever delivered as
// a comment).
func (q *Queries) GetLatestReleaseManifestCheck(ctx context.Context, arg GetLatestReleaseManifestCheckParams) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, getLatestReleaseManifestCheck, arg.RepoFullName, arg.PrNumber)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
		&i.CompositionReviewedAt,
		&i.CompositionFindings,
		&i.CompositionDecision,
		&i.CompositionDecisionBy,
		&i.CompositionDecisionAt,
		&i.CompositionHeadSha,
		&i.CompositionDiffTruncated,
	)
	return i, err
}

const getLatestReleaseManifestCheckBySessionID = `-- name: GetLatestReleaseManifestCheckBySessionID :one
SELECT id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at, composition_reviewed_at, composition_findings, composition_decision, composition_decision_by, composition_decision_at, composition_head_sha, composition_diff_truncated FROM release_manifest_checks
WHERE session_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// The session-scoped lookup: the composition-findings-posting
// tool and the Block/Acknowledge actions all resolve their target row
// from a sessionID alone (a sandbox-bearer-authenticated tool call, or an
// authenticated browser request against /api/sessions/:id/release-manifest/*),
// never from (repo_full_name, pr_number) -- mirrors GetLatestReleaseManifestCheck's
// own identical "ORDER BY created_at DESC LIMIT 1" shape, backed by
// release_manifest_checks_session_id_created_at_idx (migrations/
// 000127_release_manifest_checks_composition.up.sql). pgx.ErrNoRows means
// this session has no release manifest check on record at all.
func (q *Queries) GetLatestReleaseManifestCheckBySessionID(ctx context.Context, sessionID pgtype.UUID) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, getLatestReleaseManifestCheckBySessionID, sessionID)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
		&i.CompositionReviewedAt,
		&i.CompositionFindings,
		&i.CompositionDecision,
		&i.CompositionDecisionBy,
		&i.CompositionDecisionAt,
		&i.CompositionHeadSha,
		&i.CompositionDiffTruncated,
	)
	return i, err
}

const insertReleaseManifestCheck = `-- name: InsertReleaseManifestCheck :one

INSERT INTO release_manifest_checks (
    session_id, repo_full_name, pr_number, base_ref, head_ref,
    constituent_pr_count, coverage_partial,
    aggregate_review_triggered, aggregate_review_trigger_reasons,
    findings, merged_prs
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at, composition_reviewed_at, composition_findings, composition_decision, composition_decision_by, composition_decision_at, composition_head_sha, composition_diff_truncated
`

type InsertReleaseManifestCheckParams struct {
	SessionID                     pgtype.UUID `json:"session_id"`
	RepoFullName                  string      `json:"repo_full_name"`
	PrNumber                      int32       `json:"pr_number"`
	BaseRef                       string      `json:"base_ref"`
	HeadRef                       string      `json:"head_ref"`
	ConstituentPrCount            int32       `json:"constituent_pr_count"`
	CoveragePartial               bool        `json:"coverage_partial"`
	AggregateReviewTriggered      bool        `json:"aggregate_review_triggered"`
	AggregateReviewTriggerReasons []byte      `json:"aggregate_review_trigger_reasons"`
	Findings                      []byte      `json:"findings"`
	MergedPrs                     []byte      `json:"merged_prs"`
}

// Queries backing ReleaseManifestCheckStore (§12.2 item 9, §15.2/§15.3) -- see
// migrations/000097_release_manifest_checks.up.sql's own doc comment for
// the table's full design.
// The one write internal/app/releasereview.Run makes once it has computed
// this release PR's own manifest findings + aggregate-review trigger
// decision -- alongside, never instead of, its existing outbox-delivered
// comment (RenderManifestComment). Best-effort: a failure here is logged
// and Run simply continues to its own existing outbox enqueue, mirroring
// that function's own established "every internal failure is logged and
// this function simply returns" posture.
func (q *Queries) InsertReleaseManifestCheck(ctx context.Context, arg InsertReleaseManifestCheckParams) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, insertReleaseManifestCheck,
		arg.SessionID,
		arg.RepoFullName,
		arg.PrNumber,
		arg.BaseRef,
		arg.HeadRef,
		arg.ConstituentPrCount,
		arg.CoveragePartial,
		arg.AggregateReviewTriggered,
		arg.AggregateReviewTriggerReasons,
		arg.Findings,
		arg.MergedPrs,
	)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
		&i.CompositionReviewedAt,
		&i.CompositionFindings,
		&i.CompositionDecision,
		&i.CompositionDecisionBy,
		&i.CompositionDecisionAt,
		&i.CompositionHeadSha,
		&i.CompositionDiffTruncated,
	)
	return i, err
}

const updateReleaseManifestCompositionAnchor = `-- name: UpdateReleaseManifestCompositionAnchor :one
UPDATE release_manifest_checks
SET composition_head_sha = $2,
    composition_diff_truncated = $3
WHERE id = $1 AND composition_head_sha IS NULL
RETURNING id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at, composition_reviewed_at, composition_findings, composition_decision, composition_decision_by, composition_decision_at, composition_head_sha, composition_diff_truncated
`

type UpdateReleaseManifestCompositionAnchorParams struct {
	ID                       pgtype.UUID `json:"id"`
	CompositionHeadSha       *string     `json:"composition_head_sha"`
	CompositionDiffTruncated *bool       `json:"composition_diff_truncated"`
}

// Confirmed-major fix (migrations/000128_release_manifest_checks_
// composition_anchor.up.sql): internal/app/releasereview.
// dispatchCompositionReview's own write, immediately after it creates
// this release's own composition review turn -- records WHICH commit
// (headSHA, the SAME value just persisted as that turn's own
// turns.review_head_sha) and whether that turn's own diff fetch was
// itself truncated, so a later-posted composition finding is anchored to
// an identifiable diff rather than an untraceable one. Guarded
// ("AND composition_head_sha IS NULL") so a duplicate/retried dispatch for
// the SAME row can never silently overwrite an already-recorded anchor
// with a different one; pgx.ErrNoRows means an anchor was already
// recorded, harmless and expected for that case (best-effort, logged, not
// propagated -- see the Go call site's own doc comment).
func (q *Queries) UpdateReleaseManifestCompositionAnchor(ctx context.Context, arg UpdateReleaseManifestCompositionAnchorParams) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, updateReleaseManifestCompositionAnchor, arg.ID, arg.CompositionHeadSha, arg.CompositionDiffTruncated)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
		&i.CompositionReviewedAt,
		&i.CompositionFindings,
		&i.CompositionDecision,
		&i.CompositionDecisionBy,
		&i.CompositionDecisionAt,
		&i.CompositionHeadSha,
		&i.CompositionDiffTruncated,
	)
	return i, err
}

const updateReleaseManifestCompositionDecision = `-- name: UpdateReleaseManifestCompositionDecision :one
UPDATE release_manifest_checks
SET composition_decision = $2,
    composition_decision_by = $3,
    composition_decision_at = now()
WHERE id = $1 AND composition_decision = $4
RETURNING id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at, composition_reviewed_at, composition_findings, composition_decision, composition_decision_by, composition_decision_at, composition_head_sha, composition_diff_truncated
`

type UpdateReleaseManifestCompositionDecisionParams struct {
	ID                    pgtype.UUID `json:"id"`
	CompositionDecision   string      `json:"composition_decision"`
	CompositionDecisionBy pgtype.UUID `json:"composition_decision_by"`
	ExpectedDecision      string      `json:"expected_decision"`
}

// The Block release / Acknowledge & ship action write
// (BlockReleaseComposition/AcknowledgeReleaseComposition, httpapi/
// releasecompositiondecision.go): a guarded UPDATE comparing against
// expectedCurrentDecision (the SAME current value the caller already
// passed through internal/domain/review.TransitionCompositionDecision to
// validate) -- pgx.ErrNoRows means a concurrent decision already won the
// race between that validation and this write, reported back to the
// caller as 409, never a silent overwrite of someone else's decision.
func (q *Queries) UpdateReleaseManifestCompositionDecision(ctx context.Context, arg UpdateReleaseManifestCompositionDecisionParams) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, updateReleaseManifestCompositionDecision,
		arg.ID,
		arg.CompositionDecision,
		arg.CompositionDecisionBy,
		arg.ExpectedDecision,
	)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
		&i.CompositionReviewedAt,
		&i.CompositionFindings,
		&i.CompositionDecision,
		&i.CompositionDecisionBy,
		&i.CompositionDecisionAt,
		&i.CompositionHeadSha,
		&i.CompositionDiffTruncated,
	)
	return i, err
}

const updateReleaseManifestCompositionFindings = `-- name: UpdateReleaseManifestCompositionFindings :one
UPDATE release_manifest_checks
SET composition_reviewed_at = now(),
    composition_findings = $2
WHERE id = $1 AND composition_reviewed_at IS NULL
RETURNING id, session_id, repo_full_name, pr_number, base_ref, head_ref, constituent_pr_count, coverage_partial, aggregate_review_triggered, aggregate_review_trigger_reasons, findings, merged_prs, created_at, composition_reviewed_at, composition_findings, composition_decision, composition_decision_by, composition_decision_at, composition_head_sha, composition_diff_truncated
`

type UpdateReleaseManifestCompositionFindingsParams struct {
	ID                  pgtype.UUID `json:"id"`
	CompositionFindings []byte      `json:"composition_findings"`
}

// The composition-findings-posting tool write
// (PostReleaseCompositionFindings, httpapi/releasecompositionfindings.go):
// a guarded UPDATE ("AND composition_reviewed_at IS NULL") so this can
// only ever succeed ONCE per row -- a retried/duplicate tool call for the
// same session is a no-op here (pgx.ErrNoRows), never a silent
// overwrite of an already-posted result. Scoped by id (the caller already
// resolved the target row via GetLatestReleaseManifestCheckBySessionID,
// and passes its own id back here) rather than session_id directly, so a
// future Step that DOES re-run this check on a later push (this table's
// own append-only design, migrations/000097's doc comment) can never have
// this guarded write silently target the WRONG one of several rows
// sharing a session_id.
func (q *Queries) UpdateReleaseManifestCompositionFindings(ctx context.Context, arg UpdateReleaseManifestCompositionFindingsParams) (ReleaseManifestCheck, error) {
	row := q.db.QueryRow(ctx, updateReleaseManifestCompositionFindings, arg.ID, arg.CompositionFindings)
	var i ReleaseManifestCheck
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.ConstituentPrCount,
		&i.CoveragePartial,
		&i.AggregateReviewTriggered,
		&i.AggregateReviewTriggerReasons,
		&i.Findings,
		&i.MergedPrs,
		&i.CreatedAt,
		&i.CompositionReviewedAt,
		&i.CompositionFindings,
		&i.CompositionDecision,
		&i.CompositionDecisionBy,
		&i.CompositionDecisionAt,
		&i.CompositionHeadSha,
		&i.CompositionDiffTruncated,
	)
	return i, err
}
