// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releasemanifestpending.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueReleaseManifestPending = `-- name: ClaimDueReleaseManifestPending :many
UPDATE release_manifest_pending
SET claimed_at = now()
WHERE id IN (
    SELECT id FROM release_manifest_pending
    WHERE claimed_at IS NULL
    ORDER BY created_at
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, session_id, owner, repo, pr_number, base_ref, head_ref, correlation_id, created_at, claimed_at
`

// internal/app/releasereview.Worker's own poll query: atomically claims
// up to $1 not-yet-claimed rows, oldest-first, by stamping claimed_at with
// the database's now() in the SAME statement a SELECT ... FOR UPDATE SKIP
// LOCKED subquery identifies -- a single round trip, no separate explicit
// transaction required. Claiming a row this way IS this table's one and
// only "attempt" -- a claimed row is never selected again, so there is no
// revisit, no retry, no backoff (see the table's own doc comment for why
// releasereview.Run itself has no failure signal to record one against).
// The row stays, claimed, while its check runs -- the session's status
// reads it as work that can still create a turn (technical plan §43.20,
// migrations/000147) -- and the worker deletes it once the check returns
// (FinishReleaseManifestPending). FOR UPDATE SKIP LOCKED is what lets two
// concurrent pods' own Worker.PumpOnce calls each claim a DISJOINT row
// instead of blocking on (or double-claiming) the same one -- mirrors
// ListDuePendingOutboxEntries' own identical multi-pod reasoning
// (queries/outbox.sql).
func (q *Queries) ClaimDueReleaseManifestPending(ctx context.Context, limit int32) ([]ReleaseManifestPending, error) {
	rows, err := q.db.Query(ctx, claimDueReleaseManifestPending, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseManifestPending
	for rows.Next() {
		var i ReleaseManifestPending
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Owner,
			&i.Repo,
			&i.PrNumber,
			&i.BaseRef,
			&i.HeadRef,
			&i.CorrelationID,
			&i.CreatedAt,
			&i.ClaimedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createReleaseManifestPending = `-- name: CreateReleaseManifestPending :one

INSERT INTO release_manifest_pending (session_id, owner, repo, pr_number, base_ref, head_ref, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, session_id, owner, repo, pr_number, base_ref, head_ref, correlation_id, created_at, claimed_at
`

type CreateReleaseManifestPendingParams struct {
	SessionID     pgtype.UUID `json:"session_id"`
	Owner         string      `json:"owner"`
	Repo          string      `json:"repo"`
	PrNumber      int32       `json:"pr_number"`
	BaseRef       string      `json:"base_ref"`
	HeadRef       string      `json:"head_ref"`
	CorrelationID *string     `json:"correlation_id"`
}

// Queries backing internal/adapters/outbound/postgres.
// ReleaseManifestPendingStore (blocking-finding fix #1, "release PR
// review", §15.2) -- see migrations/000050_release_manifest_pending.up.sql's
// own doc comment for the table's full design and the "why" behind this
// fix.
// Written by internal/adapters/inbound/github's own webhook handler,
// inline, immediately before its own fast ack -- deliberately as cheap as
// a single INSERT (see the table's own doc comment for why the ACTUAL
// check work never runs on this same request path).
func (q *Queries) CreateReleaseManifestPending(ctx context.Context, arg CreateReleaseManifestPendingParams) (ReleaseManifestPending, error) {
	row := q.db.QueryRow(ctx, createReleaseManifestPending,
		arg.SessionID,
		arg.Owner,
		arg.Repo,
		arg.PrNumber,
		arg.BaseRef,
		arg.HeadRef,
		arg.CorrelationID,
	)
	var i ReleaseManifestPending
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Owner,
		&i.Repo,
		&i.PrNumber,
		&i.BaseRef,
		&i.HeadRef,
		&i.CorrelationID,
		&i.CreatedAt,
		&i.ClaimedAt,
	)
	return i, err
}

const finishReleaseManifestPending = `-- name: FinishReleaseManifestPending :exec
DELETE FROM release_manifest_pending WHERE id = $1
`

// The worker's own last step for one claimed row: its check has returned,
// and any composition review turn it inserted has already committed, so
// the row -- which the session's status reads as work still able to
// create a turn -- goes now. A session whose status no longer counts this
// row therefore already counts that turn.
func (q *Queries) FinishReleaseManifestPending(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, finishReleaseManifestPending, id)
	return err
}

const purgeStaleClaimedReleaseManifestPending = `-- name: PurgeStaleClaimedReleaseManifestPending :execrows
DELETE FROM release_manifest_pending
WHERE claimed_at < now() - $1::interval
`

// Deletes rows claimed longer ago than max_age: their one attempt is over
// -- ReleaseManifestCheckTimeout bounds it -- but their worker died before
// FinishReleaseManifestPending ran. The session's status has already
// stopped counting such a row (the same bound, measured on the same
// database clock); this keeps them from piling up. Never touches an
// unclaimed row.
func (q *Queries) PurgeStaleClaimedReleaseManifestPending(ctx context.Context, maxAge pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, purgeStaleClaimedReleaseManifestPending, maxAge)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
