// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reposettings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDemotionSweepPending = `-- name: ClearDemotionSweepPending :execrows
UPDATE repo_settings
SET demotion_sweep_pending_at = NULL, updated_at = now()
WHERE repo_full_name = $1 AND demotion_sweep_pending_at IS NOT NULL
`

// Clears the obligation, and ONLY after a sweep completed without error.
// Guarded on the column still being set so a concurrent second sweeper
// clearing it first is a no-op here rather than a lost update.
func (q *Queries) ClearDemotionSweepPending(ctx context.Context, repoFullName string) (int64, error) {
	result, err := q.db.Exec(ctx, clearDemotionSweepPending, repoFullName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSuppressedRepos = `-- name: CountSuppressedRepos :one
SELECT COUNT(*) FROM repo_settings WHERE live_egress_enabled = false
`

// How many repositories this deployment will suppress outgoing effects for
// (§30.8). Read once at boot so an operator is TOLD, rather than finding
// out because a customer stopped receiving notifications.
//
// Counts rows explicitly not promoted. It cannot count repositories with
// no settings row at all, which also resolve to shadow -- there is no
// table of "repositories this deployment knows about" to count against.
// The number is therefore a floor, and the boot message says so rather
// than presenting it as a total.
func (q *Queries) CountSuppressedRepos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppressedRepos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRepoSettings = `-- name: GetRepoSettings :one

SELECT repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd FROM repo_settings WHERE repo_full_name = $1
`

// Queries backing RepoSettingsStore (§8.2, §21.2): a small,
// extensible table of admin-configured, per-repo policy flags -- see
// migrations/000044_repo_settings.up.sql's own doc comment for the full
// "one shared table, not one bespoke table per toggle" design rationale.
// A missing row (pgx.ErrNoRows) means every flag defaults to its own safe
// value -- callers must NOT treat that as an error, see this table's own
// migration doc comment.
func (q *Queries) GetRepoSettings(ctx context.Context, repoFullName string) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, getRepoSettings, repoFullName)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const listAutoMergeEnabledRepos = `-- name: ListAutoMergeEnabledRepos :many
SELECT repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd FROM repo_settings WHERE auto_merge_enabled = true
`

// internal/app/automerge's own per-tick repo enumeration (§21.2 stage
// 2): every repo an admin has armed -- mirrors this table's own
// established "repo_settings is the one shared home for admin-configured
// per-repo policy" precedent; there is no separate registry of "every
// repo Narvi manages" anywhere in this codebase (internal/adapters/
// outbound/githubapi/listopenprs.go's own doc comment names this same
// gap), so a repo with auto_merge_enabled = true is, by construction,
// already a repo this deployment has touched.
func (q *Queries) ListAutoMergeEnabledRepos(ctx context.Context) ([]RepoSetting, error) {
	rows, err := q.db.Query(ctx, listAutoMergeEnabledRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoSetting
	for rows.Next() {
		var i RepoSetting
		if err := rows.Scan(
			&i.RepoFullName,
			&i.BlockOnHighRisk,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentinelAutofixEnabled,
			&i.RwxPreviewDispatchKey,
			&i.RwxPreviewEndpointTemplate,
			&i.RwxPreviewOrgSlug,
			&i.AutoMergeEnabled,
			&i.MaxAutoApproveFilesChanged,
			&i.SensitiveBlastRadiusTags,
			&i.AutoRetriggerReviewEnabled,
			&i.DescriptionAutofixEnabled,
			&i.ReviewDepthMode,
			&i.ReviewDepthDeepPaths,
			&i.ReviewCostBudgetLightUsd,
			&i.ReviewCostBudgetDeepUsd,
			&i.SessionsEnabled,
			&i.LiveEgressEnabled,
			&i.LiveEgressPromotedAt,
			&i.DemotionSweepPendingAt,
			&i.SessionSpendCapUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposOwedDemotionSweep = `-- name: ListReposOwedDemotionSweep :many
SELECT repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd FROM repo_settings
WHERE demotion_sweep_pending_at IS NOT NULL
ORDER BY demotion_sweep_pending_at
LIMIT $1
`

// internal/app/reconciler's own demotion-sweep retry: every repo whose
// demotion stamped an obligation that no sweep has yet cleared. Empty on
// an ordinary deployment -- see the partial index this rides.
func (q *Queries) ListReposOwedDemotionSweep(ctx context.Context, limit int32) ([]RepoSetting, error) {
	rows, err := q.db.Query(ctx, listReposOwedDemotionSweep, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoSetting
	for rows.Next() {
		var i RepoSetting
		if err := rows.Scan(
			&i.RepoFullName,
			&i.BlockOnHighRisk,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentinelAutofixEnabled,
			&i.RwxPreviewDispatchKey,
			&i.RwxPreviewEndpointTemplate,
			&i.RwxPreviewOrgSlug,
			&i.AutoMergeEnabled,
			&i.MaxAutoApproveFilesChanged,
			&i.SensitiveBlastRadiusTags,
			&i.AutoRetriggerReviewEnabled,
			&i.DescriptionAutofixEnabled,
			&i.ReviewDepthMode,
			&i.ReviewDepthDeepPaths,
			&i.ReviewCostBudgetLightUsd,
			&i.ReviewCostBudgetDeepUsd,
			&i.SessionsEnabled,
			&i.LiveEgressEnabled,
			&i.LiveEgressPromotedAt,
			&i.DemotionSweepPendingAt,
			&i.SessionSpendCapUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAutoApprovalEligibility = `-- name: UpsertAutoApprovalEligibility :one
INSERT INTO repo_settings (repo_full_name, max_auto_approve_files_changed, sensitive_blast_radius_tags, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET max_auto_approve_files_changed = EXCLUDED.max_auto_approve_files_changed, sensitive_blast_radius_tags = EXCLUDED.sensitive_blast_radius_tags, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertAutoApprovalEligibilityParams struct {
	RepoFullName               string `json:"repo_full_name"`
	MaxAutoApproveFilesChanged *int32 `json:"max_auto_approve_files_changed"`
	SensitiveBlastRadiusTags   []byte `json:"sensitive_blast_radius_tags"`
}

// Idempotent create-or-update of ONLY
// max_auto_approve_files_changed/sensitive_blast_radius_tags -- the
// column-scoped sibling of UpsertAutoMergeToggle immediately above (see
// that query's own doc comment for the full "why"). auto_merge_enabled
// is left COMPLETELY untouched by this query -- its own column DEFAULT
// (false) when this creates a brand-new row, or whatever a PRIOR
// UpsertAutoMergeToggle call already set, on an update.
func (q *Queries) UpsertAutoApprovalEligibility(ctx context.Context, arg UpsertAutoApprovalEligibilityParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertAutoApprovalEligibility, arg.RepoFullName, arg.MaxAutoApproveFilesChanged, arg.SensitiveBlastRadiusTags)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertAutoMergeToggle = `-- name: UpsertAutoMergeToggle :one

INSERT INTO repo_settings (repo_full_name, auto_merge_enabled, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET auto_merge_enabled = EXCLUDED.auto_merge_enabled, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertAutoMergeToggleParams struct {
	RepoFullName     string `json:"repo_full_name"`
	AutoMergeEnabled bool   `json:"auto_merge_enabled"`
}

// UpsertAutoApprovalSettings (§21.2) is REMOVED (an adversarial-review
// fix, MEDIUM but a privilege boundary) -- it wrote
// all three auto-approval/auto-merge columns together, even though the
// TWO REST endpoints that ever called it (PutAutoApprovalSettings,
// gated by ActionConfigureAutoApprove; PutAutoMergeToggle, admin-only
// ActionToggleAutoMerge -- httpapi/reposettings.go) are separately
// gated and each owns a DIFFERENT subset of these columns. Both
// handlers worked around this via an app-layer read-modify-write (read
// the OTHER endpoint's own columns first, pass them straight through
// unchanged) -- but that read-modify-write is exactly the kind of race
// this fix closes: a maintainer's PutAutoApprovalSettings write and an
// admin's PutAutoMergeToggle write, landing concurrently, could each
// read the OTHER's stale pre-write value and silently clobber it on
// write-back, including reverting a toggle an admin just armed/
// disarmed. Replaced by the two column-scoped upserts below --
// UpsertAutoMergeToggle/UpsertAutoApprovalEligibility -- each touching
// ONLY the columns its own one caller owns, so two concurrent writers
// touching DIFFERENT columns can no longer race at the DATABASE level,
// closing the hazard by construction rather than by an app-layer
// read-then-preserve convention a future edit could easily forget.
// Idempotent create-or-update of ONLY
// auto_merge_enabled (migrations/000069_repo_settings_auto_approval.up.sql)
// -- mirrors UpsertRWXPreviewSettings' own identical "touches ONLY these
// columns, ON CONFLICT leaves every other column untouched" shape.
// max_auto_approve_files_changed/sensitive_blast_radius_tags are left
// COMPLETELY untouched by this query -- their own column DEFAULT (NULL)
// when this creates a brand-new row, or whatever a PRIOR
// UpsertAutoApprovalEligibility call already set, on an update.
func (q *Queries) UpsertAutoMergeToggle(ctx context.Context, arg UpsertAutoMergeToggleParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertAutoMergeToggle, arg.RepoFullName, arg.AutoMergeEnabled)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertAutoRetriggerReviewToggle = `-- name: UpsertAutoRetriggerReviewToggle :one
INSERT INTO repo_settings (repo_full_name, auto_retrigger_review_enabled, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET auto_retrigger_review_enabled = EXCLUDED.auto_retrigger_review_enabled, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertAutoRetriggerReviewToggleParams struct {
	RepoFullName               string `json:"repo_full_name"`
	AutoRetriggerReviewEnabled bool   `json:"auto_retrigger_review_enabled"`
}

// §24's own admin-only, per-repo opt-in (§24.5, migrations/
// 000076_repo_settings_auto_retrigger_review.up.sql) -- idempotent
// create-or-update of ONLY auto_retrigger_review_enabled, mirroring
// UpsertAutoMergeToggle's own identical column-scoped shape immediately
// above (the same
// independently-gated-toggle pattern): every other repo_settings column is left
// COMPLETELY untouched, so a concurrent write to any of them (an admin's
// PutRepoSettings, PutAutoMergeToggle, or PutAutoApprovalSettings call)
// can never race with this one at the database level.
func (q *Queries) UpsertAutoRetriggerReviewToggle(ctx context.Context, arg UpsertAutoRetriggerReviewToggleParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertAutoRetriggerReviewToggle, arg.RepoFullName, arg.AutoRetriggerReviewEnabled)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertDescriptionAutofixToggle = `-- name: UpsertDescriptionAutofixToggle :one
INSERT INTO repo_settings (repo_full_name, description_autofix_enabled, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET description_autofix_enabled = EXCLUDED.description_autofix_enabled, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertDescriptionAutofixToggleParams struct {
	RepoFullName              string `json:"repo_full_name"`
	DescriptionAutofixEnabled bool   `json:"description_autofix_enabled"`
}

// §26.2's own admin-only, per-repo opt-in (§26.2, migrations/
// 000079_repo_settings_description_autofix.up.sql) -- idempotent
// create-or-update of ONLY description_autofix_enabled, mirroring
// UpsertAutoMergeToggle/UpsertAutoRetriggerReviewToggle's own identical
// column-scoped shape above (the same independently-gated-toggle
// pattern): every other repo_settings
// column is left COMPLETELY untouched, so a concurrent write to any of
// them can never race with this one at the database level.
func (q *Queries) UpsertDescriptionAutofixToggle(ctx context.Context, arg UpsertDescriptionAutofixToggleParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertDescriptionAutofixToggle, arg.RepoFullName, arg.DescriptionAutofixEnabled)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertLiveEgressEnabled = `-- name: UpsertLiveEgressEnabled :one
INSERT INTO repo_settings (repo_full_name, live_egress_enabled, live_egress_promoted_at, updated_at)
VALUES ($1, $2, CASE WHEN $2 THEN now() ELSE NULL END, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET
    live_egress_enabled = EXCLUDED.live_egress_enabled,
    live_egress_promoted_at = CASE
        WHEN NOT EXCLUDED.live_egress_enabled THEN NULL
        WHEN EXCLUDED.live_egress_enabled AND NOT repo_settings.live_egress_enabled THEN now()
        ELSE repo_settings.live_egress_promoted_at
    END,
    demotion_sweep_pending_at = CASE
        WHEN repo_settings.live_egress_enabled AND NOT EXCLUDED.live_egress_enabled THEN now()
        ELSE repo_settings.demotion_sweep_pending_at
    END,
    updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertLiveEgressEnabledParams struct {
	RepoFullName      string `json:"repo_full_name"`
	LiveEgressEnabled bool   `json:"live_egress_enabled"`
}

// §30.8's own per-repo egress-mode authority (migrations/
// 000101_repo_settings_live_egress_enabled.up.sql) -- idempotent
// create-or-update of ONLY live_egress_enabled, mirroring
// UpsertSessionsEnabled's own identical column-scoped shape immediately
// above (the same independently-gated-toggle pattern): every other
// repo_settings column is left COMPLETELY untouched, so a concurrent
// write to any of them can never race with this one at the database
// level. Written ONLY by the seed tool in v1 (internal/app/seed/
// reposettings.go), which can flip it either way, and by internal/app/
// shadowoperator.Activate (an admin-only REST route), which only ever
// promotes.
//
// The demotionsweep analyzer constrains WHICH PACKAGES may call this, not
// which direction they call it in -- it bans the name. What keeps
// shadowoperator to promotion is that package's own meta-test, asserting
// the literal true at its single call site; and what makes seed safe in
// the other direction is that it pairs a demotion with repodemotion.Sweep
// itself. Stated precisely because an earlier version of this comment
// claimed the analyzer enforced the direction, which would leave a reader
// trusting a guarantee nothing provides. See that file's own
// doc comment for why, and for how this write is journaled to audit_log.
//
// live_egress_promoted_at (migrations/
// 000104_repo_settings_live_egress_promoted_at.up.sql) moves WITH
// live_egress_enabled, but not identically -- it is §30.8's own
// promotion fence, and only a genuine false->true TRANSITION is a
// promotion:
//   - false -> true (a genuine promotion, including the first-ever
//     write for a repo that starts true): stamped to now(), a fresh
//     fence for this promotion.
//   - true -> true (re-affirming an already-live repo, e.g. a seed
//     re-run): left UNCHANGED -- re-running the same promotion must
//     never slide the fence forward and silently exclude verdicts that
//     were already valid candidates under the earlier promotion.
//   - anything -> false (a demotion, or a fresh row starting shadow):
//     cleared to NULL. A demoted repo's fence must not survive to a
//     later re-promotion -- §30.8's own "suppress wins both ways"
//     applies here too: only verdicts after the MOST RECENT promotion
//     are ever candidates, never a stale fence from a promotion this
//     repo has since walked back.
//
// demotion_sweep_pending_at (migrations/
// 000109_repo_settings_demotion_sweep_pending.up.sql) is stamped by THIS
// statement, on a genuine true->false transition only, so §30.4's own
// mandatory sandbox termination survives the commit that used to consume
// the evidence it was owed. It is never stamped by a fresh INSERT: a repo
// whose first-ever write is false has never been live, so no sandbox of
// it ever held more than read-only, and nothing is owed.
func (q *Queries) UpsertLiveEgressEnabled(ctx context.Context, arg UpsertLiveEgressEnabledParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertLiveEgressEnabled, arg.RepoFullName, arg.LiveEgressEnabled)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertPreviewConfig = `-- name: UpsertPreviewConfig :one
INSERT INTO repo_settings (repo_full_name, rwx_preview_endpoint_template, rwx_preview_org_slug, rwx_preview_dispatch_key, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET
    rwx_preview_endpoint_template = EXCLUDED.rwx_preview_endpoint_template,
    rwx_preview_org_slug = EXCLUDED.rwx_preview_org_slug,
    rwx_preview_dispatch_key = CASE WHEN $5::boolean THEN $4 ELSE repo_settings.rwx_preview_dispatch_key END,
    updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertPreviewConfigParams struct {
	RepoFullName               string  `json:"repo_full_name"`
	RwxPreviewEndpointTemplate *string `json:"rwx_preview_endpoint_template"`
	RwxPreviewOrgSlug          *string `json:"rwx_preview_org_slug"`
	DispatchKey                *string `json:"dispatch_key"`
	DispatchKeyProvided        bool    `json:"dispatch_key_provided"`
}

// §4.1.2 amendment ("PR preview links ... exposure amendment"): backs
// the NEW admin-facing PUT /api/repos/{owner}/{repo}/preview-config
// (httpapi/previewconfig.go), which UNLIKE UpsertRWXPreviewSettings
// immediately above gives rwx_preview_dispatch_key its OWN partial-write
// semantics -- "absent means unchanged" (§4.1.2 amendment's own words),
// the one place on this surface partial-state semantics are correct
// rather than a patch in disguise, since dispatchKey is write-only (never
// read back by any response, PreviewConfig.maskedDispatchKey) and a
// caller therefore cannot resend a value it was never given.
//
// sqlc.arg('dispatch_key_provided') is the caller's own "was dispatchKey
// present in the request body at all" bit (httpapi/previewconfig.go:
// req.DispatchKey != nil): false leaves rwx_preview_dispatch_key
// completely untouched -- its own CURRENT value on an existing row, or
// its column DEFAULT (NULL) on a brand-new one, where "unchanged" and
// "still absent" already coincide. true writes sqlc.narg('dispatch_key')
// verbatim, which is itself nullable: an explicit empty string clears the
// key (stored as NULL, mirroring this column's own established "NULL
// means off" convention, migrations/000059's own doc comment: "absent =
// off by default"), a non-empty string rotates it.
//
// rwx_preview_endpoint_template/rwx_preview_org_slug are ALWAYS written
// to EXCLUDED's value -- ordinary, full-value semantics (§4.1.2
// amendment: "ordinary identifiers ... read and write normally"), no
// partial-write bit for either, unlike dispatch_key.
func (q *Queries) UpsertPreviewConfig(ctx context.Context, arg UpsertPreviewConfigParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertPreviewConfig,
		arg.RepoFullName,
		arg.RwxPreviewEndpointTemplate,
		arg.RwxPreviewOrgSlug,
		arg.DispatchKey,
		arg.DispatchKeyProvided,
	)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertRWXPreviewSettings = `-- name: UpsertRWXPreviewSettings :one
INSERT INTO repo_settings (repo_full_name, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET rwx_preview_dispatch_key = EXCLUDED.rwx_preview_dispatch_key, rwx_preview_endpoint_template = EXCLUDED.rwx_preview_endpoint_template, rwx_preview_org_slug = EXCLUDED.rwx_preview_org_slug, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertRWXPreviewSettingsParams struct {
	RepoFullName               string  `json:"repo_full_name"`
	RwxPreviewDispatchKey      *string `json:"rwx_preview_dispatch_key"`
	RwxPreviewEndpointTemplate *string `json:"rwx_preview_endpoint_template"`
	RwxPreviewOrgSlug          *string `json:"rwx_preview_org_slug"`
}

// §4.1 ("RWX provider + previews", §4.1.2 point 1): idempotent
// create-or-update of ONLY the three RWX-preview columns (migrations/
// 000059_repo_settings_rwx_preview.up.sql), keyed on repo_full_name --
// deliberately independent of UpsertRepoSettings above: block_on_high_risk/
// sentinel_autofix_enabled are the review domain's own admin-only
// booleans; RWX previews are a separately-toggled setting with a
// different shape entirely. This upsert touches ONLY these three columns
// -- ON CONFLICT leaves whatever the other two already hold (their own
// DEFAULT false when this creates a brand-new row) completely untouched.
func (q *Queries) UpsertRWXPreviewSettings(ctx context.Context, arg UpsertRWXPreviewSettingsParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertRWXPreviewSettings,
		arg.RepoFullName,
		arg.RwxPreviewDispatchKey,
		arg.RwxPreviewEndpointTemplate,
		arg.RwxPreviewOrgSlug,
	)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertRepoSettings = `-- name: UpsertRepoSettings :one
INSERT INTO repo_settings (repo_full_name, block_on_high_risk, sentinel_autofix_enabled, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET block_on_high_risk = EXCLUDED.block_on_high_risk, sentinel_autofix_enabled = EXCLUDED.sentinel_autofix_enabled, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertRepoSettingsParams struct {
	RepoFullName           string `json:"repo_full_name"`
	BlockOnHighRisk        bool   `json:"block_on_high_risk"`
	SentinelAutofixEnabled bool   `json:"sentinel_autofix_enabled"`
}

// Idempotent create-or-update, keyed on repo_full_name -- an admin
// (re)setting block_on_high_risk/sentinel_autofix_enabled always writes
// the full, current desired value rather than patching a delta, so a
// concurrent double-submit from the same admin settles on whichever write
// lands last, never a non-deterministic partial merge. sentinel_autofix_
// enabled (§17.1) is this SAME table's own further admin-only,
// per-repo boolean, exactly as migrations/000044's own doc comment
// anticipated -- see migrations/000048_repo_settings_sentinel_autofix.up.sql.
func (q *Queries) UpsertRepoSettings(ctx context.Context, arg UpsertRepoSettingsParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertRepoSettings, arg.RepoFullName, arg.BlockOnHighRisk, arg.SentinelAutofixEnabled)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertReviewCostBudget = `-- name: UpsertReviewCostBudget :one
INSERT INTO repo_settings (repo_full_name, review_cost_budget_light_usd, review_cost_budget_deep_usd, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET review_cost_budget_light_usd = EXCLUDED.review_cost_budget_light_usd, review_cost_budget_deep_usd = EXCLUDED.review_cost_budget_deep_usd, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertReviewCostBudgetParams struct {
	RepoFullName             string         `json:"repo_full_name"`
	ReviewCostBudgetLightUsd pgtype.Numeric `json:"review_cost_budget_light_usd"`
	ReviewCostBudgetDeepUsd  pgtype.Numeric `json:"review_cost_budget_deep_usd"`
}

// §26.4's own admin-only, per-repo reviewCostBudget config (§26.7,
// migrations/000085_repo_settings_review_cost_budget.up.sql) -- idempotent
// create-or-update of ONLY review_cost_budget_light_usd/
// review_cost_budget_deep_usd, mirroring UpsertReviewDepthConfig's own
// identical column-scoped shape immediately above (the same
// independently-gated-config pattern): every other repo_settings column
// is left COMPLETELY untouched, so a
// concurrent write to any of them can never race with this one at the
// database level.
func (q *Queries) UpsertReviewCostBudget(ctx context.Context, arg UpsertReviewCostBudgetParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertReviewCostBudget, arg.RepoFullName, arg.ReviewCostBudgetLightUsd, arg.ReviewCostBudgetDeepUsd)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertReviewDepthConfig = `-- name: UpsertReviewDepthConfig :one
INSERT INTO repo_settings (repo_full_name, review_depth_mode, review_depth_deep_paths, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET review_depth_mode = EXCLUDED.review_depth_mode, review_depth_deep_paths = EXCLUDED.review_depth_deep_paths, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertReviewDepthConfigParams struct {
	RepoFullName         string  `json:"repo_full_name"`
	ReviewDepthMode      *string `json:"review_depth_mode"`
	ReviewDepthDeepPaths []byte  `json:"review_depth_deep_paths"`
}

// §26.3's own admin-only, per-repo reviewDepth config (§26.3,
// migrations/000082_repo_settings_review_depth.up.sql) -- idempotent
// create-or-update of ONLY review_depth_mode/review_depth_deep_paths,
// mirroring UpsertAutoMergeToggle/UpsertAutoRetriggerReviewToggle/
// UpsertDescriptionAutofixToggle's own identical column-scoped shape
// above (the same independently-gated-config pattern): every other
// repo_settings column is left
// COMPLETELY untouched, so a concurrent write to any of them can never
// race with this one at the database level.
func (q *Queries) UpsertReviewDepthConfig(ctx context.Context, arg UpsertReviewDepthConfigParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertReviewDepthConfig, arg.RepoFullName, arg.ReviewDepthMode, arg.ReviewDepthDeepPaths)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}

const upsertSessionsEnabled = `-- name: UpsertSessionsEnabled :one
INSERT INTO repo_settings (repo_full_name, sessions_enabled, updated_at)
VALUES ($1, $2, now())
ON CONFLICT (repo_full_name)
DO UPDATE SET sessions_enabled = EXCLUDED.sessions_enabled, updated_at = now()
RETURNING repo_full_name, block_on_high_risk, created_at, updated_at, sentinel_autofix_enabled, rwx_preview_dispatch_key, rwx_preview_endpoint_template, rwx_preview_org_slug, auto_merge_enabled, max_auto_approve_files_changed, sensitive_blast_radius_tags, auto_retrigger_review_enabled, description_autofix_enabled, review_depth_mode, review_depth_deep_paths, review_cost_budget_light_usd, review_cost_budget_deep_usd, sessions_enabled, live_egress_enabled, live_egress_promoted_at, demotion_sweep_pending_at, session_spend_cap_usd
`

type UpsertSessionsEnabledParams struct {
	RepoFullName    string `json:"repo_full_name"`
	SessionsEnabled bool   `json:"sessions_enabled"`
}

// §10's own cohort-rollout enrollment gate (§10 Phase 6, §32) --
// idempotent create-or-update of ONLY sessions_enabled, mirroring
// UpsertAutoMergeToggle/UpsertAutoRetriggerReviewToggle/
// UpsertDescriptionAutofixToggle's own identical column-scoped shape
// above (the same
// independently-gated-toggle pattern): every other repo_settings column is left
// COMPLETELY untouched, so a concurrent write to any of them can never
// race with this one at the database level. Written ONLY by the seed
// tool in v1 (§32: "seed-manifest-only").
func (q *Queries) UpsertSessionsEnabled(ctx context.Context, arg UpsertSessionsEnabledParams) (RepoSetting, error) {
	row := q.db.QueryRow(ctx, upsertSessionsEnabled, arg.RepoFullName, arg.SessionsEnabled)
	var i RepoSetting
	err := row.Scan(
		&i.RepoFullName,
		&i.BlockOnHighRisk,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentinelAutofixEnabled,
		&i.RwxPreviewDispatchKey,
		&i.RwxPreviewEndpointTemplate,
		&i.RwxPreviewOrgSlug,
		&i.AutoMergeEnabled,
		&i.MaxAutoApproveFilesChanged,
		&i.SensitiveBlastRadiusTags,
		&i.AutoRetriggerReviewEnabled,
		&i.DescriptionAutofixEnabled,
		&i.ReviewDepthMode,
		&i.ReviewDepthDeepPaths,
		&i.ReviewCostBudgetLightUsd,
		&i.ReviewCostBudgetDeepUsd,
		&i.SessionsEnabled,
		&i.LiveEgressEnabled,
		&i.LiveEgressPromotedAt,
		&i.DemotionSweepPendingAt,
		&i.SessionSpendCapUsd,
	)
	return i, err
}
