// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviewcheckruns.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearReviewCheckRunExternalID = `-- name: ClearReviewCheckRunExternalID :exec
UPDATE review_check_runs
SET external_id = NULL
WHERE repo_full_name = $1 AND pr_number = $2
`

type ClearReviewCheckRunExternalIDParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// Companion to UpdateReviewCheckRunPublished above -- called in the SAME
// transaction, under the SAME lock, whenever the caller (outboxworker's
// own reviewCheckNotifier, newIdentityNeeded) has decided the existing
// external_id must not carry forward. Finding A10: this doc used to name
// a head_sha change as the ONLY such condition -- the caller ALSO clears
// it when the row is already terminal-shaped (Stale/TerminalAssessed/
// TerminalNotAssessed) and candidate belongs to a genuinely newer
// attempt on the SAME head sha ("open a NEW check when a review
// restarts after a terminal result... never reopen a concluded one",
// finding A1) -- a case this doc omitted even though the caller has
// always implemented it. Both share the same reason: the existing
// external_id belongs to an identity this row's own next write must not
// reuse (a different SHA in the first case; an already-concluded run in
// the second).
func (q *Queries) ClearReviewCheckRunExternalID(ctx context.Context, arg ClearReviewCheckRunExternalIDParams) error {
	_, err := q.db.Exec(ctx, clearReviewCheckRunExternalID, arg.RepoFullName, arg.PrNumber)
	return err
}

const ensureReviewCheckRunRow = `-- name: EnsureReviewCheckRunRow :exec

INSERT INTO review_check_runs (repo_full_name, pr_number, head_sha, phase)
VALUES ($1, $2, '', '')
ON CONFLICT (repo_full_name, pr_number) DO NOTHING
`

type EnsureReviewCheckRunRowParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// Queries backing ReviewCheckRunStore (§21.1b's own publisher identity).
// See migrations/000132_review_check_runs.up.sql's own doc
// comment for the full per-PR claim design these implement together --
// mirrors EnsureGitHubPRSessionRow/LockGitHubPRSessionForUpdate/
// SetGitHubPRSessionID's own identical three-step atomic-claim idiom
// (githubprsessions.sql), applied here to "which candidate emission wins
// the row" instead of "which mention wins the session".
// Idempotently ensures a (repo_full_name, pr_number) claim row exists,
// with a deliberately EMPTY placeholder phase/head_sha on a fresh
// insert -- the real values are always written by
// UpdateReviewCheckRunPublished below, under LockReviewCheckRunForUpdate's
// own lock, never by this INSERT itself (mirrors EnsureGitHubPRSessionRow's
// own "session_id left NULL on a fresh insert" precedent: this step's
// only job is "make sure the row is there to lock next").
func (q *Queries) EnsureReviewCheckRunRow(ctx context.Context, arg EnsureReviewCheckRunRowParams) error {
	_, err := q.db.Exec(ctx, ensureReviewCheckRunRow, arg.RepoFullName, arg.PrNumber)
	return err
}

const getReviewCheckRunByRepoAndPRNumber = `-- name: GetReviewCheckRunByRepoAndPRNumber :one
SELECT repo_full_name, pr_number, head_sha, external_id, attempt_id, attempt_created_at, phase, base_ref, base_sha, policy_version, created_at, updated_at FROM review_check_runs
WHERE repo_full_name = $1 AND pr_number = $2
`

type GetReviewCheckRunByRepoAndPRNumberParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// A plain, non-locking read -- mirrors GetGitHubPRSessionByRepoAndPRNumber's
// own identical "forward, non-locking read" precedent
// (githubprsessions.sql). pgx.ErrNoRows means no row exists yet for this
// PR.
//
// Finding A10: this used to be documented as "the read a Notifier.Deliver
// call opens with... resolves reviewcheck.Supersedes' own current
// argument" -- describing a pre-read Deliver never actually performed
// (Deliver's own claim sequence resolves "current" from
// LockReviewCheckRunForUpdate, inside its transaction, never from this
// query) -- and, before finding A3's own fix, had no production caller
// at all. It now has one: reviewCheckNotifier.
// guardAgainstSupersessionDuringCall (reviewcheck.go) calls this, with
// no transaction open, AFTER a GitHub write completes, to detect whether
// a concurrently-racing, newer Deliver call already committed a
// different row while that write was in flight -- a genuinely reachable
// pgx.ErrNoRows there would mean this row was deleted between this
// notifier's own earlier claim and this later read (not a real
// production path today, but handled rather than assumed unreachable).
func (q *Queries) GetReviewCheckRunByRepoAndPRNumber(ctx context.Context, arg GetReviewCheckRunByRepoAndPRNumberParams) (ReviewCheckRun, error) {
	row := q.db.QueryRow(ctx, getReviewCheckRunByRepoAndPRNumber, arg.RepoFullName, arg.PrNumber)
	var i ReviewCheckRun
	err := row.Scan(
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.ExternalID,
		&i.AttemptID,
		&i.AttemptCreatedAt,
		&i.Phase,
		&i.BaseRef,
		&i.BaseSha,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockReviewCheckRunForUpdate = `-- name: LockReviewCheckRunForUpdate :one
SELECT repo_full_name, pr_number, head_sha, external_id, attempt_id, attempt_created_at, phase, base_ref, base_sha, policy_version, created_at, updated_at FROM review_check_runs
WHERE repo_full_name = $1 AND pr_number = $2
FOR UPDATE
`

type LockReviewCheckRunForUpdateParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// Locks the (repo_full_name, pr_number) row for the remainder of the
// caller's own transaction -- any concurrent caller's own call to this
// SAME query for the SAME PR blocks here until the first caller commits
// or rolls back. The caller must have already run
// EnsureReviewCheckRunRow (in the SAME transaction) so this row is
// guaranteed to exist by the time this runs.
func (q *Queries) LockReviewCheckRunForUpdate(ctx context.Context, arg LockReviewCheckRunForUpdateParams) (ReviewCheckRun, error) {
	row := q.db.QueryRow(ctx, lockReviewCheckRunForUpdate, arg.RepoFullName, arg.PrNumber)
	var i ReviewCheckRun
	err := row.Scan(
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.ExternalID,
		&i.AttemptID,
		&i.AttemptCreatedAt,
		&i.Phase,
		&i.BaseRef,
		&i.BaseSha,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setReviewCheckRunExternalID = `-- name: SetReviewCheckRunExternalID :one
UPDATE review_check_runs
SET external_id = $3, updated_at = now()
WHERE repo_full_name = $1 AND pr_number = $2 AND attempt_id IS NOT DISTINCT FROM $4 AND external_id IS NULL
RETURNING repo_full_name, pr_number, head_sha, external_id, attempt_id, attempt_created_at, phase, base_ref, base_sha, policy_version, created_at, updated_at
`

type SetReviewCheckRunExternalIDParams struct {
	RepoFullName string      `json:"repo_full_name"`
	PrNumber     int32       `json:"pr_number"`
	ExternalID   *int64      `json:"external_id"`
	AttemptID    pgtype.UUID `json:"attempt_id"`
}

// The publisher's own POST-GitHub-call record write -- a GUARDED update
// (CLAUDE.md/§11's own "guarded UPDATE ... WHERE for cross-writer
// transitions" idiom), never a blind SET: applies only if this row's
// attempt_id still matches attempt_id_guard AND external_id is still
// NULL, i.e. nobody else has since reserved a NEWER identity on this row
// while this caller's own GitHub call was in flight (Notifier.Deliver
// runs with no Postgres transaction held open across it -- migrations/
// 000132's own doc comment). A guard miss (0 rows, pgx.ErrNoRows) means
// exactly that race happened: this caller's own GitHub check run may now
// be an orphan nothing else in this system ever points to again --
// reassessed, NOT harmless (finding A7 -- internal/app/outboxworker's
// own reviewCheckNotifier.Deliver, its doc comment immediately above the
// resolveOrCreateCheckRun call, is this claim's own source of truth: the
// orphan sits on the pull request's own Checks tab PERMANENTLY queued or
// in_progress, a second, real, human-visible entry beside the one this
// system keeps correctly updating, with no reconciliation sweep built
// yet to clean it up) -- the caller logs it and returns nil (this
// delivery attempt is done; whichever newer candidate won the row
// already has, or will soon get, its OWN correct external_id recorded by
// its own Deliver call).
func (q *Queries) SetReviewCheckRunExternalID(ctx context.Context, arg SetReviewCheckRunExternalIDParams) (ReviewCheckRun, error) {
	row := q.db.QueryRow(ctx, setReviewCheckRunExternalID,
		arg.RepoFullName,
		arg.PrNumber,
		arg.ExternalID,
		arg.AttemptID,
	)
	var i ReviewCheckRun
	err := row.Scan(
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.ExternalID,
		&i.AttemptID,
		&i.AttemptCreatedAt,
		&i.Phase,
		&i.BaseRef,
		&i.BaseSha,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewCheckRunPublished = `-- name: UpdateReviewCheckRunPublished :one
UPDATE review_check_runs
SET head_sha = $3, attempt_id = $4, attempt_created_at = $5, phase = $6,
    base_ref = $7, base_sha = $8, policy_version = $9, updated_at = now()
WHERE repo_full_name = $1 AND pr_number = $2
RETURNING repo_full_name, pr_number, head_sha, external_id, attempt_id, attempt_created_at, phase, base_ref, base_sha, policy_version, created_at, updated_at
`

type UpdateReviewCheckRunPublishedParams struct {
	RepoFullName     string             `json:"repo_full_name"`
	PrNumber         int32              `json:"pr_number"`
	HeadSha          string             `json:"head_sha"`
	AttemptID        pgtype.UUID        `json:"attempt_id"`
	AttemptCreatedAt pgtype.Timestamptz `json:"attempt_created_at"`
	Phase            string             `json:"phase"`
	BaseRef          *string            `json:"base_ref"`
	BaseSha          *string            `json:"base_sha"`
	PolicyVersion    int32              `json:"policy_version"`
}

// Records a winning internal/domain/reviewcheck.Emission -- called only
// after the caller has already evaluated reviewcheck.Supersedes against
// the row LockReviewCheckRunForUpdate just returned, still holding that
// SAME lock (this UPDATE never itself decides whether to apply; it is
// the caller's own already-made decision, persisted). external_id is
// deliberately NOT set here: this write happens BEFORE the real GitHub
// call (reserving the identity, never spanning the network call inside
// this transaction -- migrations/000132's own doc comment), so
// external_id is left exactly as it was (unchanged) when the head_sha is
// unchanged too (an in-place update, the existing external check run
// still applies), or explicitly cleared to NULL by the caller via
// ClearReviewCheckRunExternalID below when head_sha is changing (a new
// commit landed -- the OLD external_id belongs to a SHA this row no
// longer targets, and reusing it would silently update the wrong,
// superseded check run).
func (q *Queries) UpdateReviewCheckRunPublished(ctx context.Context, arg UpdateReviewCheckRunPublishedParams) (ReviewCheckRun, error) {
	row := q.db.QueryRow(ctx, updateReviewCheckRunPublished,
		arg.RepoFullName,
		arg.PrNumber,
		arg.HeadSha,
		arg.AttemptID,
		arg.AttemptCreatedAt,
		arg.Phase,
		arg.BaseRef,
		arg.BaseSha,
		arg.PolicyVersion,
	)
	var i ReviewCheckRun
	err := row.Scan(
		&i.RepoFullName,
		&i.PrNumber,
		&i.HeadSha,
		&i.ExternalID,
		&i.AttemptID,
		&i.AttemptCreatedAt,
		&i.Phase,
		&i.BaseRef,
		&i.BaseSha,
		&i.PolicyVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
