// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviewfindings.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getReviewFinding = `-- name: GetReviewFinding :one
SELECT id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check FROM review_findings
WHERE repo_full_name = $1 AND pr_number = $2 AND identity_hash = $3
`

type GetReviewFindingParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
	IdentityHash string `json:"identity_hash"`
}

// Looked up by the rebut/apply-suggestion endpoints (identityHash comes
// straight off the URL path).
func (q *Queries) GetReviewFinding(ctx context.Context, arg GetReviewFindingParams) (ReviewFinding, error) {
	row := q.db.QueryRow(ctx, getReviewFinding, arg.RepoFullName, arg.PrNumber, arg.IdentityHash)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.IdentityHash,
		&i.SentinelKind,
		&i.Severity,
		&i.FilePath,
		&i.Line,
		&i.Description,
		&i.SuggestedFix,
		&i.Status,
		&i.RebuttalText,
		&i.RebuttedBy,
		&i.RebuttedAt,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ReportedSource,
		&i.AdditionCheck,
	)
	return i, err
}

const listAllReviewFindingsForPR = `-- name: ListAllReviewFindingsForPR :many
SELECT id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check FROM review_findings
WHERE repo_full_name = $1 AND pr_number = $2
ORDER BY first_seen_at ASC
`

type ListAllReviewFindingsForPRParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// §26.1 item 5's own merge-readout appendix (§12.2 item 2): EVERY
// finding ever posted for one PR, regardless of status -- unlike
// ListOpenAndRebuttedReviewFindings above (which deliberately excludes
// fix_pending/fix_open/fix_merged/fix_applied for re-review reconciliation
// purposes), a human reading the merge readout needs to see a finding's
// full remediation history too, not just the subset still "live". Ordered
// oldest-first, mirroring that query's own stable ordering.
func (q *Queries) ListAllReviewFindingsForPR(ctx context.Context, arg ListAllReviewFindingsForPRParams) ([]ReviewFinding, error) {
	rows, err := q.db.Query(ctx, listAllReviewFindingsForPR, arg.RepoFullName, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewFinding
	for rows.Next() {
		var i ReviewFinding
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.IdentityHash,
			&i.SentinelKind,
			&i.Severity,
			&i.FilePath,
			&i.Line,
			&i.Description,
			&i.SuggestedFix,
			&i.Status,
			&i.RebuttalText,
			&i.RebuttedBy,
			&i.RebuttedAt,
			&i.FixChildSessionID,
			&i.FixPrNumber,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ReportedSource,
			&i.AdditionCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAndRebuttedReviewFindings = `-- name: ListOpenAndRebuttedReviewFindings :many
SELECT id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check FROM review_findings
WHERE repo_full_name = $1 AND pr_number = $2 AND status IN ('open', 'rebutted', 'fix_recorded')
ORDER BY first_seen_at ASC
`

type ListOpenAndRebuttedReviewFindingsParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// §22.1's own reconciliation read: every 'open', 'rebutted', or
// 'fix_recorded' finding for one PR, oldest-first (a stable, deterministic
// order — see internal/domain/reviewpost.RenderAlreadyAnsweredFacts' own
// doc comment on why ordering matters for a byte-for-byte-repeatable
// render). 'open' is included deliberately, not just 'rebutted': an
// already-reported-but-not-yet-rebutted finding should still read as
// "already told you about this" to a re-reviewing agent, not as brand new
// -- see reviewpost.ReconciledFinding's own doc comment. fix_pending/
// fix_open/fix_merged/fix_applied findings are DELIBERATELY excluded
// here: those already have their own separate, stronger signal (a
// referenced fix PR, or a merged one) that the verdict-update step
// (§17.3) posts directly onto the PR, and re-surfacing them in the SAME
// "already answered, do not re-report" block a plain rebuttal uses would
// blur two different kinds of resolution together. 'fix_recorded'
// (§30.7/§30.9 -- the manual apply-suggestion endpoint's own commit was
// shadow-suppressed) is included for the OPPOSITE reason: it claims no
// such stronger signal at all -- nothing reached the real repository -- so
// a re-reviewing agent must keep treating it as still open, never as
// already resolved.
func (q *Queries) ListOpenAndRebuttedReviewFindings(ctx context.Context, arg ListOpenAndRebuttedReviewFindingsParams) ([]ReviewFinding, error) {
	rows, err := q.db.Query(ctx, listOpenAndRebuttedReviewFindings, arg.RepoFullName, arg.PrNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewFinding
	for rows.Next() {
		var i ReviewFinding
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.IdentityHash,
			&i.SentinelKind,
			&i.Severity,
			&i.FilePath,
			&i.Line,
			&i.Description,
			&i.SuggestedFix,
			&i.Status,
			&i.RebuttalText,
			&i.RebuttedBy,
			&i.RebuttedAt,
			&i.FixChildSessionID,
			&i.FixPrNumber,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ReportedSource,
			&i.AdditionCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewFindingStatusesInWindow = `-- name: ListReviewFindingStatusesInWindow :many
SELECT status, reported_source, addition_check FROM review_findings
WHERE repo_full_name = $1 AND first_seen_at > $2
ORDER BY first_seen_at ASC
LIMIT $3
`

type ListReviewFindingStatusesInWindowParams struct {
	RepoFullName string             `json:"repo_full_name"`
	FirstSeenAt  pgtype.Timestamptz `json:"first_seen_at"`
	Limit        int32              `json:"limit"`
}

type ListReviewFindingStatusesInWindowRow struct {
	Status         string  `json:"status"`
	ReportedSource *string `json:"reported_source"`
	AdditionCheck  *string `json:"addition_check"`
}

// §21's own "Review finding outcomes" analytics KPI (§21.1/§12.2
// item 6) -- every finding FIRST seen for repoFullName after sinceTime,
// bounded by limit (§21.1's own "bounded from day one" discipline). Only
// the columns the pure reduction reads are selected: the status, and
// (§26.5/§26.6's amendment, migrations/000154) the reported source and
// the addition check, so an unverified counter-review addition is counted
// apart and precision can be read per source
// (internal/domain/reviewverdict.FindingOutcomesBySource), mirroring
// internal/app/decisioninbox.Metrics' own identical "select only the
// columns the pure reduction actually needs" precedent.
func (q *Queries) ListReviewFindingStatusesInWindow(ctx context.Context, arg ListReviewFindingStatusesInWindowParams) ([]ListReviewFindingStatusesInWindowRow, error) {
	rows, err := q.db.Query(ctx, listReviewFindingStatusesInWindow, arg.RepoFullName, arg.FirstSeenAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewFindingStatusesInWindowRow
	for rows.Next() {
		var i ListReviewFindingStatusesInWindowRow
		if err := rows.Scan(&i.Status, &i.ReportedSource, &i.AdditionCheck); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReviewFindingFixApplied = `-- name: MarkReviewFindingFixApplied :one
UPDATE review_findings
SET status = 'fix_applied'
WHERE repo_full_name = $1 AND pr_number = $2 AND identity_hash = $3
RETURNING id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check
`

type MarkReviewFindingFixAppliedParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
	IdentityHash string `json:"identity_hash"`
}

// Set by the manual apply-suggestion endpoint once it has successfully
// committed a finding's own SuggestedFix directly (§12.2 item 2) -- the
// OTHER of the two mutually-exclusive remediation paths.
func (q *Queries) MarkReviewFindingFixApplied(ctx context.Context, arg MarkReviewFindingFixAppliedParams) (ReviewFinding, error) {
	row := q.db.QueryRow(ctx, markReviewFindingFixApplied, arg.RepoFullName, arg.PrNumber, arg.IdentityHash)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.IdentityHash,
		&i.SentinelKind,
		&i.Severity,
		&i.FilePath,
		&i.Line,
		&i.Description,
		&i.SuggestedFix,
		&i.Status,
		&i.RebuttalText,
		&i.RebuttedBy,
		&i.RebuttedAt,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ReportedSource,
		&i.AdditionCheck,
	)
	return i, err
}

const markReviewFindingFixOpen = `-- name: MarkReviewFindingFixOpen :one
UPDATE review_findings
SET status = 'fix_open', fix_pr_number = $2
WHERE fix_child_session_id = $1 AND status = 'fix_pending'
RETURNING id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check
`

type MarkReviewFindingFixOpenParams struct {
	FixChildSessionID pgtype.UUID `json:"fix_child_session_id"`
	FixPrNumber       *int32      `json:"fix_pr_number"`
}

// Set once the fix session's own fix PR has actually been opened
// (pushpr.go's own createSentinelFixPRBestEffort).
func (q *Queries) MarkReviewFindingFixOpen(ctx context.Context, arg MarkReviewFindingFixOpenParams) (ReviewFinding, error) {
	row := q.db.QueryRow(ctx, markReviewFindingFixOpen, arg.FixChildSessionID, arg.FixPrNumber)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.IdentityHash,
		&i.SentinelKind,
		&i.Severity,
		&i.FilePath,
		&i.Line,
		&i.Description,
		&i.SuggestedFix,
		&i.Status,
		&i.RebuttalText,
		&i.RebuttedBy,
		&i.RebuttedAt,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ReportedSource,
		&i.AdditionCheck,
	)
	return i, err
}

const markReviewFindingFixPending = `-- name: MarkReviewFindingFixPending :one
UPDATE review_findings
SET status = 'fix_pending', fix_child_session_id = $4
WHERE repo_full_name = $1 AND pr_number = $2 AND identity_hash = $3
  AND status IN ('open', 'fix_pending')
RETURNING id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check
`

type MarkReviewFindingFixPendingParams struct {
	RepoFullName      string      `json:"repo_full_name"`
	PrNumber          int32       `json:"pr_number"`
	IdentityHash      string      `json:"identity_hash"`
	FixChildSessionID pgtype.UUID `json:"fix_child_session_id"`
}

// Set the moment the sentinel-auto-fix outbox worker claims this finding
// for a child session (§17.2) -- suppresses the manual apply-suggestion
// action from this point on (§17.3: "the two remediation paths are
// mutually exclusive per finding"). Guarded on status IN ('open',
// 'fix_pending') -- audit fix, mirrors MarkReviewFindingFixOpen's own
// identical "WHERE ... AND status = ..." discipline immediately below:
// internal/app/outboxworker's own sentinelAutoFixNotifier.Deliver
// (sentinelautofix.go) now RETURNS a genuine per-finding store failure
// here instead of discarding it, so outboxworker's builder.go retries the
// whole delivery -- and that retry re-runs this SAME write for every
// finding in the payload, including ones an earlier, partially-failed
// attempt already reached successfully. Re-running with status still
// 'fix_pending' is a harmless no-op (same values rewritten); WITHOUT this
// guard, re-running for a finding that has SINCE progressed past
// fix_pending (fix_open/fix_merged/fix_applied -- e.g. the fix session
// finished and its PR already opened before the retry ran) would silently
// regress it back to fix_pending. With the guard, that case is instead a
// harmless pgx.ErrNoRows no-op, exactly like a finding whose row has
// since disappeared entirely.
func (q *Queries) MarkReviewFindingFixPending(ctx context.Context, arg MarkReviewFindingFixPendingParams) (ReviewFinding, error) {
	row := q.db.QueryRow(ctx, markReviewFindingFixPending,
		arg.RepoFullName,
		arg.PrNumber,
		arg.IdentityHash,
		arg.FixChildSessionID,
	)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.IdentityHash,
		&i.SentinelKind,
		&i.Severity,
		&i.FilePath,
		&i.Line,
		&i.Description,
		&i.SuggestedFix,
		&i.Status,
		&i.RebuttalText,
		&i.RebuttedBy,
		&i.RebuttedAt,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ReportedSource,
		&i.AdditionCheck,
	)
	return i, err
}

const markReviewFindingFixRecorded = `-- name: MarkReviewFindingFixRecorded :one
UPDATE review_findings
SET status = 'fix_recorded'
WHERE repo_full_name = $1 AND pr_number = $2 AND identity_hash = $3
RETURNING id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check
`

type MarkReviewFindingFixRecordedParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
	IdentityHash string `json:"identity_hash"`
}

// Set by the manual apply-suggestion endpoint instead of
// MarkReviewFindingFixApplied when the endpoint's own UpdateFileContent
// call came back shadow-suppressed (§30.7/§30.9): the commit SHA it
// received is shadowscm's own self-evidently synthetic value, not a real
// git object, so nothing was actually committed to the repository.
// Deliberately a DISTINCT status from 'fix_applied' -- see
// reviewpost.FindingStatusFixRecorded's own doc comment for why marking
// this 'fix_applied' would let §24's automatic re-review re-detect the
// SAME unfixed defect while this row still claims it was already
// resolved, and ListOpenAndRebuttedReviewFindings' own doc comment (above)
// for why this status is included in re-review reconciliation while
// 'fix_applied' is not.
func (q *Queries) MarkReviewFindingFixRecorded(ctx context.Context, arg MarkReviewFindingFixRecordedParams) (ReviewFinding, error) {
	row := q.db.QueryRow(ctx, markReviewFindingFixRecorded, arg.RepoFullName, arg.PrNumber, arg.IdentityHash)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.IdentityHash,
		&i.SentinelKind,
		&i.Severity,
		&i.FilePath,
		&i.Line,
		&i.Description,
		&i.SuggestedFix,
		&i.Status,
		&i.RebuttalText,
		&i.RebuttedBy,
		&i.RebuttedAt,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ReportedSource,
		&i.AdditionCheck,
	)
	return i, err
}

const markReviewFindingRebutted = `-- name: MarkReviewFindingRebutted :one
UPDATE review_findings
SET status = 'rebutted', rebuttal_text = $4, rebutted_by = $5, rebutted_at = now()
WHERE repo_full_name = $1 AND pr_number = $2 AND identity_hash = $3
RETURNING id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check
`

type MarkReviewFindingRebuttedParams struct {
	RepoFullName string      `json:"repo_full_name"`
	PrNumber     int32       `json:"pr_number"`
	IdentityHash string      `json:"identity_hash"`
	RebuttalText *string     `json:"rebuttal_text"`
	RebuttedBy   pgtype.UUID `json:"rebutted_by"`
}

// The rebuttal endpoint's own write (POST .../findings/{identityHash}/rebut,
// maintainer+ only, authz.ActionEditReviewVerdict) -- sets status,
// rebuttal_text, rebutted_by, rebutted_at together, atomically.
func (q *Queries) MarkReviewFindingRebutted(ctx context.Context, arg MarkReviewFindingRebuttedParams) (ReviewFinding, error) {
	row := q.db.QueryRow(ctx, markReviewFindingRebutted,
		arg.RepoFullName,
		arg.PrNumber,
		arg.IdentityHash,
		arg.RebuttalText,
		arg.RebuttedBy,
	)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.IdentityHash,
		&i.SentinelKind,
		&i.Severity,
		&i.FilePath,
		&i.Line,
		&i.Description,
		&i.SuggestedFix,
		&i.Status,
		&i.RebuttalText,
		&i.RebuttedBy,
		&i.RebuttedAt,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ReportedSource,
		&i.AdditionCheck,
	)
	return i, err
}

const markReviewFindingsFixMergedByFixSession = `-- name: MarkReviewFindingsFixMergedByFixSession :many
UPDATE review_findings
SET status = 'fix_merged'
WHERE fix_child_session_id = $1 AND status IN ('fix_pending', 'fix_open')
RETURNING id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check
`

// Merge-gating's own terminal write (§17.4, once all four checks pass and
// the fix PR actually merges) -- every finding this ONE fix session was
// addressing transitions to 'fix_merged' together.
func (q *Queries) MarkReviewFindingsFixMergedByFixSession(ctx context.Context, fixChildSessionID pgtype.UUID) ([]ReviewFinding, error) {
	rows, err := q.db.Query(ctx, markReviewFindingsFixMergedByFixSession, fixChildSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewFinding
	for rows.Next() {
		var i ReviewFinding
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.IdentityHash,
			&i.SentinelKind,
			&i.Severity,
			&i.FilePath,
			&i.Line,
			&i.Description,
			&i.SuggestedFix,
			&i.Status,
			&i.RebuttalText,
			&i.RebuttedBy,
			&i.RebuttedAt,
			&i.FixChildSessionID,
			&i.FixPrNumber,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.ReportedSource,
			&i.AdditionCheck,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReviewFinding = `-- name: UpsertReviewFinding :one

INSERT INTO review_findings (
    repo_full_name, pr_number, identity_hash, sentinel_kind, severity,
    file_path, line, description, suggested_fix,
    reported_source, addition_check
)
VALUES ($1, $2, $3, $7, $4, $5, $8, $6, $9,
    $10, $11)
ON CONFLICT (repo_full_name, pr_number, identity_hash)
DO UPDATE SET last_seen_at = now(),
    reported_source = EXCLUDED.reported_source,
    addition_check = EXCLUDED.addition_check
RETURNING id, repo_full_name, pr_number, identity_hash, sentinel_kind, severity, file_path, line, description, suggested_fix, status, rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, fix_pr_number, first_seen_at, last_seen_at, reported_source, addition_check
`

type UpsertReviewFindingParams struct {
	RepoFullName   string  `json:"repo_full_name"`
	PrNumber       int32   `json:"pr_number"`
	IdentityHash   string  `json:"identity_hash"`
	Severity       string  `json:"severity"`
	FilePath       string  `json:"file_path"`
	Description    string  `json:"description"`
	SentinelKind   *string `json:"sentinel_kind"`
	Line           *int32  `json:"line"`
	SuggestedFix   *string `json:"suggested_fix"`
	ReportedSource *string `json:"reported_source"`
	AdditionCheck  *string `json:"addition_check"`
}

// Queries backing ReviewFindingStore ("sentinels + suggestions",
// §17/§22.1) -- see migrations/000046_review_findings.up.sql's own doc
// comment for the full table design.
// The one write every verdict post with findings makes, once per finding
// (internal/adapters/inbound/httpapi/reviewverdict.go) -- idempotent
// create-or-update keyed on (repo_full_name, pr_number, identity_hash),
// mirroring repo_settings'/github_pr_sessions' own established "INSERT
// ... ON CONFLICT" idiom. Critically, ONLY last_seen_head_sha/last_seen_at
// are overwritten on a re-report of the SAME identity -- status,
// rebuttal_text, rebutted_by, rebutted_at, fix_child_session_id, and
// fix_pr_number are all PRESERVED (never reset back to 'open'/NULL),
// which is exactly what makes a finding re-reported on a LATER commit
// still read as "already rebutted"/"already fix_open" rather than
// silently reverting to looking brand new.
//
// reported_source/addition_check (§26.6's amendment, migrations/
// 000154_review_findings_source.up.sql) describe the finding's LATEST
// publication, so a re-report overwrites them just as it moves
// last_seen_at: a counter-review addition published unverified and later
// re-published checked, or re-reported by the primary reviewer, reads as
// that later publication says. A row first published before 000154 gets
// both on its next publication.
func (q *Queries) UpsertReviewFinding(ctx context.Context, arg UpsertReviewFindingParams) (ReviewFinding, error) {
	row := q.db.QueryRow(ctx, upsertReviewFinding,
		arg.RepoFullName,
		arg.PrNumber,
		arg.IdentityHash,
		arg.Severity,
		arg.FilePath,
		arg.Description,
		arg.SentinelKind,
		arg.Line,
		arg.SuggestedFix,
		arg.ReportedSource,
		arg.AdditionCheck,
	)
	var i ReviewFinding
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.IdentityHash,
		&i.SentinelKind,
		&i.Severity,
		&i.FilePath,
		&i.Line,
		&i.Description,
		&i.SuggestedFix,
		&i.Status,
		&i.RebuttalText,
		&i.RebuttedBy,
		&i.RebuttedAt,
		&i.FixChildSessionID,
		&i.FixPrNumber,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.ReportedSource,
		&i.AdditionCheck,
	)
	return i, err
}
