// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviewverdictacceptances.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveReviewVerdictAcceptance = `-- name: GetActiveReviewVerdictAcceptance :one
SELECT id, repo_full_name, pr_number, verdict_id, attempt_id, head_sha, base_ref, base_sha, ancestor_chain, policy_version, reason, justification, accepted_by, accepted_at, revoked_at, revoked_by FROM review_verdict_acceptances
WHERE repo_full_name = $1 AND pr_number = $2 AND revoked_at IS NULL
ORDER BY accepted_at DESC
LIMIT 1
`

type GetActiveReviewVerdictAcceptanceParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
}

// The one read the merge/decision-inbox path needs: the LATEST
// non-revoked acceptance for one pull request, if any -- pgx.ErrNoRows
// means no acceptance is currently active for this PR (never accepted at
// all, or every acceptance ever granted has since been revoked).
// Applicability against the PR's CURRENT verdict is decided by the
// caller (internal/domain/reviewverdict.Acceptance.Applicable), never by
// this query -- a row returned here may still be inapplicable (a new
// attempt posted a different verdict since this row was accepted).
func (q *Queries) GetActiveReviewVerdictAcceptance(ctx context.Context, arg GetActiveReviewVerdictAcceptanceParams) (ReviewVerdictAcceptance, error) {
	row := q.db.QueryRow(ctx, getActiveReviewVerdictAcceptance, arg.RepoFullName, arg.PrNumber)
	var i ReviewVerdictAcceptance
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.VerdictID,
		&i.AttemptID,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.AncestorChain,
		&i.PolicyVersion,
		&i.Reason,
		&i.Justification,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const getReviewVerdictAcceptance = `-- name: GetReviewVerdictAcceptance :one
SELECT id, repo_full_name, pr_number, verdict_id, attempt_id, head_sha, base_ref, base_sha, ancestor_chain, policy_version, reason, justification, accepted_by, accepted_at, revoked_at, revoked_by FROM review_verdict_acceptances WHERE id = $1 AND repo_full_name = $2
`

type GetReviewVerdictAcceptanceParams struct {
	ID           pgtype.UUID `json:"id"`
	RepoFullName string      `json:"repo_full_name"`
}

// Looked up by the revoke endpoint (acceptance id comes straight off the
// URL path, repoFullName off the route) -- SCOPED to repoFullName,
// mirroring GetFalsePositivePattern's own identical "id alone is not
// enough" audit-fix precedent (reviewfalsepositivepatterns.sql): a
// pattern/acceptance belonging to a DIFFERENT repo must never be
// reachable through the wrong repo's own URL.
func (q *Queries) GetReviewVerdictAcceptance(ctx context.Context, arg GetReviewVerdictAcceptanceParams) (ReviewVerdictAcceptance, error) {
	row := q.db.QueryRow(ctx, getReviewVerdictAcceptance, arg.ID, arg.RepoFullName)
	var i ReviewVerdictAcceptance
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.VerdictID,
		&i.AttemptID,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.AncestorChain,
		&i.PolicyVersion,
		&i.Reason,
		&i.Justification,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const insertReviewVerdictAcceptance = `-- name: InsertReviewVerdictAcceptance :one

INSERT INTO review_verdict_acceptances (
    repo_full_name, pr_number, verdict_id, attempt_id, head_sha,
    base_ref, base_sha, ancestor_chain, policy_version,
    reason, justification, accepted_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, repo_full_name, pr_number, verdict_id, attempt_id, head_sha, base_ref, base_sha, ancestor_chain, policy_version, reason, justification, accepted_by, accepted_at, revoked_at, revoked_by
`

type InsertReviewVerdictAcceptanceParams struct {
	RepoFullName  string      `json:"repo_full_name"`
	PrNumber      int32       `json:"pr_number"`
	VerdictID     pgtype.UUID `json:"verdict_id"`
	AttemptID     pgtype.UUID `json:"attempt_id"`
	HeadSha       string      `json:"head_sha"`
	BaseRef       *string     `json:"base_ref"`
	BaseSha       *string     `json:"base_sha"`
	AncestorChain []byte      `json:"ancestor_chain"`
	PolicyVersion int32       `json:"policy_version"`
	Reason        string      `json:"reason"`
	Justification string      `json:"justification"`
	AcceptedBy    pgtype.UUID `json:"accepted_by"`
}

// Queries backing ReviewVerdictAcceptanceStore ("human acceptance of a
// verdict the engine refuses", §21.1b) -- see migrations/
// 000135_review_verdict_acceptances.up.sql's own doc comment for the
// table's full design.
// APPEND-ONLY create (this table's own migration doc comment: "never
// UPDATEd for a re-accept") -- a maintainer+ accepting the SAME verdict
// twice (a double-click, a retried request) simply inserts a second row;
// GetActiveReviewVerdictAcceptance's own "latest non-revoked row" read is
// what a caller consults, never a uniqueness constraint here.
func (q *Queries) InsertReviewVerdictAcceptance(ctx context.Context, arg InsertReviewVerdictAcceptanceParams) (ReviewVerdictAcceptance, error) {
	row := q.db.QueryRow(ctx, insertReviewVerdictAcceptance,
		arg.RepoFullName,
		arg.PrNumber,
		arg.VerdictID,
		arg.AttemptID,
		arg.HeadSha,
		arg.BaseRef,
		arg.BaseSha,
		arg.AncestorChain,
		arg.PolicyVersion,
		arg.Reason,
		arg.Justification,
		arg.AcceptedBy,
	)
	var i ReviewVerdictAcceptance
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.VerdictID,
		&i.AttemptID,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.AncestorChain,
		&i.PolicyVersion,
		&i.Reason,
		&i.Justification,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const listReviewVerdictAcceptances = `-- name: ListReviewVerdictAcceptances :many
SELECT id, repo_full_name, pr_number, verdict_id, attempt_id, head_sha, base_ref, base_sha, ancestor_chain, policy_version, reason, justification, accepted_by, accepted_at, revoked_at, revoked_by FROM review_verdict_acceptances
WHERE repo_full_name = $1 AND pr_number = $2
ORDER BY accepted_at DESC
LIMIT $3
`

type ListReviewVerdictAcceptancesParams struct {
	RepoFullName string `json:"repo_full_name"`
	PrNumber     int32  `json:"pr_number"`
	Limit        int32  `json:"limit"`
}

// The audit view: EVERY acceptance for one pull request, active or
// revoked, newest-first -- mirrors ListFalsePositivePatterns' own
// identical audit-view shape (reviewfalsepositivepatterns.sql), bounded
// by limit per this codebase's own "no unbounded list, ever" discipline.
func (q *Queries) ListReviewVerdictAcceptances(ctx context.Context, arg ListReviewVerdictAcceptancesParams) ([]ReviewVerdictAcceptance, error) {
	rows, err := q.db.Query(ctx, listReviewVerdictAcceptances, arg.RepoFullName, arg.PrNumber, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewVerdictAcceptance
	for rows.Next() {
		var i ReviewVerdictAcceptance
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.PrNumber,
			&i.VerdictID,
			&i.AttemptID,
			&i.HeadSha,
			&i.BaseRef,
			&i.BaseSha,
			&i.AncestorChain,
			&i.PolicyVersion,
			&i.Reason,
			&i.Justification,
			&i.AcceptedBy,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.RevokedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeReviewVerdictAcceptance = `-- name: RevokeReviewVerdictAcceptance :one
UPDATE review_verdict_acceptances
SET revoked_at = now(), revoked_by = $2
WHERE id = $1 AND repo_full_name = $3 AND revoked_at IS NULL
RETURNING id, repo_full_name, pr_number, verdict_id, attempt_id, head_sha, base_ref, base_sha, ancestor_chain, policy_version, reason, justification, accepted_by, accepted_at, revoked_at, revoked_by
`

type RevokeReviewVerdictAcceptanceParams struct {
	ID           pgtype.UUID `json:"id"`
	RevokedBy    pgtype.UUID `json:"revoked_by"`
	RepoFullName string      `json:"repo_full_name"`
}

// The revoke write: a maintainer+ (the SAME role that may accept --
// see internal/domain/authz's own ActionAcceptReviewVerdict, row 5)
// explicitly withdraws an active acceptance. SCOPED to repo_full_name
// (mirrors RetireFalsePositivePattern's own identical audit-fix
// precedent) AND guarded (WHERE revoked_at IS NULL, CLAUDE.md/§11's own
// "guarded UPDATE ... WHERE for cross-writer transitions" rule) so
// revoking an ALREADY-revoked acceptance is a no-op that returns
// pgx.ErrNoRows (never a second, silently overwriting revoked_at/
// revoked_by) -- the caller (httpapi) tells "never existed in this
// repo" apart from "exists in this repo but already revoked" via a
// follow-up GetReviewVerdictAcceptance (also repo-scoped) read on this
// same error path, mirroring RetireFalsePositivePattern's own identical
// caller-side discipline.
func (q *Queries) RevokeReviewVerdictAcceptance(ctx context.Context, arg RevokeReviewVerdictAcceptanceParams) (ReviewVerdictAcceptance, error) {
	row := q.db.QueryRow(ctx, revokeReviewVerdictAcceptance, arg.ID, arg.RevokedBy, arg.RepoFullName)
	var i ReviewVerdictAcceptance
	err := row.Scan(
		&i.ID,
		&i.RepoFullName,
		&i.PrNumber,
		&i.VerdictID,
		&i.AttemptID,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.AncestorChain,
		&i.PolicyVersion,
		&i.Reason,
		&i.Justification,
		&i.AcceptedBy,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}
