// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpActorEpoch = `-- name: BumpActorEpoch :one
UPDATE sessions SET actor_epoch = actor_epoch + 1
WHERE id = $1
RETURNING actor_epoch
`

// Increments a session's actor_epoch and returns the new value. Called
// once, at acquisition time, when an actor takes ownership of a session
// (§2: "bumped on each acquisition") -- never as part of an ordinary
// state-transition write (those only READ the epoch, via
// GetSessionActorEpochForUpdate below, to check it hasn't moved).
func (q *Queries) BumpActorEpoch(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, bumpActorEpoch, id)
	var actor_epoch int64
	err := row.Scan(&actor_epoch)
	return actor_epoch, err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (title, spawn_source, created_by, repos, environment_id, provenance_tag, build_model_id, build_effort, parent_session_id, spawn_depth, epistemic_check_enabled)
VALUES ($1, $2, $3, COALESCE($4, '[]'::jsonb), $5, $6, $7, $8, $9, COALESCE($10, 0), $11)
RETURNING id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id, parent_session_id, spawn_depth, build_effort, epistemic_check_enabled
`

type CreateSessionParams struct {
	Title                 *string            `json:"title"`
	SpawnSource           SessionSpawnSource `json:"spawn_source"`
	CreatedBy             pgtype.UUID        `json:"created_by"`
	Repos                 interface{}        `json:"repos"`
	EnvironmentID         pgtype.UUID        `json:"environment_id"`
	ProvenanceTag         *string            `json:"provenance_tag"`
	BuildModelID          *string            `json:"build_model_id"`
	BuildEffort           *string            `json:"build_effort"`
	ParentSessionID       pgtype.UUID        `json:"parent_session_id"`
	SpawnDepth            interface{}        `json:"spawn_depth"`
	EpistemicCheckEnabled *bool              `json:"epistemic_check_enabled"`
}

// Queries backing SessionStore (§4.3). Just enough to prove the pipeline
// end to end (create + get) — full CRUD lands with the PRs that build out
// session-actor persistence (PR-11+).
// repos defaults to '[]'::jsonb via COALESCE (not the column's own DEFAULT
// clause) specifically so every EXISTING call site that never set Repos
// (every session row created before this column existed) keeps compiling
// and behaving identically: a nil/absent []byte param binds SQL NULL, and
// COALESCE(NULL, '[]'::jsonb) resolves to the same empty-list default a
// bare column-default insert would have produced.
//
// environment_id/provenance_tag (row 10, "domain: Environment scoping",
// §14.1) are both sqlc.narg -- nullable, optional params -- so every
// EXISTING call site that never sets them (every session created before
// this batch) keeps compiling and behaving identically: both stay NULL,
// byte-for-byte today's unscoped behavior.
//
// build_model_id ("plan mode, web", §12.2 item 3) is likewise
// sqlc.narg -- every EXISTING call site that never sets it keeps
// compiling and behaving identically (NULL, "use the default model
// catalog entry", migrations/000034_plan_mode.up.sql's own convention).
//
// build_effort (migrations/000063_turn_session_effort.up.sql,
// §29.8) mirrors build_model_id's own shape exactly, one column over --
// same sqlc.narg treatment, same "every existing call site keeps
// compiling and behaving identically (NULL, use the default)" guarantee.
//
// parent_session_id/spawn_depth ("sentinels + suggestions",
// §17.2, migrations/000045) are likewise sqlc.narg/COALESCE-defaulted --
// every EXISTING call site (every session created before this Step) keeps
// compiling and behaving identically: parent_session_id stays NULL,
// spawn_depth stays 0. httpapi.CreateSessionOnTx's own ChildSessionOptions
// (create.go) is this Step's own mechanism that supplies non-default
// values -- either via httpapi.SpawnChildSession (childsession.go, a
// caller with no already-open transaction of its own) or, since the
// Finding-1 audit fix, internal/app/outboxworker's own sentinelautofix.go,
// which calls CreateSessionOnTx directly, inline on its own
// claim-locked transaction (see that file's own doc comment for why it
// cannot go through SpawnChildSession's separate transaction instead).
//
// epistemic_check_enabled ("builder epistemic pre-action check",
// §20.4, migrations/000066) mirrors build_model_id's own sqlc.narg
// treatment exactly: every EXISTING call site that never sets it keeps
// compiling and behaving identically (NULL, "use platform.Config's own
// global default" -- off, unless an operator has turned the default on).
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Title,
		arg.SpawnSource,
		arg.CreatedBy,
		arg.Repos,
		arg.EnvironmentID,
		arg.ProvenanceTag,
		arg.BuildModelID,
		arg.BuildEffort,
		arg.ParentSessionID,
		arg.SpawnDepth,
		arg.EpistemicCheckEnabled,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
		&i.ParentSessionID,
		&i.SpawnDepth,
		&i.BuildEffort,
		&i.EpistemicCheckEnabled,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id, parent_session_id, spawn_depth, build_effort, epistemic_check_enabled FROM sessions
WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
		&i.ParentSessionID,
		&i.SpawnDepth,
		&i.BuildEffort,
		&i.EpistemicCheckEnabled,
	)
	return i, err
}

const getSessionActivityFacts = `-- name: GetSessionActivityFacts :one
SELECT
    s.id AS session_id,
    s.status AS session_status,
    s.failure_reason AS session_failure_reason,
    s.archived AS archived,
    sb.status AS sandbox_status,
    statement_timestamp()::timestamptz AS observed_at,
    COALESCE(tc.turn_counts, '{}'::jsonb)::jsonb AS turn_counts,
    inflight.id AS in_flight_turn_id,
    COALESCE(inflight.status::text, '')::text AS in_flight_turn_status,
    inflight.dispatched_at AS in_flight_dispatched_at,
    lastrun.id AS last_run_turn_id,
    COALESCE(lastrun.status::text, '')::text AS last_run_status,
    lastrun.completed_at AS last_run_completed_at,
    newest.id AS newest_turn_id,
    awaitingplan.id AS awaiting_plan_id,
    awaitingplan.created_at AS awaiting_plan_since,
    awaitingstep.id AS awaiting_step_id,
    awaitingstep.updated_at AS awaiting_step_since,
    escalated.id AS escalated_run_id,
    escalated.updated_at AS escalated_run_since
FROM sessions s
LEFT JOIN sandboxes sb ON sb.session_id = s.id
LEFT JOIN LATERAL (
    SELECT jsonb_object_agg(c.status, c.n) AS turn_counts
    FROM (
        SELECT t.status::text AS status, count(*) AS n
        FROM turns t
        WHERE t.session_id = s.id
        GROUP BY t.status
    ) c
) tc ON true
LEFT JOIN LATERAL (
    SELECT t.id, t.status, t.dispatched_at
    FROM turns t
    WHERE t.session_id = s.id AND t.status IN ('dispatched', 'processing')
    ORDER BY t.created_at, t.id
    LIMIT 1
) inflight ON true
LEFT JOIN LATERAL (
    SELECT t.id, t.status, t.completed_at
    FROM turns t
    WHERE t.session_id = s.id AND t.status IN ('completed', 'failed', 'cancelled')
    ORDER BY t.created_at DESC, t.id DESC
    LIMIT 1
) lastrun ON true
LEFT JOIN LATERAL (
    SELECT t.id
    FROM turns t
    WHERE t.session_id = s.id
    ORDER BY t.created_at DESC, t.id DESC
    LIMIT 1
) newest ON true
LEFT JOIN LATERAL (
    SELECT p.id, p.created_at
    FROM plans p
    WHERE p.session_id = s.id AND p.status = 'awaiting_approval'
    ORDER BY p.created_at, p.id
    LIMIT 1
) awaitingplan ON true
LEFT JOIN LATERAL (
    SELECT sr.id, sr.updated_at
    FROM workflow_step_runs sr
    JOIN workflow_runs wr ON wr.id = sr.workflow_run_id
    WHERE wr.session_id = s.id AND sr.status = 'awaiting_decision'
    ORDER BY sr.updated_at, sr.id
    LIMIT 1
) awaitingstep ON true
LEFT JOIN LATERAL (
    SELECT wr.id, wr.updated_at
    FROM (
        SELECT r.id, r.status, r.workflow_definition_id, r.updated_at
        FROM workflow_runs r
        WHERE r.session_id = s.id
        ORDER BY r.created_at DESC, r.id DESC
        LIMIT 1
    ) wr
    JOIN workflow_definitions d ON d.id = wr.workflow_definition_id
    WHERE wr.status = 'needs_review'
      AND NOT d.is_built_in
      AND EXISTS (
          SELECT 1
          FROM workflow_step_runs sr
          WHERE sr.workflow_run_id = wr.id AND sr.turn_id = newest.id
      )
) escalated ON true
WHERE s.id = $1
`

type GetSessionActivityFactsRow struct {
	SessionID            pgtype.UUID           `json:"session_id"`
	SessionStatus        SessionStatus         `json:"session_status"`
	SessionFailureReason *SessionFailureReason `json:"session_failure_reason"`
	Archived             bool                  `json:"archived"`
	SandboxStatus        *SandboxStatus        `json:"sandbox_status"`
	ObservedAt           pgtype.Timestamptz    `json:"observed_at"`
	TurnCounts           []byte                `json:"turn_counts"`
	InFlightTurnID       pgtype.UUID           `json:"in_flight_turn_id"`
	InFlightTurnStatus   string                `json:"in_flight_turn_status"`
	InFlightDispatchedAt pgtype.Timestamptz    `json:"in_flight_dispatched_at"`
	LastRunTurnID        pgtype.UUID           `json:"last_run_turn_id"`
	LastRunStatus        string                `json:"last_run_status"`
	LastRunCompletedAt   pgtype.Timestamptz    `json:"last_run_completed_at"`
	NewestTurnID         pgtype.UUID           `json:"newest_turn_id"`
	AwaitingPlanID       pgtype.UUID           `json:"awaiting_plan_id"`
	AwaitingPlanSince    pgtype.Timestamptz    `json:"awaiting_plan_since"`
	AwaitingStepID       pgtype.UUID           `json:"awaiting_step_id"`
	AwaitingStepSince    pgtype.Timestamptz    `json:"awaiting_step_since"`
	EscalatedRunID       pgtype.UUID           `json:"escalated_run_id"`
	EscalatedRunSince    pgtype.Timestamptz    `json:"escalated_run_since"`
}

// Every fact GET /api/sessions/{sessionID}/status derives a session's
// activity from (technical plan §43.20), in ONE statement and so one MVCC
// snapshot: two statements under READ COMMITTED could interleave with the
// transaction that completes a plan-mode turn and inserts its plan
// (sessionactor's recordPlanIfNeeded) and see "turn completed, no plan
// yet" -- a false "finished". Deliberately NOT sessions.status: that
// column is re-derived only when a turn reaches a terminal state, so a
// queued or running turn can sit under any of its five values; it is
// selected here only to decide whether sessions.failure_reason still
// describes the last run (the handler's own rule), never the activity.
//
// turn_counts is the per-state turn histogram as a JSON object (state ->
// count), not one column per known state: a state added to turn_status
// later still reaches internal/domain/session.DeriveActivity, which counts
// an unknown state as work in flight, instead of being silently dropped.
// Aggregates and single-row lookups only -- never the turns themselves
// (turns per session are unbounded, and each row carries its prompt).
// Every lookup leads with session_id on an existing index (turns_session_
// id_dispatched_message_id_idx, plans_one_awaiting_approval_per_session,
// workflow_runs_session_id_idx, workflow_step_runs_one_live_per_run); the
// escalation's two follow-up checks go by primary key and by
// workflow_run_id (workflow_step_runs_run_step_idx).
//
// escalated is the session's LIVE workflow escalation, never merely a run
// in needs_review: nothing moves a run out of needs_review, and the next
// turn starts a fresh run beside the parked one (migrations/000057), so
// counting every such run would gate the session for good. A needs_review
// run is reported only when all three hold: it is the session's newest
// workflow run; the session's newest turn is one of that run's own
// attempts (workflow_step_runs.turn_id), so no turn has come after it --
// whether that turn started a run of its own or none (a turn queued behind
// a running one, a plan's implementation turn); and its definition is not
// a built-in one, whose escalation no person or route can act on
// (technical plan §43.20 gives the reasons).
//
// Turn order is created_at, then id -- ListTurnsForSession's own order,
// with id breaking a tie; workflow runs are ordered the same way. observed_at is the database's own statement time,
// the instant the snapshot was taken. The two turn statuses are text, ”
// when their turn is absent (its id is then NULL): an enum column from an
// outer-joined subquery would be generated as a non-nullable type that
// cannot scan NULL.
func (q *Queries) GetSessionActivityFacts(ctx context.Context, id pgtype.UUID) (GetSessionActivityFactsRow, error) {
	row := q.db.QueryRow(ctx, getSessionActivityFacts, id)
	var i GetSessionActivityFactsRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionStatus,
		&i.SessionFailureReason,
		&i.Archived,
		&i.SandboxStatus,
		&i.ObservedAt,
		&i.TurnCounts,
		&i.InFlightTurnID,
		&i.InFlightTurnStatus,
		&i.InFlightDispatchedAt,
		&i.LastRunTurnID,
		&i.LastRunStatus,
		&i.LastRunCompletedAt,
		&i.NewestTurnID,
		&i.AwaitingPlanID,
		&i.AwaitingPlanSince,
		&i.AwaitingStepID,
		&i.AwaitingStepSince,
		&i.EscalatedRunID,
		&i.EscalatedRunSince,
	)
	return i, err
}

const getSessionActorEpochForUpdate = `-- name: GetSessionActorEpochForUpdate :one
SELECT actor_epoch FROM sessions
WHERE id = $1
FOR UPDATE
`

// Locks and reads a session's current actor_epoch. Called at the START of
// every transactional write, inside that same transaction, to fence a
// stale writer (an actor whose epoch no longer matches -- proof a newer
// actor has since taken over) before it does anything else (§2: "writes
// with a stale epoch fail").
func (q *Queries) GetSessionActorEpochForUpdate(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getSessionActorEpochForUpdate, id)
	var actor_epoch int64
	err := row.Scan(&actor_epoch)
	return actor_epoch, err
}

const listFailedSessions = `-- name: ListFailedSessions :many
SELECT id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id, parent_session_id, spawn_depth, build_effort, epistemic_check_enabled FROM sessions
WHERE status = 'failed' AND NOT archived
ORDER BY updated_at DESC
LIMIT $1
`

// §16 ("decision inbox: read model + API", §16.1)'s own
// needs_attention row source: every session currently 'failed' -- §3.2's
// own resume/recreate lanes make every failed session resume-eligible in
// SOME form (recreate-from-scratch at minimum, via conversation replay --
// see internal/app/decisioninbox's own doc comment for why this Step does
// not further narrow "resume available" beyond the status itself, since
// no additional per-provider capability signal is available at this read-
// model layer). Most-recently-failed first (updated_at -- set to now() by
// UpdateSessionStatus at the exact moment a session's own status last
// changed, which for an unarchived, still-'failed' row is the instant it
// became failed), bounded by $1 (§21.1's own "bounded from day one"
// discipline -- never an unbounded scan).
//
// ADMIN-ONLY at the RBAC/httpapi layer (§16.1's own parenthetical) -- this
// query itself carries no per-user filter: an admin's own ops-triage view
// is system-wide, not narrowed to sessions they personally created.
func (q *Queries) ListFailedSessions(ctx context.Context, limit int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, listFailedSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.FailureReason,
			&i.Archived,
			&i.SpawnSource,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActorEpoch,
			&i.Repos,
			&i.OpencodeConversationID,
			&i.EnvironmentID,
			&i.ProvenanceTag,
			&i.IntentDecision,
			&i.BuildModelID,
			&i.ParentSessionID,
			&i.SpawnDepth,
			&i.BuildEffort,
			&i.EpistemicCheckEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionOutcomeCountsInWindow = `-- name: ListSessionOutcomeCountsInWindow :many
SELECT
    (date_trunc('day', created_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC')::timestamptz AS day,
    status,
    failure_reason,
    COUNT(*) AS session_count
FROM sessions
WHERE created_at >= $1
GROUP BY (date_trunc('day', created_at AT TIME ZONE 'UTC') AT TIME ZONE 'UTC')::timestamptz, status, failure_reason
ORDER BY day
`

type ListSessionOutcomeCountsInWindowRow struct {
	Day           pgtype.Timestamptz    `json:"day"`
	Status        SessionStatus         `json:"status"`
	FailureReason *SessionFailureReason `json:"failure_reason"`
	SessionCount  int64                 `json:"session_count"`
}

// §12.2 item 6's own platform-wide analytics rollup: the ONE
// Postgres read behind FOUR distinct reductions internal/domain/
// platformanalytics performs over its rows (mirrors internal/domain/
// reviewverdict.ListRecordsSince's own "one fetch, several pure
// reductions" precedent) -- the "Sessions" KPI tile (sum of every
// session_count row), "success rate" (completed vs completed+failed),
// "sessions per day by outcome" chart (grouped by day+status), and "top
// failure reasons" chart (grouped by failure_reason, for status IN
// (failed, cancelled)).
//
// A GROUP BY reduction, deliberately NOT a bounded raw-row fetch like
// ListRecentlyDecided/ListRecordsSince use for their own, inherently
// narrower (per-repo or per-window-of-decisions) scopes: this rollup is
// explicitly platform-wide (every repo, every session), so its own true
// row count has no natural per-entity bound the way a repo-scoped fetch
// does, and an arbitrary LIMIT here would silently UNDERCOUNT the
// "Sessions" tile the moment a real deployment's window exceeds it --
// the exact kind of quietly-wrong number this Step exists to replace, not
// reintroduce. Aggregating in Postgres instead keeps the RESULT set
// small (at most a handful of days x 5 statuses x 5 failure reasons)
// regardless of how many session rows the window actually contains.
//
// day is truncated to UTC calendar day (date_trunc(...) AT TIME ZONE
// 'UTC', converting back to a real timestamptz at UTC midnight) --
// mirrors internal/domain/reviewverdict's own truncateToUTCDay, done here
// in SQL rather than Go specifically because the day dimension IS the
// GROUP BY key (unlike reviewverdict's own Go-side truncation over an
// already-fetched, small, repo-scoped row set).
//
// Bounded by sessions_created_at_idx (migrations/
// 000125_platform_analytics_indexes.up.sql) -- $1 is the window's own
// start (platform.Timeouts.PlatformAnalyticsWindow), never an unbounded
// scan.
func (q *Queries) ListSessionOutcomeCountsInWindow(ctx context.Context, createdAt pgtype.Timestamptz) ([]ListSessionOutcomeCountsInWindowRow, error) {
	rows, err := q.db.Query(ctx, listSessionOutcomeCountsInWindow, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionOutcomeCountsInWindowRow
	for rows.Next() {
		var i ListSessionOutcomeCountsInWindowRow
		if err := rows.Scan(
			&i.Day,
			&i.Status,
			&i.FailureReason,
			&i.SessionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id, s.title, s.status, s.failure_reason, s.archived, s.spawn_source, s.created_by, s.created_at, s.updated_at, s.actor_epoch, s.repos, s.opencode_conversation_id, s.environment_id, s.provenance_tag, s.intent_decision, s.build_model_id, s.parent_session_id, s.spawn_depth, s.build_effort, s.epistemic_check_enabled, sb.status AS sandbox_status FROM sessions s
LEFT JOIN sandboxes sb ON sb.session_id = s.id
WHERE NOT s.archived
  AND (
    NOT $1::boolean
    OR s.created_by = $2
    OR EXISTS (SELECT 1 FROM participants p WHERE p.session_id = s.id AND p.user_id = $2)
  )
ORDER BY s.updated_at DESC, s.id DESC
LIMIT $3
`

type ListSessionsParams struct {
	MineOnly bool        `json:"mine_only"`
	UserID   pgtype.UUID `json:"user_id"`
	RowLimit int32       `json:"row_limit"`
}

type ListSessionsRow struct {
	Session       Session        `json:"session"`
	SandboxStatus *SandboxStatus `json:"sandbox_status"`
}

// Backs GET /api/sessions (§6.3/§12.2 item 1's own sidebar addition --
// no general session-list route existed before this;
// ListFailedSessions immediately above is a narrower, admin-only,
// single-status read model, not this). mine_only implements §12.2 item
// 1's own "'My sessions' = created or joined" definition exactly:
// created_by = user_id OR a participants row exists for (session, user) --
// false returns every unarchived session system-wide, mirroring
// ListFailedSessions' own "no per-user filter, gated at the httpapi layer
// instead" precedent, since this codebase has no per-session RBAC/
// visibility concept today (httpapi/doc.go's own "every route ... 401
// before reaching any handler, nothing narrower"). sb.status is LEFT
// JOINed, never INNER -- a session with no sandbox row yet (status=
// 'created', never dispatched, or long since torn down) reads back
// NULL/Invalid here, never a fabricated default state; sandboxes.
// UNIQUE(session_id) (migrations/000006_sandboxes.up.sql) guarantees this
// join can add at most one row per session, never fan it out. Most-
// recently-updated first, id DESC as a tiebreaker for rows sharing the
// same updated_at (e.g. a batch of sessions created in the same
// transaction), bounded by $2 -- no cursor pagination in this first cut
// (see ListSessionsResponse's own schema doc comment for why).
func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.MineOnly, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsRow
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.Session.ID,
			&i.Session.Title,
			&i.Session.Status,
			&i.Session.FailureReason,
			&i.Session.Archived,
			&i.Session.SpawnSource,
			&i.Session.CreatedBy,
			&i.Session.CreatedAt,
			&i.Session.UpdatedAt,
			&i.Session.ActorEpoch,
			&i.Session.Repos,
			&i.Session.OpencodeConversationID,
			&i.Session.EnvironmentID,
			&i.Session.ProvenanceTag,
			&i.Session.IntentDecision,
			&i.Session.BuildModelID,
			&i.Session.ParentSessionID,
			&i.Session.SpawnDepth,
			&i.Session.BuildEffort,
			&i.Session.EpistemicCheckEnabled,
			&i.SandboxStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionConversationID = `-- name: UpdateSessionConversationID :one
UPDATE sessions
SET opencode_conversation_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id, parent_session_id, spawn_depth, build_effort, epistemic_check_enabled
`

type UpdateSessionConversationIDParams struct {
	ID                     pgtype.UUID `json:"id"`
	OpencodeConversationID *string     `json:"opencode_conversation_id"`
}

// Persists the session-level OpenCode conversation id (§3.3: "recorded at
// turn start ... also reported on every heartbeat"; see
// migrations/000018_session_repos.up.sql's own doc comment for why this is
// session-scoped, not turns.conversation_id). Called by
// internal/app/sessionactor's handleSandboxEvent whenever a "heartbeat"
// event carries a non-nil ConversationId.
func (q *Queries) UpdateSessionConversationID(ctx context.Context, arg UpdateSessionConversationIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionConversationID, arg.ID, arg.OpencodeConversationID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
		&i.ParentSessionID,
		&i.SpawnDepth,
		&i.BuildEffort,
		&i.EpistemicCheckEnabled,
	)
	return i, err
}

const updateSessionIntentDecisionIfNull = `-- name: UpdateSessionIntentDecisionIfNull :execrows
UPDATE sessions
SET intent_decision = $2
WHERE id = $1 AND intent_decision IS NULL
`

type UpdateSessionIntentDecisionIfNullParams struct {
	ID             pgtype.UUID `json:"id"`
	IntentDecision []byte      `json:"intent_decision"`
}

// §8.3's ("intent classifier", §18.4) write-once guarded update:
// "UPDATE sessions SET intent_decision = ... WHERE intent_decision IS
// NULL" -- NOT read-then-write, first decision wins, no application-level
// lock needed. RowsAffected (via :execrows) is the caller's own win/lose
// signal: 1 means THIS call actually set intent_decision (first writer
// wins); 0 means some other writer already set it first -- internal/app/
// intentclassifier's persistence path treats either outcome as success,
// never an error, since "someone already recorded a decision for this
// session" is exactly the expected, race-safe steady state, not a
// failure.
func (q *Queries) UpdateSessionIntentDecisionIfNull(ctx context.Context, arg UpdateSessionIntentDecisionIfNullParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSessionIntentDecisionIfNull, arg.ID, arg.IntentDecision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :one
UPDATE sessions
SET status = $2, failure_reason = $3, updated_at = now()
WHERE id = $1
RETURNING id, title, status, failure_reason, archived, spawn_source, created_by, created_at, updated_at, actor_epoch, repos, opencode_conversation_id, environment_id, provenance_tag, intent_decision, build_model_id, parent_session_id, spawn_depth, build_effort, epistemic_check_enabled
`

type UpdateSessionStatusParams struct {
	ID            pgtype.UUID           `json:"id"`
	Status        SessionStatus         `json:"status"`
	FailureReason *SessionFailureReason `json:"failure_reason"`
}

// Persists a session's derived status + failure_reason --
// internal/domain/session.DeriveStatus's output, never written directly
// (§11: "every state transition goes through the machine's transition
// table").
func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (Session, error) {
	row := q.db.QueryRow(ctx, updateSessionStatus, arg.ID, arg.Status, arg.FailureReason)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.FailureReason,
		&i.Archived,
		&i.SpawnSource,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ActorEpoch,
		&i.Repos,
		&i.OpencodeConversationID,
		&i.EnvironmentID,
		&i.ProvenanceTag,
		&i.IntentDecision,
		&i.BuildModelID,
		&i.ParentSessionID,
		&i.SpawnDepth,
		&i.BuildEffort,
		&i.EpistemicCheckEnabled,
	)
	return i, err
}
