// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachTurnToWorkflowStepRun = `-- name: AttachTurnToWorkflowStepRun :exec
UPDATE workflow_step_runs SET turn_id = $2, updated_at = now() WHERE id = $1
`

type AttachTurnToWorkflowStepRunParams struct {
	ID     pgtype.UUID `json:"id"`
	TurnID pgtype.UUID `json:"turn_id"`
}

func (q *Queries) AttachTurnToWorkflowStepRun(ctx context.Context, arg AttachTurnToWorkflowStepRunParams) error {
	_, err := q.db.Exec(ctx, attachTurnToWorkflowStepRun, arg.ID, arg.TurnID)
	return err
}

const cancelWorkflowRun = `-- name: CancelWorkflowRun :one
UPDATE workflow_runs SET status = 'cancelled', finished_at = now(), updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

// Technical plan §3.3's stop: an attempt whose turn a person's stop
// cancelled ends its run here, terminal like FailWorkflowRun, and
// workflow.NextStep is never consulted -- a custom definition's edge on
// 'blocked' would otherwise queue the next step, and the stop would not
// stop.
func (q *Queries) CancelWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, cancelWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const claimWorkflowRunEscalationNotice = `-- name: ClaimWorkflowRunEscalationNotice :execrows
UPDATE workflow_runs SET needs_review_notified_at = now(), updated_at = now() WHERE id = $1 AND needs_review_notified_at IS NULL
`

// The §25.9/§24.6-mirroring "one notice, never repeated" claim
// (migrations/000058_workflow_hitl.up.sql's own doc comment): guarded on
// needs_review_notified_at IS NULL, so of any number of concurrent/
// repeated attempts to escalate the SAME run, exactly one ever claims the
// right to enqueue the notice -- :execrows lets the caller tell "I claimed
// it, send the notice" (1) from "already claimed/sent by an earlier
// escalation" (0) apart, without a separate existence check.
func (q *Queries) ClaimWorkflowRunEscalationNotice(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimWorkflowRunEscalationNotice, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeWorkflowRun = `-- name: CompleteWorkflowRun :one
UPDATE workflow_runs SET status = 'completed', finished_at = now(), updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

func (q *Queries) CompleteWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, completeWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const countWorkflowStepRunsForStepDefinition = `-- name: CountWorkflowStepRunsForStepDefinition :one
SELECT COUNT(*) FROM workflow_step_runs WHERE workflow_run_id = $1 AND step_definition_id = $2
`

type CountWorkflowStepRunsForStepDefinitionParams struct {
	WorkflowRunID    pgtype.UUID `json:"workflow_run_id"`
	StepDefinitionID pgtype.UUID `json:"step_definition_id"`
}

// §25.5's own "iteration count reads COUNT(*) on workflow_step_runs, no
// dedicated counter column" -- scoped to ONE run (a count is never summed
// across a session's separate runs) and ONE step definition (the step
// about to receive a new attempt). The engine consults this ONLY when a
// needs_fix edge is about to advance to a step that might already have
// prior attempts in THIS run -- see internal/app/workflowengine's own
// advance.go for the exact call site and the "count > 0 means a genuine
// re-fire" reasoning.
func (q *Queries) CountWorkflowStepRunsForStepDefinition(ctx context.Context, arg CountWorkflowStepRunsForStepDefinitionParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowStepRunsForStepDefinition, arg.WorkflowRunID, arg.StepDefinitionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflowDefinition = `-- name: CreateWorkflowDefinition :one
INSERT INTO workflow_definitions (lane, name, is_built_in, version)
VALUES ($1, $2, false, 1)
RETURNING id, lane, name, is_built_in, version, created_at, updated_at
`

type CreateWorkflowDefinitionParams struct {
	Lane WorkflowLane `json:"lane"`
	Name string       `json:"name"`
}

// is_built_in is hardcoded false: POST /api/workflow-definitions can
// never mint a built-in row (only migration 000057's own seed does).
// version is hardcoded 1: every freshly created or duplicated definition
// starts there (§25.10).
func (q *Queries) CreateWorkflowDefinition(ctx context.Context, arg CreateWorkflowDefinitionParams) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, createWorkflowDefinition, arg.Lane, arg.Name)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Name,
		&i.IsBuiltIn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowEdge = `-- name: CreateWorkflowEdge :one
INSERT INTO workflow_edges (workflow_definition_id, from_step_id, to_step_id, on_status)
VALUES ($1, $2, $3, $4)
RETURNING id, workflow_definition_id, from_step_id, to_step_id, on_status, created_at
`

type CreateWorkflowEdgeParams struct {
	WorkflowDefinitionID pgtype.UUID               `json:"workflow_definition_id"`
	FromStepID           pgtype.UUID               `json:"from_step_id"`
	ToStepID             pgtype.UUID               `json:"to_step_id"`
	OnStatus             WorkflowStepOutcomeStatus `json:"on_status"`
}

func (q *Queries) CreateWorkflowEdge(ctx context.Context, arg CreateWorkflowEdgeParams) (WorkflowEdge, error) {
	row := q.db.QueryRow(ctx, createWorkflowEdge,
		arg.WorkflowDefinitionID,
		arg.FromStepID,
		arg.ToStepID,
		arg.OnStatus,
	)
	var i WorkflowEdge
	err := row.Scan(
		&i.ID,
		&i.WorkflowDefinitionID,
		&i.FromStepID,
		&i.ToStepID,
		&i.OnStatus,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (session_id, lane, workflow_definition_id, definition_version)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

type CreateWorkflowRunParams struct {
	SessionID            pgtype.UUID  `json:"session_id"`
	Lane                 WorkflowLane `json:"lane"`
	WorkflowDefinitionID pgtype.UUID  `json:"workflow_definition_id"`
	DefinitionVersion    int32        `json:"definition_version"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.SessionID,
		arg.Lane,
		arg.WorkflowDefinitionID,
		arg.DefinitionVersion,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const createWorkflowStepDefinition = `-- name: CreateWorkflowStepDefinition :one
INSERT INTO workflow_step_definitions
    (id, workflow_definition_id, step_order, kind, model_id, effort, prompt_template, execution_scope, conversation_continuity, hitl_before, hitl_after, canvas_position)
VALUES
    ($1, $2, $3, 'agent', $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, workflow_definition_id, step_order, kind, model_id, prompt_template, execution_scope, conversation_continuity, hitl_before, hitl_after, canvas_position, created_at, updated_at, effort
`

type CreateWorkflowStepDefinitionParams struct {
	ID                     pgtype.UUID                    `json:"id"`
	WorkflowDefinitionID   pgtype.UUID                    `json:"workflow_definition_id"`
	StepOrder              int32                          `json:"step_order"`
	ModelID                *string                        `json:"model_id"`
	Effort                 *string                        `json:"effort"`
	PromptTemplate         string                         `json:"prompt_template"`
	ExecutionScope         WorkflowExecutionScope         `json:"execution_scope"`
	ConversationContinuity WorkflowConversationContinuity `json:"conversation_continuity"`
	HitlBefore             bool                           `json:"hitl_before"`
	HitlAfter              bool                           `json:"hitl_after"`
	CanvasPosition         []byte                         `json:"canvas_position"`
}

func (q *Queries) CreateWorkflowStepDefinition(ctx context.Context, arg CreateWorkflowStepDefinitionParams) (WorkflowStepDefinition, error) {
	row := q.db.QueryRow(ctx, createWorkflowStepDefinition,
		arg.ID,
		arg.WorkflowDefinitionID,
		arg.StepOrder,
		arg.ModelID,
		arg.Effort,
		arg.PromptTemplate,
		arg.ExecutionScope,
		arg.ConversationContinuity,
		arg.HitlBefore,
		arg.HitlAfter,
		arg.CanvasPosition,
	)
	var i WorkflowStepDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkflowDefinitionID,
		&i.StepOrder,
		&i.Kind,
		&i.ModelID,
		&i.PromptTemplate,
		&i.ExecutionScope,
		&i.ConversationContinuity,
		&i.HitlBefore,
		&i.HitlAfter,
		&i.CanvasPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Effort,
	)
	return i, err
}

const createWorkflowStepRun = `-- name: CreateWorkflowStepRun :one
INSERT INTO workflow_step_runs (workflow_run_id, step_definition_id)
VALUES ($1, $2)
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type CreateWorkflowStepRunParams struct {
	WorkflowRunID    pgtype.UUID `json:"workflow_run_id"`
	StepDefinitionID pgtype.UUID `json:"step_definition_id"`
}

func (q *Queries) CreateWorkflowStepRun(ctx context.Context, arg CreateWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowStepRun, arg.WorkflowRunID, arg.StepDefinitionID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const decideWorkflowStepRunApprove = `-- name: DecideWorkflowStepRunApprove :execrows

UPDATE workflow_step_runs
SET status = 'completed', decision = 'approve', decision_text = $2, decided_at = now(), decided_by = $3, finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'awaiting_decision'
`

type DecideWorkflowStepRunApproveParams struct {
	ID           pgtype.UUID `json:"id"`
	DecisionText *string     `json:"decision_text"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
}

// DecideWorkflowStepRunApprove/Reject/Revise are three narrow,
// single-purpose guarded UPDATEs -- mirroring plans.sql's own
// ApprovePlanIfAwaitingApproval/RejectPlanIfAwaitingApproval precedent
// (two verdicts, two statements) exactly, extended to three here so which
// resulting status/decision applies to which verdict is enforced by WHICH
// STATEMENT RUNS, never by a conditional expression a future edit could
// silently get wrong (this file's own header comment states this
// discipline for MarkWorkflowStepRunAwaitingDecision/FinishWorkflowStepRun
// above; the same reasoning applies here). All three share the identical
// "AND status = 'awaiting_decision'" guard -- :execrows lets the handler
// distinguish "this call won the decision" from "already decided (or a
// stale id)" without a separate existence check, exactly like
// ApprovePlanIfAwaitingApproval's own :execrows shape. decisionText ($2)
// is nullable: NULL for approve (ignored), optional context for reject,
// required non-empty for revise (enforced at the application layer, per
// WorkflowStepDecideRequest.text's own schema doc comment).
//
// Resulting status: approve/revise both land on 'completed' (the
// attempt's own execution genuinely finished either way -- what happens
// NEXT, advance vs re-execute, is the decision column's own job, not the
// status column's); reject lands on 'failed', mirroring
// WorkflowStepDecideResponse.runStatus's own documented "'failed' after a
// winning reject ends the run" example -- the owning run's and the
// decided attempt's own resulting status agree by construction.
func (q *Queries) DecideWorkflowStepRunApprove(ctx context.Context, arg DecideWorkflowStepRunApproveParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideWorkflowStepRunApprove, arg.ID, arg.DecisionText, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decideWorkflowStepRunReject = `-- name: DecideWorkflowStepRunReject :execrows
UPDATE workflow_step_runs
SET status = 'failed', decision = 'reject', decision_text = $2, decided_at = now(), decided_by = $3, finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'awaiting_decision'
`

type DecideWorkflowStepRunRejectParams struct {
	ID           pgtype.UUID `json:"id"`
	DecisionText *string     `json:"decision_text"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
}

func (q *Queries) DecideWorkflowStepRunReject(ctx context.Context, arg DecideWorkflowStepRunRejectParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideWorkflowStepRunReject, arg.ID, arg.DecisionText, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const decideWorkflowStepRunRevise = `-- name: DecideWorkflowStepRunRevise :execrows
UPDATE workflow_step_runs
SET status = 'completed', decision = 'revise', decision_text = $2, decided_at = now(), decided_by = $3, finished_at = now(), updated_at = now()
WHERE id = $1 AND status = 'awaiting_decision'
`

type DecideWorkflowStepRunReviseParams struct {
	ID           pgtype.UUID `json:"id"`
	DecisionText *string     `json:"decision_text"`
	DecidedBy    pgtype.UUID `json:"decided_by"`
}

func (q *Queries) DecideWorkflowStepRunRevise(ctx context.Context, arg DecideWorkflowStepRunReviseParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideWorkflowStepRunRevise, arg.ID, arg.DecisionText, arg.DecidedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflowDefinition = `-- name: DeleteWorkflowDefinition :execrows
DELETE FROM workflow_definitions WHERE id = $1
`

func (q *Queries) DeleteWorkflowDefinition(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkflowDefinition, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkflowStepDefinitionsForDefinition = `-- name: DeleteWorkflowStepDefinitionsForDefinition :exec
DELETE FROM workflow_step_definitions WHERE workflow_definition_id = $1
`

func (q *Queries) DeleteWorkflowStepDefinitionsForDefinition(ctx context.Context, workflowDefinitionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkflowStepDefinitionsForDefinition, workflowDefinitionID)
	return err
}

const duplicateWorkflowStepDefinition = `-- name: DuplicateWorkflowStepDefinition :one
INSERT INTO workflow_step_definitions
    (workflow_definition_id, step_order, kind, model_id, effort, prompt_template, execution_scope, conversation_continuity, hitl_before, hitl_after, canvas_position)
VALUES
    ($1, $2, 'agent', $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workflow_definition_id, step_order, kind, model_id, prompt_template, execution_scope, conversation_continuity, hitl_before, hitl_after, canvas_position, created_at, updated_at, effort
`

type DuplicateWorkflowStepDefinitionParams struct {
	WorkflowDefinitionID   pgtype.UUID                    `json:"workflow_definition_id"`
	StepOrder              int32                          `json:"step_order"`
	ModelID                *string                        `json:"model_id"`
	Effort                 *string                        `json:"effort"`
	PromptTemplate         string                         `json:"prompt_template"`
	ExecutionScope         WorkflowExecutionScope         `json:"execution_scope"`
	ConversationContinuity WorkflowConversationContinuity `json:"conversation_continuity"`
	HitlBefore             bool                           `json:"hitl_before"`
	HitlAfter              bool                           `json:"hitl_after"`
	CanvasPosition         []byte                         `json:"canvas_position"`
}

func (q *Queries) DuplicateWorkflowStepDefinition(ctx context.Context, arg DuplicateWorkflowStepDefinitionParams) (WorkflowStepDefinition, error) {
	row := q.db.QueryRow(ctx, duplicateWorkflowStepDefinition,
		arg.WorkflowDefinitionID,
		arg.StepOrder,
		arg.ModelID,
		arg.Effort,
		arg.PromptTemplate,
		arg.ExecutionScope,
		arg.ConversationContinuity,
		arg.HitlBefore,
		arg.HitlAfter,
		arg.CanvasPosition,
	)
	var i WorkflowStepDefinition
	err := row.Scan(
		&i.ID,
		&i.WorkflowDefinitionID,
		&i.StepOrder,
		&i.Kind,
		&i.ModelID,
		&i.PromptTemplate,
		&i.ExecutionScope,
		&i.ConversationContinuity,
		&i.HitlBefore,
		&i.HitlAfter,
		&i.CanvasPosition,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Effort,
	)
	return i, err
}

const escalateWorkflowRun = `-- name: EscalateWorkflowRun :one
UPDATE workflow_runs SET status = 'needs_review', updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

func (q *Queries) EscalateWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, escalateWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const existsWorkflowBindingForDefinition = `-- name: ExistsWorkflowBindingForDefinition :one
SELECT EXISTS(SELECT 1 FROM workflow_bindings WHERE workflow_definition_id = $1)
`

func (q *Queries) ExistsWorkflowBindingForDefinition(ctx context.Context, workflowDefinitionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsWorkflowBindingForDefinition, workflowDefinitionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsWorkflowRunForDefinition = `-- name: ExistsWorkflowRunForDefinition :one
SELECT EXISTS(SELECT 1 FROM workflow_runs WHERE workflow_definition_id = $1)
`

func (q *Queries) ExistsWorkflowRunForDefinition(ctx context.Context, workflowDefinitionID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsWorkflowRunForDefinition, workflowDefinitionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const failWorkflowRun = `-- name: FailWorkflowRun :one
UPDATE workflow_runs SET status = 'failed', finished_at = now(), updated_at = now() WHERE id = $1 RETURNING id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at
`

// §25.9's own addition (§25.9): a winning HITL reject verdict ends the
// run -- mirrors CompleteWorkflowRun's own shape exactly, landing on
// 'failed' instead of 'completed' (WorkflowStepDecideResponse.runStatus's
// own documented "'failed' after a winning reject ends the run" example).
// Terminal (finished_at set), unlike EscalateWorkflowRun's own
// 'needs_review' (non-terminal, waiting on a human) -- a reject is itself
// the human's own final word, nothing further to wait on.
func (q *Queries) FailWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, failWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const finishWorkflowStepRun = `-- name: FinishWorkflowStepRun :one
UPDATE workflow_step_runs
SET status = $2, outcome_status = COALESCE(outcome_status, $3), finished_at = now(), updated_at = now()
WHERE id = $1
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type FinishWorkflowStepRunParams struct {
	ID            pgtype.UUID                `json:"id"`
	Status        WorkflowStepRunStatus      `json:"status"`
	OutcomeStatus *WorkflowStepOutcomeStatus `json:"outcome_status"`
}

// status is the caller-computed terminal workflow_step_run_status
// (completed/failed/cancelled -- never awaiting_decision, which
// MarkWorkflowStepRunAwaitingDecision above owns exclusively).
func (q *Queries) FinishWorkflowStepRun(ctx context.Context, arg FinishWorkflowStepRunParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, finishWorkflowStepRun, arg.ID, arg.Status, arg.OutcomeStatus)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGlobalWorkflowBinding = `-- name: GetGlobalWorkflowBinding :one
SELECT id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at FROM workflow_bindings WHERE lane = $1 AND repo_full_name IS NULL
`

func (q *Queries) GetGlobalWorkflowBinding(ctx context.Context, lane WorkflowLane) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, getGlobalWorkflowBinding, lane)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLiveWorkflowStepRunByTurnID = `-- name: GetLiveWorkflowStepRunByTurnID :one
SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs WHERE turn_id = $1 AND status = 'running'
`

func (q *Queries) GetLiveWorkflowStepRunByTurnID(ctx context.Context, turnID pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getLiveWorkflowStepRunByTurnID, turnID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLiveWorkflowStepRunForRun = `-- name: GetLiveWorkflowStepRunForRun :one
SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs
WHERE workflow_run_id = $1 AND status IN ('running', 'awaiting_decision')
`

func (q *Queries) GetLiveWorkflowStepRunForRun(ctx context.Context, workflowRunID pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getLiveWorkflowStepRunForRun, workflowRunID)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunningWorkflowRunForSession = `-- name: GetRunningWorkflowRunForSession :one
SELECT id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at FROM workflow_runs WHERE session_id = $1 AND status = 'running'
`

func (q *Queries) GetRunningWorkflowRunForSession(ctx context.Context, sessionID pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getRunningWorkflowRunForSession, sessionID)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const getWorkflowBindingForRepo = `-- name: GetWorkflowBindingForRepo :one

SELECT id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at FROM workflow_bindings WHERE lane = $1 AND repo_full_name = $2
`

type GetWorkflowBindingForRepoParams struct {
	Lane         WorkflowLane `json:"lane"`
	RepoFullName *string      `json:"repo_full_name"`
}

// Queries backing WorkflowStore ("workflow execution engine",
// §25.6/§25.7/§25.8), the first real reader/writer of §25.4's own dark
// schema (migrations/000057_workflows.up.sql). internal/app/workflowengine
// is this file's only caller: it resolves which (lane, repo) binding and
// WorkflowDefinition govern a session's current turn, tracks the run/
// step-run ledger these queries persist, and consults
// internal/domain/workflow.NextStep on every posted/derived step outcome
// -- never reimplementing that decision here.
//
// Binding resolution (§25.4): a repo-specific row (GetWorkflowBindingForRepo)
// always wins when one exists; GetGlobalWorkflowBinding is the guaranteed
// fallback (seeded by migration 000057 for every lane, so this SELECT is
// never truly expected to return zero rows in a correctly-migrated
// database -- see workflowengine's own fail-open handling for the
// defensive case where it somehow does).
//
// Definition assembly (GetWorkflowDefinition + ListWorkflowStepDefinitions +
// ListWorkflowEdgesForDefinition): three queries, not one join, mirroring
// domain/workflow.Definition's own shape (a definition row plus its
// ordered steps, each carrying its own outgoing edges) -- workflowengine
// groups edges by from_step_id in Go when assembling the domain value, the
// same "read plain rows, assemble the domain type in the app layer" split
// every other store in this package already follows (e.g. PlanStore never
// constructs an internal/domain/plan value itself).
//
// Run/step-run lifecycle (§25.6, migration 000057's own header comment):
// GetRunningWorkflowRunForSession/GetLiveWorkflowStepRunForRun back the
// "is there already a live run/step for this session" check
// ResolveStepForNewTurn makes before ever starting a new run --
// workflow_runs_one_running_per_session/workflow_step_runs_one_live_per_run
// (migration 000057) make violating either a live constraint violation,
// not just an application bug; this store's own CreateWorkflowRun/
// CreateWorkflowStepRun are therefore only ever called from the branch that
// already confirmed no live one exists. AttachTurnToWorkflowStepRun
// backfills turn_id once the actual turn row exists (it cannot exist before
// the step-run row is created, since ResolveStepForNewTurn must decide the
// step BEFORE the turn insert it feeds prompt/model into) --
// GetLiveWorkflowStepRunByTurnID is completion.go's own reverse lookup, at
// turn-completion time.
//
// MarkWorkflowStepRunAwaitingDecision/FinishWorkflowStepRun/
// CompleteWorkflowRun/EscalateWorkflowRun are deliberately four narrow,
// single-purpose statements rather than one CASE-parameterized UPDATE each
// -- mirroring plans.sql's own ApprovePlanIfAwaitingApproval/
// RejectPlanIfAwaitingApproval precedent (two verdicts, two statements) --
// so finished_at's own "null while awaiting_decision" invariant
// (migration 000057's own doc comment) is enforced by which statement runs,
// never by a conditional expression a future edit could silently get wrong.
// outcome_status uses COALESCE in both step-run UPDATEs so an outcome
// ALREADY posted via the step-outcome tool (SetWorkflowStepRunOutcome
// below) is never clobbered by the engine's own implicit-from-trigger
// derivation at turn-completion time -- the posted value always wins.
//
// SetWorkflowStepRunOutcome is the generic step-outcome-posting tool's own
// write (§25.6's typed {status, summary, structuredPayload} handoff,
// structurally mirroring internal/domain/reviewpost's existing
// verdict-posting shape): guarded to "AND status = 'running'" so a caller
// can only ever post onto the attempt currently actually in flight, never
// an already-finished or awaiting-decision one -- :execrows lets the
// handler distinguish "posted" from "no live attempt to post onto" without
// a separate existence check.
func (q *Queries) GetWorkflowBindingForRepo(ctx context.Context, arg GetWorkflowBindingForRepoParams) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, getWorkflowBindingForRepo, arg.Lane, arg.RepoFullName)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowDefinition = `-- name: GetWorkflowDefinition :one
SELECT id, lane, name, is_built_in, version, created_at, updated_at FROM workflow_definitions WHERE id = $1
`

func (q *Queries) GetWorkflowDefinition(ctx context.Context, id pgtype.UUID) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinition, id)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Name,
		&i.IsBuiltIn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowDefinitionWithRefusalFacts = `-- name: GetWorkflowDefinitionWithRefusalFacts :one
SELECT
    d.id, d.lane, d.name, d.is_built_in, d.version, d.created_at, d.updated_at,
    EXISTS (SELECT 1 FROM workflow_bindings b WHERE b.workflow_definition_id = d.id) AS is_bound,
    EXISTS (SELECT 1 FROM workflow_runs r WHERE r.workflow_definition_id = d.id) AS has_runs
FROM workflow_definitions d
WHERE d.id = $1
`

type GetWorkflowDefinitionWithRefusalFactsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Lane      WorkflowLane       `json:"lane"`
	Name      string             `json:"name"`
	IsBuiltIn bool               `json:"is_built_in"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IsBound   bool               `json:"is_bound"`
	HasRuns   bool               `json:"has_runs"`
}

// GetWorkflowDefinition's own shape plus the same two EXISTS -- see
// ListWorkflowDefinitions above for why they travel with the row.
func (q *Queries) GetWorkflowDefinitionWithRefusalFacts(ctx context.Context, id pgtype.UUID) (GetWorkflowDefinitionWithRefusalFactsRow, error) {
	row := q.db.QueryRow(ctx, getWorkflowDefinitionWithRefusalFacts, id)
	var i GetWorkflowDefinitionWithRefusalFactsRow
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Name,
		&i.IsBuiltIn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsBound,
		&i.HasRuns,
	)
	return i, err
}

const getWorkflowRun = `-- name: GetWorkflowRun :one
SELECT id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at FROM workflow_runs WHERE id = $1
`

func (q *Queries) GetWorkflowRun(ctx context.Context, id pgtype.UUID) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Lane,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
		&i.NeedsReviewNotifiedAt,
	)
	return i, err
}

const getWorkflowStepRun = `-- name: GetWorkflowStepRun :one

SELECT id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at FROM workflow_step_runs WHERE id = $1
`

// §25.9 ("workflow HITL gate + circuit breaker", §25.9) own additions
// below: the decide endpoint's lookup/guarded-decision queries, the
// circuit breaker's own COUNT(*) attempt read (§25.5), and the escalation
// notice's one-time claim (migrations/000058_workflow_hitl.up.sql).
// Plain lookup by id -- the decide endpoint's own first read (mirrors
// plans.Get's identical role in decideplan.go): used both to resolve the
// target attempt before deciding it and, after the guarded UPDATE below,
// to re-fetch its REAL current state either way (won or already decided),
// exactly like DecidePlanOnTx's own plans.Get re-fetch.
func (q *Queries) GetWorkflowStepRun(ctx context.Context, id pgtype.UUID) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowStepRun, id)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listWorkflowBindings = `-- name: ListWorkflowBindings :many
SELECT id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at FROM workflow_bindings ORDER BY lane, repo_full_name NULLS FIRST
`

func (q *Queries) ListWorkflowBindings(ctx context.Context) ([]WorkflowBinding, error) {
	rows, err := q.db.Query(ctx, listWorkflowBindings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowBinding
	for rows.Next() {
		var i WorkflowBinding
		if err := rows.Scan(
			&i.ID,
			&i.Lane,
			&i.RepoFullName,
			&i.WorkflowDefinitionID,
			&i.DefinitionVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowDefinitions = `-- name: ListWorkflowDefinitions :many

SELECT
    d.id, d.lane, d.name, d.is_built_in, d.version, d.created_at, d.updated_at,
    EXISTS (SELECT 1 FROM workflow_bindings b WHERE b.workflow_definition_id = d.id) AS is_bound,
    EXISTS (SELECT 1 FROM workflow_runs r WHERE r.workflow_definition_id = d.id) AS has_runs
FROM workflow_definitions d
ORDER BY d.lane, d.name
`

type ListWorkflowDefinitionsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Lane      WorkflowLane       `json:"lane"`
	Name      string             `json:"name"`
	IsBuiltIn bool               `json:"is_built_in"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IsBound   bool               `json:"is_bound"`
	HasRuns   bool               `json:"has_runs"`
}

// ---------------------------------------------------------------------
// "workflow definition & run API" (§25.10/§25.11) own additions below:
// the definition/binding CRUD + duplicate surface, and
// the two run-history list reads (session's own runs; one run's own
// ordered step runs) the run view needs and no query above provides.
//
// Definition writes (Create/Update/Delete + the two step-insert
// variants + CreateWorkflowEdge) are always driven from a WithTx store
// (§25.10: "The PUT is therefore a single transaction"): DeleteWorkflow
// StepDefinitionsForDefinition relies on workflow_edges' own ON DELETE
// CASCADE from workflow_step_definitions (migration 000057) to clear a
// definition's old graph in one statement, never hand-diffed, and the
// caller re-inserts the complete new graph in the SAME transaction.
//
// CreateWorkflowStepDefinition takes a CLIENT-SUPPLIED id ($1) -- every
// POST(whole-document)/PUT request body carries real step ids (a canvas editor's own
// locally-generated uuid for a brand-new node, or an existing step's own
// id echoed back), so edges within the SAME request body can reference a
// step that has never been persisted before. DuplicateWorkflowStepDefinition
// is the one exception: POST .../workflow-definitions' own
// {sourceDefinitionId, name} path deep-copies an existing definition, and
// every copied step must get a genuinely NEW id (the column's own
// gen_random_uuid() default) so the copy never collides with its source
// -- the caller remaps (source step id -> new step id) in Go to translate
// the source's own edges onto the copy. Both hardcode kind = 'agent',
// the only recognized workflow_step_kind value today
// (internal/domain/workflow.StepKindAgent).
//
// ExistsWorkflowBindingForDefinition is the "unbound draft" structural
// refusal's own read (§25.10/§25.11's amendment): PUT/DELETE both check
// this BEFORE touching a definition's rows at all. ExistsWorkflowRunForDefinition
// is a THIRD guard this Step adds beyond the two §25.10/§25.11 name by
// word: workflow_runs.workflow_definition_id and workflow_step_runs.
// step_definition_id are both plain NO ACTION references (migration
// 000057: "history outlives configuration"), so a definition that has
// EVER run cannot have its steps deleted-and-reinserted (PUT) or the row
// itself deleted (DELETE) without a raw FK-violation 500 -- reachable
// even on a definition that is CURRENTLY unbound (rebinding a lane to a
// duplicate frees the old definition's own workflow_bindings row while
// its workflow_runs history remains behind). Refused with its own
// distinct message, the same "validate first, name which rule broke"
// discipline the other two guards already follow.
//
// UpsertGlobalWorkflowBinding/UpsertRepoWorkflowBinding mirror
// opencodeconfigs.sql's own UpsertEnvironmentOpenCodeConfig/
// UpsertGlobalOpenCodeConfig pair exactly -- see that file's own doc
// comment for why a value governed by two DIFFERENT partial unique
// indexes (workflow_bindings_global_uniq/workflow_bindings_repo_uniq,
// migration 000057) needs two separate upsert statements: Postgres's ON
// CONFLICT clause names exactly one arbiter index per statement, and a
// plain UNIQUE never matches on NULL, so a single "ON CONFLICT (lane,
// repo_full_name)" would silently INSERT a second global row instead of
// updating the first.
//
// ListWorkflowStepRunsForRun orders oldest-first by creation -- the
// chronological execution/re-attempt sequence (§25.10: "a run without
// its steps answers no question anybody asks"); each retry/revise
// re-execution is its own row, never an update-in-place (§25.5), so
// creation order IS execution order.
// Carries the two EXISTS a caller would otherwise have to derive itself, so
// §25.11's three edit refusals have ONE definition (refusalReasonForMutation,
// httpapi/workflowdefinitions.go) rather than a server copy and a client copy
// that drift. Computed in-query rather than per-row in Go: a list endpoint
// issuing two extra round trips per definition is the N+1 this avoids.
//
// The third refusal, run history, is the one a client could not derive AT ALL
// -- nothing about runs is on WorkflowDefinition's own wire shape -- so
// without this an editor only learns a definition is frozen by failing to
// save it, after the operator has already done the work.
func (q *Queries) ListWorkflowDefinitions(ctx context.Context) ([]ListWorkflowDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowDefinitions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowDefinitionsRow
	for rows.Next() {
		var i ListWorkflowDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Lane,
			&i.Name,
			&i.IsBuiltIn,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsBound,
			&i.HasRuns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowEdgesForDefinition = `-- name: ListWorkflowEdgesForDefinition :many
SELECT id, workflow_definition_id, from_step_id, to_step_id, on_status, created_at FROM workflow_edges WHERE workflow_definition_id = $1
`

func (q *Queries) ListWorkflowEdgesForDefinition(ctx context.Context, workflowDefinitionID pgtype.UUID) ([]WorkflowEdge, error) {
	rows, err := q.db.Query(ctx, listWorkflowEdgesForDefinition, workflowDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowEdge
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowDefinitionID,
			&i.FromStepID,
			&i.ToStepID,
			&i.OnStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowRunsForSession = `-- name: ListWorkflowRunsForSession :many
SELECT id, session_id, lane, workflow_definition_id, definition_version, status, created_at, updated_at, finished_at, needs_review_notified_at FROM workflow_runs WHERE session_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListWorkflowRunsForSession(ctx context.Context, sessionID pgtype.UUID) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRunsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Lane,
			&i.WorkflowDefinitionID,
			&i.DefinitionVersion,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.NeedsReviewNotifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepDefinitions = `-- name: ListWorkflowStepDefinitions :many
SELECT id, workflow_definition_id, step_order, kind, model_id, prompt_template, execution_scope, conversation_continuity, hitl_before, hitl_after, canvas_position, created_at, updated_at, effort FROM workflow_step_definitions WHERE workflow_definition_id = $1 ORDER BY step_order
`

func (q *Queries) ListWorkflowStepDefinitions(ctx context.Context, workflowDefinitionID pgtype.UUID) ([]WorkflowStepDefinition, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepDefinitions, workflowDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowStepDefinition
	for rows.Next() {
		var i WorkflowStepDefinition
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowDefinitionID,
			&i.StepOrder,
			&i.Kind,
			&i.ModelID,
			&i.PromptTemplate,
			&i.ExecutionScope,
			&i.ConversationContinuity,
			&i.HitlBefore,
			&i.HitlAfter,
			&i.CanvasPosition,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Effort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowStepRunsForRun = `-- name: ListWorkflowStepRunsForRun :many
SELECT
    sr.id, sr.workflow_run_id, sr.step_definition_id, sr.turn_id, sr.status, sr.outcome_status, sr.outcome_summary, sr.outcome_payload, sr.decision, sr.decision_text, sr.decided_at, sr.decided_by, sr.created_at, sr.updated_at, sr.finished_at,
    t.model_id AS turn_model_id,
    t.cost_usd AS turn_cost_usd
FROM workflow_step_runs sr
LEFT JOIN turns t ON t.id = sr.turn_id
WHERE sr.workflow_run_id = $1
ORDER BY sr.created_at ASC, sr.id ASC
`

type ListWorkflowStepRunsForRunRow struct {
	ID               pgtype.UUID                `json:"id"`
	WorkflowRunID    pgtype.UUID                `json:"workflow_run_id"`
	StepDefinitionID pgtype.UUID                `json:"step_definition_id"`
	TurnID           pgtype.UUID                `json:"turn_id"`
	Status           WorkflowStepRunStatus      `json:"status"`
	OutcomeStatus    *WorkflowStepOutcomeStatus `json:"outcome_status"`
	OutcomeSummary   *string                    `json:"outcome_summary"`
	OutcomePayload   []byte                     `json:"outcome_payload"`
	Decision         *WorkflowStepDecision      `json:"decision"`
	DecisionText     *string                    `json:"decision_text"`
	DecidedAt        pgtype.Timestamptz         `json:"decided_at"`
	DecidedBy        pgtype.UUID                `json:"decided_by"`
	CreatedAt        pgtype.Timestamptz         `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz         `json:"updated_at"`
	FinishedAt       pgtype.Timestamptz         `json:"finished_at"`
	TurnModelID      *string                    `json:"turn_model_id"`
	TurnCostUsd      pgtype.Numeric             `json:"turn_cost_usd"`
}

// §25.15: carries the two facts a run view needs that live on the
// ordinary turn each attempt dispatched as, not on workflow_step_runs
// itself -- turn_model_id (the join through turn_id that IS a step's
// model, turns.model_id, persisted since migration 000018; §25.6 makes
// every workflow step an ordinary sequential turn, so no new column was
// needed) and turn_cost_usd (turns.cost_usd, migration 000098's own
// running total, accumulated as this attempt's own step_finish events
// land). A LEFT JOIN, not INNER: turn_id is nullable (an
// awaiting_decision attempt has no turn yet), and a step run with no
// turn must still be listed, with both extra columns simply absent --
// mirrors ListWorkflowDefinitions' own "carries the extra columns a
// caller would otherwise have to derive itself... a list endpoint
// issuing extra round trips per row is the N+1 this avoids" reasoning
// exactly, one join away from an EXISTS subquery.
func (q *Queries) ListWorkflowStepRunsForRun(ctx context.Context, workflowRunID pgtype.UUID) ([]ListWorkflowStepRunsForRunRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowStepRunsForRun, workflowRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowStepRunsForRunRow
	for rows.Next() {
		var i ListWorkflowStepRunsForRunRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowRunID,
			&i.StepDefinitionID,
			&i.TurnID,
			&i.Status,
			&i.OutcomeStatus,
			&i.OutcomeSummary,
			&i.OutcomePayload,
			&i.Decision,
			&i.DecisionText,
			&i.DecidedAt,
			&i.DecidedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FinishedAt,
			&i.TurnModelID,
			&i.TurnCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkflowDefinitionForUpdate = `-- name: LockWorkflowDefinitionForUpdate :one
SELECT id, lane, name, is_built_in, version, created_at, updated_at FROM workflow_definitions WHERE id = $1 FOR UPDATE
`

// Row-level lock making §25.11's own "a bound definition is never edited"
// refusal actually hold, rather than hold only because callers happen not
// to interleave. Taken in the SAME transaction as the bound/run-history
// EXISTS checks and the step rewrite that follows them, and taken again by
// the binding upsert (§25.10's PUT /api/workflow-bindings) before it
// creates a binding -- so a definition cannot acquire a binding in the
// window between a PUT's refusal check and its own COMMIT. Without it the
// refusal is a read-then-write: the EXISTS sees no binding, an admin
// activates the definition, and the edit lands on a now-bound definition,
// which is exactly the past-the-admin-gate dispatch change the refusal
// exists to prevent. Mirrors LockAutomationForUpdate (queries/
// automations.sql), taken for the identical read-check-then-write shape.
//
// Serialising the two writers also fixes a second, quieter race for free:
// two concurrent PUTs on the same definition each deleted only the steps
// visible in their own snapshot, so the "complete desired state" replace
// could merge two step sets instead of replacing one.
func (q *Queries) LockWorkflowDefinitionForUpdate(ctx context.Context, id pgtype.UUID) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, lockWorkflowDefinitionForUpdate, id)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Name,
		&i.IsBuiltIn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWorkflowStepRunAwaitingDecision = `-- name: MarkWorkflowStepRunAwaitingDecision :one
UPDATE workflow_step_runs
SET status = 'awaiting_decision', outcome_status = COALESCE(outcome_status, $2), updated_at = now()
WHERE id = $1
RETURNING id, workflow_run_id, step_definition_id, turn_id, status, outcome_status, outcome_summary, outcome_payload, decision, decision_text, decided_at, decided_by, created_at, updated_at, finished_at
`

type MarkWorkflowStepRunAwaitingDecisionParams struct {
	ID            pgtype.UUID                `json:"id"`
	OutcomeStatus *WorkflowStepOutcomeStatus `json:"outcome_status"`
}

func (q *Queries) MarkWorkflowStepRunAwaitingDecision(ctx context.Context, arg MarkWorkflowStepRunAwaitingDecisionParams) (WorkflowStepRun, error) {
	row := q.db.QueryRow(ctx, markWorkflowStepRunAwaitingDecision, arg.ID, arg.OutcomeStatus)
	var i WorkflowStepRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowRunID,
		&i.StepDefinitionID,
		&i.TurnID,
		&i.Status,
		&i.OutcomeStatus,
		&i.OutcomeSummary,
		&i.OutcomePayload,
		&i.Decision,
		&i.DecisionText,
		&i.DecidedAt,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const setWorkflowStepRunOutcome = `-- name: SetWorkflowStepRunOutcome :execrows
UPDATE workflow_step_runs
SET outcome_status = $2, outcome_summary = $3, outcome_payload = $4, updated_at = now()
WHERE id = $1 AND status = 'running'
`

type SetWorkflowStepRunOutcomeParams struct {
	ID             pgtype.UUID                `json:"id"`
	OutcomeStatus  *WorkflowStepOutcomeStatus `json:"outcome_status"`
	OutcomeSummary *string                    `json:"outcome_summary"`
	OutcomePayload []byte                     `json:"outcome_payload"`
}

func (q *Queries) SetWorkflowStepRunOutcome(ctx context.Context, arg SetWorkflowStepRunOutcomeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setWorkflowStepRunOutcome,
		arg.ID,
		arg.OutcomeStatus,
		arg.OutcomeSummary,
		arg.OutcomePayload,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWorkflowDefinitionNameAndBumpVersion = `-- name: UpdateWorkflowDefinitionNameAndBumpVersion :one
UPDATE workflow_definitions SET name = $2, version = version + 1, updated_at = now() WHERE id = $1 RETURNING id, lane, name, is_built_in, version, created_at, updated_at
`

type UpdateWorkflowDefinitionNameAndBumpVersionParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

// PUT /api/workflow-definitions/{id}'s own definition-row write -- name
// is the only definition-level column this endpoint may change (lane/
// is_built_in are immutable post-creation); version always increments by
// exactly 1 on a successful write, regardless of what (if anything) the
// caller sent ("Bump version on a successful write", §25.10).
func (q *Queries) UpdateWorkflowDefinitionNameAndBumpVersion(ctx context.Context, arg UpdateWorkflowDefinitionNameAndBumpVersionParams) (WorkflowDefinition, error) {
	row := q.db.QueryRow(ctx, updateWorkflowDefinitionNameAndBumpVersion, arg.ID, arg.Name)
	var i WorkflowDefinition
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.Name,
		&i.IsBuiltIn,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGlobalWorkflowBinding = `-- name: UpsertGlobalWorkflowBinding :one
INSERT INTO workflow_bindings (lane, repo_full_name, workflow_definition_id, definition_version)
VALUES ($1, NULL, $2, $3)
ON CONFLICT (lane) WHERE repo_full_name IS NULL
DO UPDATE SET workflow_definition_id = EXCLUDED.workflow_definition_id, definition_version = EXCLUDED.definition_version, updated_at = now()
RETURNING id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at
`

type UpsertGlobalWorkflowBindingParams struct {
	Lane                 WorkflowLane `json:"lane"`
	WorkflowDefinitionID pgtype.UUID  `json:"workflow_definition_id"`
	DefinitionVersion    int32        `json:"definition_version"`
}

func (q *Queries) UpsertGlobalWorkflowBinding(ctx context.Context, arg UpsertGlobalWorkflowBindingParams) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, upsertGlobalWorkflowBinding, arg.Lane, arg.WorkflowDefinitionID, arg.DefinitionVersion)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepoWorkflowBinding = `-- name: UpsertRepoWorkflowBinding :one
INSERT INTO workflow_bindings (lane, repo_full_name, workflow_definition_id, definition_version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (lane, repo_full_name) WHERE repo_full_name IS NOT NULL
DO UPDATE SET workflow_definition_id = EXCLUDED.workflow_definition_id, definition_version = EXCLUDED.definition_version, updated_at = now()
RETURNING id, lane, repo_full_name, workflow_definition_id, definition_version, created_at, updated_at
`

type UpsertRepoWorkflowBindingParams struct {
	Lane                 WorkflowLane `json:"lane"`
	RepoFullName         *string      `json:"repo_full_name"`
	WorkflowDefinitionID pgtype.UUID  `json:"workflow_definition_id"`
	DefinitionVersion    int32        `json:"definition_version"`
}

func (q *Queries) UpsertRepoWorkflowBinding(ctx context.Context, arg UpsertRepoWorkflowBindingParams) (WorkflowBinding, error) {
	row := q.db.QueryRow(ctx, upsertRepoWorkflowBinding,
		arg.Lane,
		arg.RepoFullName,
		arg.WorkflowDefinitionID,
		arg.DefinitionVersion,
	)
	var i WorkflowBinding
	err := row.Scan(
		&i.ID,
		&i.Lane,
		&i.RepoFullName,
		&i.WorkflowDefinitionID,
		&i.DefinitionVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
