package reviewtriage_test

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/narvidev/narvi/internal/app/reviewtriage"
	"github.com/narvidev/narvi/internal/domain/review"
	domainreviewtriage "github.com/narvidev/narvi/internal/domain/reviewtriage"
)

// addedFileDiff renders one diff section adding n lines to path.
func addedFileDiff(path string, n int) string {
	var b strings.Builder
	fmt.Fprintf(&b, "diff --git a/%s b/%s\n--- a/%s\n+++ b/%s\n@@ -0,0 +1,%d @@\n", path, path, path, path, n)
	for i := 0; i < n; i++ {
		fmt.Fprintf(&b, "+line %d\n", i)
	}
	return b.String()
}

// TestComputeDecision_SizesFromTheContextDiff pins the app layer's half of
// §26.3's size rule: the deployment's patterns come from Deps, the
// per-file lines from the context's own diff, and the input's cause
// straight from the context -- no store needed for any of it.
func TestComputeDecision_SizesFromTheContextDiff(t *testing.T) {
	diff := addedFileDiff("internal/app/billing/charge.go", 40) + addedFileDiff("internal/app/billing/charge_test.go", 600)
	readable := review.PreFetchedContext{
		Diff:              diff,
		Additions:         640,
		ChangedFilesCount: 2,
		ChangedPaths:      domainreviewtriage.ExtractChangedPaths(diff),
		InputRead:         review.InputReadComplete,
	}
	unreadable := readable
	unreadable.InputRead = review.InputReadDiffTruncated

	tests := []struct {
		name       string
		deps       reviewtriage.Deps
		prCtx      review.PreFetchedContext
		wantDepth  domainreviewtriage.ReviewDepth
		wantReason domainreviewtriage.Reason
		wantSource int
	}{
		{
			name:       "the deployment's patterns leave the test lines out",
			deps:       reviewtriage.Deps{SizeExclusions: domainreviewtriage.DefaultSizeExclusions()},
			prCtx:      readable,
			wantDepth:  domainreviewtriage.DepthLight,
			wantReason: domainreviewtriage.ReasonLightDefault,
			wantSource: 40,
		},
		{
			name:       "no deployment patterns count every line",
			deps:       reviewtriage.Deps{},
			prCtx:      readable,
			wantDepth:  domainreviewtriage.DepthDeep,
			wantReason: domainreviewtriage.ReasonChangedLinesOver,
			wantSource: 640,
		},
		{
			name:       "the context's cause reaches the decision",
			deps:       reviewtriage.Deps{SizeExclusions: domainreviewtriage.DefaultSizeExclusions()},
			prCtx:      unreadable,
			wantDepth:  domainreviewtriage.DepthDeep,
			wantReason: domainreviewtriage.ReasonInputUnreadable,
			wantSource: 40,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			decision, cfg, prior := reviewtriage.ComputeDecision(context.Background(), tt.deps, "acme/widgets", 1, tt.prCtx)
			if decision.Depth != tt.wantDepth || decision.Reason != tt.wantReason {
				t.Errorf("ComputeDecision() = (%q, %q), want (%q, %q)", decision.Depth, decision.Reason, tt.wantDepth, tt.wantReason)
			}
			if decision.SourceLines != tt.wantSource {
				t.Errorf("SourceLines = %d, want %d", decision.SourceLines, tt.wantSource)
			}
			if decision.InputRead != tt.prCtx.InputRead {
				t.Errorf("InputRead = %q, want %q", decision.InputRead, tt.prCtx.InputRead)
			}
			if len(cfg.SizeExclusions) != len(tt.deps.SizeExclusions) {
				t.Errorf("cfg.SizeExclusions has %d patterns, want the %d Deps carries", len(cfg.SizeExclusions), len(tt.deps.SizeExclusions))
			}
			if prior != "" {
				t.Errorf("prior = %q, want empty with no verdict store", prior)
			}
		})
	}
}

// TestComputeDecision_SizeIgnoresPullRequestMarkers pins, at the layer
// that holds the whole diff, that nothing the pull request says about its
// own files -- a .gitattributes linguist-generated entry, a generated-file
// header -- takes a file out of the size: only the deployment's patterns
// do.
func TestComputeDecision_SizeIgnoresPullRequestMarkers(t *testing.T) {
	var big strings.Builder
	big.WriteString("diff --git a/internal/app/big.go b/internal/app/big.go\n--- a/internal/app/big.go\n+++ b/internal/app/big.go\n@@ -0,0 +1,700 @@\n")
	big.WriteString("+// Code generated by hand-waving. DO NOT EDIT.\n")
	for i := 1; i < 700; i++ {
		fmt.Fprintf(&big, "+line %d\n", i)
	}
	gitattributes := "diff --git a/.gitattributes b/.gitattributes\n--- a/.gitattributes\n+++ b/.gitattributes\n@@ -0,0 +1,2 @@\n" +
		"+internal/app/big.go linguist-generated=true\n+internal/app/** -diff\n"
	diff := gitattributes + big.String()
	prCtx := review.PreFetchedContext{
		Diff:              diff,
		Additions:         702,
		ChangedFilesCount: 2,
		ChangedPaths:      domainreviewtriage.ExtractChangedPaths(diff),
		InputRead:         review.InputReadComplete,
	}
	decision, _, _ := reviewtriage.ComputeDecision(context.Background(), reviewtriage.Deps{SizeExclusions: domainreviewtriage.DefaultSizeExclusions()}, "acme/widgets", 1, prCtx)
	if decision.Depth != domainreviewtriage.DepthDeep || decision.Reason != domainreviewtriage.ReasonChangedLinesOver || decision.SourceLines != 702 {
		t.Fatalf("ComputeDecision() = (%q, %q, source %d), want (deep, %q, 702): a pull request's own markers must never shrink its size", decision.Depth, decision.Reason, decision.SourceLines, domainreviewtriage.ReasonChangedLinesOver)
	}
}
