package contractstest

import (
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/narvidev/narvi/contracts"
)

// manifest mirrors compat.Manifest's own shape (tools/contractscompat/
// compat/manifest.go) just enough for this test -- duplicated rather than
// imported so contracts/contractstest, a package other Steps may embed
// into a shipped binary one day (README.md's own "single source of wire
// truth"), never depends on a tools/ package.
type manifest struct {
	Surfaces []struct {
		Path string `json:"path"`
	} `json:"surfaces"`
}

// TestManifestMatchesEmbeddedSchemaSet is §6.3 design spec §3's guard 6:
// contracts/manifest.json's own surface set must equal contracts.FS's
// embedded *.schema.json set exactly -- a schema file added to disk but
// never registered in the manifest (or vice versa) would otherwise let
// tools/contractscompat silently skip it rather than fail loudly, since
// that tool trusts the manifest for direction/status but the actual
// content for everything else.
func TestManifestMatchesEmbeddedSchemaSet(t *testing.T) {
	data, err := os.ReadFile("../manifest.json")
	if err != nil {
		t.Fatalf("read manifest.json: %v", err)
	}
	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("parse manifest.json: %v", err)
	}
	if len(m.Surfaces) == 0 {
		t.Fatal("manifest.json lists no surfaces")
	}

	manifestPaths := map[string]bool{}
	for _, s := range m.Surfaces {
		manifestPaths[s.Path] = true
	}

	embeddedPaths := map[string]bool{}
	err = fs.WalkDir(contracts.FS, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".schema.json") {
			return nil
		}
		embeddedPaths[filepath.ToSlash(path)] = true
		return nil
	})
	if err != nil {
		t.Fatalf("walk contracts.FS: %v", err)
	}
	if len(embeddedPaths) == 0 {
		t.Fatal("contracts.FS embeds no schema files")
	}

	for p := range manifestPaths {
		if !embeddedPaths[p] {
			t.Errorf("manifest.json lists %s but contracts.FS does not embed it", p)
		}
	}
	for p := range embeddedPaths {
		if !manifestPaths[p] {
			t.Errorf("contracts.FS embeds %s but manifest.json has no row for it", p)
		}
	}
}

// surfaceCodegen maps each manifest.json surface path to the Go package
// (under contracts/gen/go) and the TS file (under contracts/gen/ts) the
// Makefile's contracts-generate target and contracts/scripts/
// generate-ts.mjs are, TODAY, hand-wired to produce for it. The mapping
// is many-to-one for sandbox-ws (commands.schema.json and
// events.schema.json share one go-jsonschema invocation, package
// "sandboxws") -- see the Makefile's contracts-generate recipe and
// generate-ts.mjs's own `schemas` array, which this table mirrors by
// hand for the same reason contractstest never imports tools/
// contractscompat/compat (see that package's own manifest type,
// duplicated above): this is the low-tech, always-available way to
// notice one of those two files falling out of sync with manifest.json,
// short of teaching this test to parse a Makefile recipe or a .mjs
// module.
var surfaceCodegen = map[string]struct {
	goPackage string
	tsFile    string
}{
	"sandbox-ws/v1/commands.schema.json":           {"sandboxws", "sandbox-ws-commands.ts"},
	"sandbox-ws/v1/events.schema.json":             {"sandboxws", "sandbox-ws-events.ts"},
	"client-ws/v1/protocol.schema.json":            {"clientws", "client-ws.ts"},
	"session-config/v1/session-config.schema.json": {"sessionconfig", "session-config.ts"},
	"rest/v1/dtos.schema.json":                     {"restdtos", "rest-dtos.ts"},
}

// TestManifestMatchesCodegenOutput is C21 / §3 guard 6's remaining two
// legs: the manifest set must equal not just contracts.FS (checked
// above) but ALSO the gen/go package list and the gen/ts file list. A
// versioned-sibling PR that adds a manifest row, embeds the new schema,
// but forgets to wire it into the Makefile's contracts-generate recipe
// and generate-ts.mjs's `schemas` array would otherwise sail through
// `go test ./...` (contracts-compat would only ever report the new
// file's own row-38 MINOR) with no generated Go or TS types at all for
// the new surface -- this test catches that by asserting the OUTPUT
// (already regenerated by `make contracts-check` as part of CI, and
// committed) actually exists for every surface manifest.json declares.
func TestManifestMatchesCodegenOutput(t *testing.T) {
	data, err := os.ReadFile("../manifest.json")
	if err != nil {
		t.Fatalf("read manifest.json: %v", err)
	}
	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		t.Fatalf("parse manifest.json: %v", err)
	}

	for _, s := range m.Surfaces {
		codegen, ok := surfaceCodegen[s.Path]
		if !ok {
			t.Errorf("manifest.json surface %s has no entry in this test's surfaceCodegen table -- add one (and wire the Makefile's contracts-generate recipe + generate-ts.mjs's schemas array) before landing this row", s.Path)
			continue
		}
		pkgDir := filepath.Join("..", "gen", "go", codegen.goPackage)
		entries, err := os.ReadDir(pkgDir)
		if err != nil || !anyGoFile(entries) {
			t.Errorf("manifest.json surface %s expects a generated Go package at contracts/gen/go/%s, but it is missing or empty (is it wired into the Makefile's contracts-generate recipe?)", s.Path, codegen.goPackage)
		}
		tsPath := filepath.Join("..", "gen", "ts", codegen.tsFile)
		if _, err := os.Stat(tsPath); err != nil {
			t.Errorf("manifest.json surface %s expects a generated TS file at contracts/gen/ts/%s, but it is missing (is it wired into generate-ts.mjs's schemas array?)", s.Path, codegen.tsFile)
		}
	}

	for path := range surfaceCodegen {
		found := false
		for _, s := range m.Surfaces {
			if s.Path == path {
				found = true
				break
			}
		}
		if !found {
			t.Errorf("surfaceCodegen has an entry for %s but manifest.json has no matching row -- this test's own table has drifted", path)
		}
	}
}

func anyGoFile(entries []os.DirEntry) bool {
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), ".go") {
			return true
		}
	}
	return false
}

// TestVersionMatchesPackageJSON pins contracts/VERSION and contracts/
// package.json's own "version" field to the same value (§6.3 design spec
// §4) -- two independent files a reviewer could update just one of by
// mistake, one read by contracts.Version (the Go/embedded side), the
// other by every npm tool that touches this scoped project (the TS
// side).
func TestVersionMatchesPackageJSON(t *testing.T) {
	versionData, err := os.ReadFile("../VERSION")
	if err != nil {
		t.Fatalf("read VERSION: %v", err)
	}
	version := strings.TrimSpace(string(versionData))
	if version == "" {
		t.Fatal("contracts/VERSION is empty")
	}
	if version != contracts.Version {
		t.Fatalf("contracts.Version (%q) does not match contracts/VERSION on disk (%q) -- did the embed drift?", contracts.Version, version)
	}

	pkgData, err := os.ReadFile("../package.json")
	if err != nil {
		t.Fatalf("read package.json: %v", err)
	}
	var pkg struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal(pkgData, &pkg); err != nil {
		t.Fatalf("parse package.json: %v", err)
	}
	if pkg.Version != version {
		t.Fatalf("contracts/package.json version (%q) does not match contracts/VERSION (%q)", pkg.Version, version)
	}
}
