package githubapi_test

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"

	"github.com/narvidev/narvi/internal/adapters/outbound/githubapi"
	"github.com/narvidev/narvi/internal/app/ports"
	"github.com/narvidev/narvi/internal/domain/contractdrift"
)

// TestCreatePR_Success proves CreatePR posts the right shape to
// /repos/{owner}/{repo}/pulls and parses a real GitHub-shaped success
// response.
func TestCreatePR_Success(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth, gotAccept string
	var gotBody map[string]any

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotAccept = r.Header.Get("Accept")
		if err := json.NewDecoder(r.Body).Decode(&gotBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}

		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"number":   42,
			"html_url": "https://github.com/acme/widgets/pull/42",
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	ref, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Body:  "Generated by narvi.",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("CreatePR() error = %v, want nil", err)
	}

	if gotPath != "/repos/acme/widgets/pulls" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/pulls")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
	if gotAccept != "application/vnd.github+json" {
		t.Errorf("Accept header = %q, want %q", gotAccept, "application/vnd.github+json")
	}
	if gotBody["title"] != "Narvi: do the thing" || gotBody["head"] != "narvi/session-123" || gotBody["base"] != "main" {
		t.Errorf("request body = %+v, missing expected fields", gotBody)
	}

	if ref.Number != 42 {
		t.Errorf("PRRef.Number = %d, want 42", ref.Number)
	}
	if ref.URL != "https://github.com/acme/widgets/pull/42" {
		t.Errorf("PRRef.URL = %q, want %q", ref.URL, "https://github.com/acme/widgets/pull/42")
	}
}

// TestCreatePR_4xxMapsToRealError proves a realistic GitHub 4xx failure
// (e.g. a validation error on an already-existing PR) maps to a real,
// structured *githubapi.CreatePRError, never a panic or a silently-empty
// PRRef mistaken for success.
func TestCreatePR_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		_ = json.NewEncoder(w).Encode(map[string]any{
			// Deliberately NOT an "already exists" message -- that fixture
			// now collides with CreatePR's own idempotency path (see
			// TestCreatePR_AlreadyExists_* below). This is a genuinely
			// non-idempotent validation failure, so this test keeps
			// exercising real 4xx-to-CreatePRError mapping instead of the
			// recovery path.
			"message": "Validation Failed: head and base branches must be different.",
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Token: "gho_realtoken",
	})
	if err == nil {
		t.Fatal("CreatePR() error = nil, want a *githubapi.CreatePRError")
	}

	var prErr *githubapi.CreatePRError
	if !asCreatePRError(err, &prErr) {
		t.Fatalf("CreatePR() error = %v (%T), want *githubapi.CreatePRError", err, err)
	}
	if prErr.Status != http.StatusUnprocessableEntity {
		t.Errorf("CreatePRError.Status = %d, want %d", prErr.Status, http.StatusUnprocessableEntity)
	}
	if prErr.Message == "" {
		t.Error("CreatePRError.Message is empty, want GitHub's own error message")
	}
}

// TestCreatePR_AlreadyExists_RecoversExistingOpenPR proves CreatePR's own
// idempotency path: a 422 "already exists" response is followed by a real
// GET /pulls?head=...&base=...&state=open lookup, and the matching PR's own
// Number/URL are returned with a nil error -- never the original 422.
func TestCreatePR_AlreadyExists_RecoversExistingOpenPR(t *testing.T) {
	t.Parallel()

	var gotListPath string
	var gotQuery url.Values

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.Method == http.MethodPost && r.URL.Path == "/repos/acme/widgets/pulls":
			w.WriteHeader(http.StatusUnprocessableEntity)
			_ = json.NewEncoder(w).Encode(map[string]any{
				"message": "A pull request already exists for acme:narvi/session-123.",
			})
		case r.Method == http.MethodGet && r.URL.Path == "/repos/acme/widgets/pulls":
			gotListPath = r.URL.Path
			gotQuery = r.URL.Query()
			w.WriteHeader(http.StatusOK)
			_ = json.NewEncoder(w).Encode([]map[string]any{
				{"number": 77, "html_url": "https://github.com/acme/widgets/pull/77"},
			})
		default:
			t.Errorf("unexpected request: %s %s", r.Method, r.URL.Path)
			w.WriteHeader(http.StatusNotFound)
		}
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	ref, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("CreatePR() error = %v, want nil (recovered from the already-exists 422)", err)
	}
	if ref.Number != 77 || ref.URL != "https://github.com/acme/widgets/pull/77" {
		t.Errorf("CreatePR() = %+v, want the recovered PR's own Number/URL", ref)
	}
	if gotListPath == "" {
		t.Fatal("no GET /pulls lookup was ever made")
	}
	if got := gotQuery.Get("head"); got != "acme:narvi/session-123" {
		t.Errorf("lookup head query = %q, want %q", got, "acme:narvi/session-123")
	}
	if got := gotQuery.Get("base"); got != "main" {
		t.Errorf("lookup base query = %q, want %q", got, "main")
	}
	if got := gotQuery.Get("state"); got != "open" {
		t.Errorf("lookup state query = %q, want %q", got, "open")
	}
}

// TestCreatePR_AlreadyExists_LookupFails_ReturnsOriginalError proves that
// when the recovery lookup itself finds nothing, CreatePR falls back to the
// ORIGINAL CreatePRError (status + message), never a different/wrapped
// lookup error -- a caller must never see this idempotency path make things
// worse than the pre-existing behavior.
func TestCreatePR_AlreadyExists_LookupFails_ReturnsOriginalError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost:
			w.WriteHeader(http.StatusUnprocessableEntity)
			_ = json.NewEncoder(w).Encode(map[string]any{
				"message": "A pull request already exists for acme:narvi/session-123.",
			})
		case http.MethodGet:
			w.WriteHeader(http.StatusOK)
			_ = json.NewEncoder(w).Encode([]map[string]any{}) // no matching open PR
		}
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme",
		Repo:  "widgets",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "Narvi: do the thing",
		Token: "gho_realtoken",
	})
	if err == nil {
		t.Fatal("CreatePR() error = nil, want the original CreatePRError when the lookup finds nothing")
	}

	var prErr *githubapi.CreatePRError
	if !asCreatePRError(err, &prErr) {
		t.Fatalf("CreatePR() error = %v (%T), want *githubapi.CreatePRError (the ORIGINAL error, not a lookup error)", err, err)
	}
	if prErr.Status != http.StatusUnprocessableEntity {
		t.Errorf("CreatePRError.Status = %d, want %d (the original status)", prErr.Status, http.StatusUnprocessableEntity)
	}
	if !strings.Contains(strings.ToLower(prErr.Message), "already exists") {
		t.Errorf("CreatePRError.Message = %q, want it to still contain GitHub's original message", prErr.Message)
	}
}

// --- URL escaping (audit remediation: security-crosscutting lens) ---
//
// Each test below asserts against the real *http.Request.URL the server
// actually received (via r.URL.EscapedPath(), the exact wire-encoded path,
// and r.URL.Query(), the real parsed query values) -- not merely that the
// call returned no error -- so a regression that silently stopped escaping
// (e.g. reverting to a bare fmt.Sprintf) would fail these tests even
// though the fake server itself never rejects any request shape.

// TestCreatePR_EscapesOwnerAndRepo proves a malicious Owner/Repo containing
// a "/" and a "#" cannot inject an extra path segment or truncate the
// request via an unintended URL fragment.
func TestCreatePR_EscapesOwnerAndRepo(t *testing.T) {
	t.Parallel()

	var gotEscapedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPath = r.URL.EscapedPath()
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(map[string]any{"number": 1, "html_url": "https://github.com/x/y/pull/1"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.CreatePR(context.Background(), ports.CreatePRSpec{
		Owner: "acme/evil",
		Repo:  "widgets#v1",
		Head:  "narvi/session-123",
		Base:  "main",
		Title: "t",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("CreatePR() error = %v, want nil", err)
	}

	want := "/repos/acme%2Fevil/widgets%23v1/pulls"
	if gotEscapedPath != want {
		t.Errorf("request EscapedPath = %q, want %q (owner/repo must be escaped, not interpolated raw)", gotEscapedPath, want)
	}
}

// TestResolveBranchSHA_EscapesOwnerRepoAndBranch proves a malicious
// Owner/Repo/Branch is escaped on BOTH request paths ResolveBranchSHA can
// build: the repo-info lookup (only reached when Branch is empty) and the
// commits lookup, whose OWN ref segment is the resolved default_branch
// value in this path -- itself attacker-shaped here, since a real GitHub
// default_branch is caller-controlled from ResolveBranchSHA's own point of
// view.
func TestResolveBranchSHA_EscapesOwnerRepoAndBranch(t *testing.T) {
	t.Parallel()

	var gotEscapedPaths []string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPaths = append(gotEscapedPaths, r.URL.EscapedPath())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		switch {
		case len(gotEscapedPaths) == 1:
			_ = json.NewEncoder(w).Encode(map[string]any{"default_branch": "release/1.0#x"})
		default:
			_ = json.NewEncoder(w).Encode(map[string]any{"sha": "abc123"})
		}
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	sha, _, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner: "acme/evil",
		Repo:  "widgets#v1",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveBranchSHA() error = %v, want nil", err)
	}
	if sha != "abc123" {
		t.Errorf("ResolveBranchSHA() = %q, want %q", sha, "abc123")
	}

	if len(gotEscapedPaths) != 2 {
		t.Fatalf("server received %d requests, want 2", len(gotEscapedPaths))
	}
	wantRepoPath := "/repos/acme%2Fevil/widgets%23v1"
	if gotEscapedPaths[0] != wantRepoPath {
		t.Errorf("repo-info request EscapedPath = %q, want %q", gotEscapedPaths[0], wantRepoPath)
	}
	// branch (the resolved default_branch "release/1.0#x") is escaped as a
	// single opaque path segment -- GitHub's own commits/{ref} endpoint
	// requires a "/" WITHIN a ref to be percent-encoded (%2F) to
	// disambiguate it from a route-segment boundary, exactly what
	// url.PathEscape produces here.
	wantCommitPath := "/repos/acme%2Fevil/widgets%23v1/commits/release%2F1.0%23x"
	if gotEscapedPaths[1] != wantCommitPath {
		t.Errorf("commit request EscapedPath = %q, want %q", gotEscapedPaths[1], wantCommitPath)
	}
}

// TestResolveContractsFingerprint_EscapesOwnerRepoPathAndRef proves the
// sharpest case the audit named: a spec.Path containing "?ref=attacker&"
// must not rewrite the request's real query string (the actual spec.Ref
// must still win), and a spec.Path containing "#" must not truncate the
// request via an unintended URL fragment -- while a real, multi-segment
// spec.Path (containing legitimate "/" directory separators) must still
// resolve to a real, correctly nested GitHub Contents API path, not a
// single mangled segment.
func TestResolveContractsFingerprint_EscapesOwnerRepoPathAndRef(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name            string
		path            string
		ref             string
		wantEscapedTail string
		wantRefQuery    string
	}{
		{
			name:            "query-injection attempt via path is neutralized",
			path:            "x?ref=attacker&",
			ref:             "realref",
			wantEscapedTail: "/contents/x%3Fref=attacker&",
			wantRefQuery:    "realref",
		},
		{
			name:            "fragment-truncation attempt via path is neutralized",
			path:            "x#evilfragment",
			ref:             "realref",
			wantEscapedTail: "/contents/x%23evilfragment",
			wantRefQuery:    "realref",
		},
		{
			name:            "a real multi-segment path still resolves as nested directories",
			path:            "services/mock-api/contracts",
			ref:             "abc123",
			wantEscapedTail: "/contents/services/mock-api/contracts",
			wantRefQuery:    "abc123",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			var gotEscapedPath string
			var gotQuery url.Values
			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				gotEscapedPath = r.URL.EscapedPath()
				gotQuery = r.URL.Query()
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusOK)
				_ = json.NewEncoder(w).Encode([]map[string]any{})
			}))
			defer server.Close()

			adapter := githubapi.New(server.Client(), server.URL)

			_, _, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
				Owner: "acme",
				Repo:  "widgets",
				Ref:   tc.ref,
				Path:  tc.path,
				Token: "gho_realtoken",
			})
			if err != nil {
				t.Fatalf("ResolveContractsFingerprint() error = %v, want nil", err)
			}

			wantEscapedPath := "/repos/acme/widgets" + tc.wantEscapedTail
			if gotEscapedPath != wantEscapedPath {
				t.Errorf("request EscapedPath = %q, want %q", gotEscapedPath, wantEscapedPath)
			}
			// len == 1 proves the malicious path never smuggled in a SECOND
			// query key/value the attacker controlled (e.g. its own "ref").
			if len(gotQuery["ref"]) != 1 || gotQuery.Get("ref") != tc.wantRefQuery {
				t.Errorf("request query ref = %v, want exactly one value %q", gotQuery["ref"], tc.wantRefQuery)
			}
		})
	}
}

// TestGetPullRequest_Success proves GetPullRequest resolves the real head
// ref/repo from a realistic GET /repos/{owner}/{repo}/pulls/{number}
// response -- batch fix/audit-github-pr-payload-correctness's own H5 fix.
func TestGetPullRequest_Success(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth, gotAccept string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotAccept = r.Header.Get("Accept")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"number": 42,
			"title":  "Fix the retry loop",
			"body":   "Retries now back off exponentially.",
			"head": map[string]any{
				"ref": "feature-x",
				"repo": map[string]any{
					"name":      "widgets",
					"clone_url": "https://github.com/contributor/widgets.git",
				},
			},
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	pr, err := adapter.GetPullRequest(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequest() error = %v, want nil", err)
	}

	if gotPath != "/repos/acme/widgets/pulls/42" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/pulls/42")
	}
	if gotAuth != "Bearer gho_bottoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_bottoken")
	}
	if gotAccept != "application/vnd.github+json" {
		t.Errorf("Accept header = %q, want %q", gotAccept, "application/vnd.github+json")
	}

	if pr.HeadRef != "feature-x" {
		t.Errorf("PullRequest.HeadRef = %q, want %q", pr.HeadRef, "feature-x")
	}
	if pr.HeadRepoName != "widgets" {
		t.Errorf("PullRequest.HeadRepoName = %q, want %q", pr.HeadRepoName, "widgets")
	}
	if pr.HeadRepoCloneURL != "https://github.com/contributor/widgets.git" {
		t.Errorf("PullRequest.HeadRepoCloneURL = %q, want %q", pr.HeadRepoCloneURL, "https://github.com/contributor/widgets.git")
	}
	if pr.Title != "Fix the retry loop" {
		t.Errorf("PullRequest.Title = %q, want %q", pr.Title, "Fix the retry loop")
	}
	if pr.Body != "Retries now back off exponentially." {
		t.Errorf("PullRequest.Body = %q, want %q", pr.Body, "Retries now back off exponentially.")
	}
}

// TestGetPullRequest_NullBody proves a real "body: null" response (GitHub's
// own documented shape for a PR opened with no description at all) resolves
// to an empty PullRequest.Body rather than an error or a panic -- mirrors
// TestGetPullRequest_NullHeadRepo's own identical nullable-field precedent,
// for the SAME underlying reason (pullRequestResponse.Body is *string).
func TestGetPullRequest_NullBody(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"number": 42, "title": "Fix the retry loop", "body": null, "head": {"ref": "feature-x", "repo": null}}`))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	pr, err := adapter.GetPullRequest(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequest() error = %v, want nil", err)
	}
	if pr.Title != "Fix the retry loop" {
		t.Errorf("PullRequest.Title = %q, want %q", pr.Title, "Fix the retry loop")
	}
	if pr.Body != "" {
		t.Errorf("PullRequest.Body = %q, want empty (body was null)", pr.Body)
	}
}

// TestGetPullRequest_NullHeadRepo proves a real "head.repo: null" response
// (GitHub's own documented shape when the head/fork repo has been deleted)
// resolves to an empty HeadRepoName/HeadRepoCloneURL rather than an error
// or a panic -- L15's own sibling fix, mirrored here on the outbound side.
func TestGetPullRequest_NullHeadRepo(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"number": 42, "head": {"ref": "feature-x", "repo": null}}`))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	pr, err := adapter.GetPullRequest(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequest() error = %v, want nil", err)
	}
	if pr.HeadRef != "feature-x" {
		t.Errorf("PullRequest.HeadRef = %q, want %q", pr.HeadRef, "feature-x")
	}
	if pr.HeadRepoName != "" {
		t.Errorf("PullRequest.HeadRepoName = %q, want empty (head.repo was null)", pr.HeadRepoName)
	}
	if pr.HeadRepoCloneURL != "" {
		t.Errorf("PullRequest.HeadRepoCloneURL = %q, want empty (head.repo was null)", pr.HeadRepoCloneURL)
	}
}

// TestGetPullRequest_4xxMapsToRealError proves a realistic GitHub 4xx
// failure (e.g. PR not found) maps to a real, structured *githubapi.
// APIError, never a panic or a silently-empty PullRequest mistaken for
// success.
func TestGetPullRequest_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Not Found"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.GetPullRequest(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err == nil {
		t.Fatal("GetPullRequest() error = nil, want a *githubapi.APIError")
	}

	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("GetPullRequest() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if apiErr.Status != http.StatusNotFound {
		t.Errorf("APIError.Status = %d, want %d", apiErr.Status, http.StatusNotFound)
	}
}

// TestGetPullRequest_EscapesOwnerAndRepo proves a malicious Owner/Repo
// containing a "/" and a "#" cannot inject an extra path segment or
// truncate the request via an unintended URL fragment -- mirrors
// TestCreatePR_EscapesOwnerAndRepo's own identical discipline.
func TestGetPullRequest_EscapesOwnerAndRepo(t *testing.T) {
	t.Parallel()

	var gotEscapedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPath = r.URL.EscapedPath()
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{"number": 1, "head": map[string]any{"ref": "x", "repo": nil}})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, err := adapter.GetPullRequest(context.Background(), "acme/evil", "widgets#v1", 7, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequest() error = %v, want nil", err)
	}

	want := "/repos/acme%2Fevil/widgets%23v1/pulls/7"
	if gotEscapedPath != want {
		t.Errorf("request EscapedPath = %q, want %q (owner/repo must be escaped, not interpolated raw)", gotEscapedPath, want)
	}
}

// TestGetPullRequest_StackPresent proves a real GitHub "stack" object
// riding on the pull-request resource (§17.6's amendment, "review
// sessions") is parsed into PullRequest.Stack.
func TestGetPullRequest_StackPresent(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"number": 42,
			"head":   map[string]any{"ref": "feature-x", "repo": nil},
			// Position/Size deliberately distinguishable (2 vs 3, not an
			// equal-valued pair) -- a confirmed audit finding noted that a
			// Position/Size field swap in GetPullRequest's own mapping would
			// pass undetected against a fixture where both fields carried
			// the same value.
			"stack": map[string]any{
				"size":     3,
				"position": 2,
				"base": map[string]any{
					"ref": "main",
					"sha": "deadbeefcafe",
				},
			},
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	pr, err := adapter.GetPullRequest(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequest() error = %v, want nil", err)
	}

	if pr.Stack == nil {
		t.Fatal("PullRequest.Stack = nil, want non-nil when GitHub reports a stack object")
	}
	if pr.Stack.Size != 3 {
		t.Errorf("Stack.Size = %d, want 3", pr.Stack.Size)
	}
	if pr.Stack.Position != 2 {
		t.Errorf("Stack.Position = %d, want 2", pr.Stack.Position)
	}
	if pr.Stack.BaseRef != "main" {
		t.Errorf("Stack.BaseRef = %q, want %q", pr.Stack.BaseRef, "main")
	}
	if pr.Stack.BaseSHA != "deadbeefcafe" {
		t.Errorf("Stack.BaseSHA = %q, want %q", pr.Stack.BaseSHA, "deadbeefcafe")
	}
}

// TestGetPullRequest_NoStackIsNil proves the ordinary, non-stacked case
// (GitHub's own response carries no "stack" key at all -- confirmed the
// common case, §17.6) leaves PullRequest.Stack nil, never a zero-valued,
// misleadingly-present struct.
func TestGetPullRequest_NoStackIsNil(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{
			"number": 42,
			"head":   map[string]any{"ref": "feature-x", "repo": nil},
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	pr, err := adapter.GetPullRequest(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequest() error = %v, want nil", err)
	}
	if pr.Stack != nil {
		t.Errorf("PullRequest.Stack = %+v, want nil when GitHub reports no stack object", pr.Stack)
	}
}

// TestGetPullRequestDiff_Success proves GetPullRequestDiff (
// "review sessions", §8.2) requests GitHub's own raw diff media type
// against the SAME pulls/{number} endpoint GetPullRequest uses, and
// returns the response body verbatim, un-truncated, when it fits within
// the cap.
func TestGetPullRequestDiff_Success(t *testing.T) {
	t.Parallel()

	const wantDiff = "diff --git a/x b/x\nindex 111..222 100644\n--- a/x\n+++ b/x\n@@ -1 +1 @@\n-old\n+new\n"

	var gotPath, gotAuth, gotAccept string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotAccept = r.Header.Get("Accept")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(wantDiff))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	diff, truncated, err := adapter.GetPullRequestDiff(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequestDiff() error = %v, want nil", err)
	}
	if gotPath != "/repos/acme/widgets/pulls/42" {
		t.Errorf("request path = %q, want %q (the SAME endpoint GetPullRequest uses)", gotPath, "/repos/acme/widgets/pulls/42")
	}
	if gotAuth != "Bearer gho_bottoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_bottoken")
	}
	if gotAccept != "application/vnd.github.diff" {
		t.Errorf("Accept header = %q, want the raw-diff media type", gotAccept)
	}
	if diff != wantDiff {
		t.Errorf("diff = %q, want %q", diff, wantDiff)
	}
	if truncated {
		t.Error("truncated = true, want false (the diff fit well within the cap)")
	}
}

// TestGetPullRequestDiff_Truncated proves a diff exceeding
// maxPRDiffResponseBytes is cut at the cap and reported as truncated,
// rather than silently handed back partial with no signal.
func TestGetPullRequestDiff_Truncated(t *testing.T) {
	t.Parallel()

	// 5 MiB of 'x' -- comfortably past the package's own 4 MiB cap.
	oversized := strings.Repeat("x", 5<<20)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(oversized))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	diff, truncated, err := adapter.GetPullRequestDiff(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequestDiff() error = %v, want nil", err)
	}
	if !truncated {
		t.Error("truncated = false, want true (the diff exceeded the cap)")
	}
	const wantLen = 4 << 20
	if len(diff) != wantLen {
		t.Errorf("len(diff) = %d, want exactly %d (cut at the cap)", len(diff), wantLen)
	}
}

// TestGetPullRequestDiff_ExactlyAtCapIsNotTruncated proves a diff whose
// length is EXACTLY maxPRDiffResponseBytes is not misreported as
// truncated -- the "read one byte past the cap" discipline this method's
// own doc comment describes.
func TestGetPullRequestDiff_ExactlyAtCapIsNotTruncated(t *testing.T) {
	t.Parallel()

	exact := strings.Repeat("y", 4<<20)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(exact))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	diff, truncated, err := adapter.GetPullRequestDiff(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequestDiff() error = %v, want nil", err)
	}
	if truncated {
		t.Error("truncated = true, want false (the diff ends exactly at the cap, nothing was actually cut)")
	}
	if diff != exact {
		t.Error("diff does not match the exact-cap-length input")
	}
}

// TestGetPullRequestDiff_4xxMapsToRealError proves a realistic GitHub 4xx
// failure still maps to a real, structured *githubapi.APIError even though
// a SUCCESS response on this same call would have been a raw diff, not
// JSON -- GitHub's own error envelope is always plain JSON regardless of
// the Accept header sent.
func TestGetPullRequestDiff_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Not Found"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, _, err := adapter.GetPullRequestDiff(context.Background(), "acme", "widgets", 42, "gho_bottoken")
	if err == nil {
		t.Fatal("GetPullRequestDiff() error = nil, want a *githubapi.APIError")
	}
	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("GetPullRequestDiff() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if apiErr.Status != http.StatusNotFound {
		t.Errorf("APIError.Status = %d, want %d", apiErr.Status, http.StatusNotFound)
	}
}

// TestGetPullRequestDiff_EscapesOwnerAndRepo mirrors
// TestGetPullRequest_EscapesOwnerAndRepo's own identical discipline for
// this method's own request-path construction.
func TestGetPullRequestDiff_EscapesOwnerAndRepo(t *testing.T) {
	t.Parallel()

	var gotEscapedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPath = r.URL.EscapedPath()
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("diff"))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, _, err := adapter.GetPullRequestDiff(context.Background(), "acme/evil", "widgets#v1", 7, "gho_bottoken")
	if err != nil {
		t.Fatalf("GetPullRequestDiff() error = %v, want nil", err)
	}

	want := "/repos/acme%2Fevil/widgets%23v1/pulls/7"
	if gotEscapedPath != want {
		t.Errorf("request EscapedPath = %q, want %q (owner/repo must be escaped, not interpolated raw)", gotEscapedPath, want)
	}
}

// TestGetCompareDiff_Success proves the happy path: GET
// /repos/{owner}/{repo}/compare/{base}...{head}, content-negotiated for
// the SAME diff media type GetPullRequestDiff uses.
func TestGetCompareDiff_Success(t *testing.T) {
	t.Parallel()

	const wantDiff = "diff --git a/x b/x\nindex 111..222 100644\n--- a/x\n+++ b/x\n@@ -1 +1 @@\n-old\n+new\n"

	var gotPath, gotAuth, gotAccept string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotAccept = r.Header.Get("Accept")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(wantDiff))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	diff, truncated, err := adapter.GetCompareDiff(context.Background(), "acme", "widgets", "main", "feature-sha", "gho_bottoken")
	if err != nil {
		t.Fatalf("GetCompareDiff() error = %v, want nil", err)
	}
	if gotPath != "/repos/acme/widgets/compare/main...feature-sha" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/compare/main...feature-sha")
	}
	if gotAuth != "Bearer gho_bottoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_bottoken")
	}
	if gotAccept != "application/vnd.github.diff" {
		t.Errorf("Accept header = %q, want the raw-diff media type", gotAccept)
	}
	if diff != wantDiff {
		t.Errorf("diff = %q, want %q", diff, wantDiff)
	}
	if truncated {
		t.Error("truncated = true, want false (the diff fit well within the cap)")
	}
}

// TestGetCompareDiff_PinnedToExactBaseAndHead proves base/head are both
// passed through verbatim into the request path -- distinct values on
// each side (never the same string twice) so a transposition bug (base
// and head swapped) would fail this assertion. This is the C2 fix's own
// core property exercised directly at the adapter level: two calls with
// DIFFERENT head values produce DIFFERENT request paths, unlike
// GetPullRequestDiff's own fixed /pulls/{number} target.
func TestGetCompareDiff_PinnedToExactBaseAndHead(t *testing.T) {
	t.Parallel()

	var gotPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("diff"))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	if _, _, err := adapter.GetCompareDiff(context.Background(), "acme", "widgets", "base-ref-abc", "head-sha-xyz", "gho_bottoken"); err != nil {
		t.Fatalf("GetCompareDiff() error = %v, want nil", err)
	}
	if gotPath != "/repos/acme/widgets/compare/base-ref-abc...head-sha-xyz" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/compare/base-ref-abc...head-sha-xyz")
	}
}

// TestGetCompareDiff_Truncated mirrors TestGetPullRequestDiff_Truncated's
// own identical cap/truncation discipline.
func TestGetCompareDiff_Truncated(t *testing.T) {
	t.Parallel()

	oversized := strings.Repeat("x", 5<<20)

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(oversized))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	diff, truncated, err := adapter.GetCompareDiff(context.Background(), "acme", "widgets", "main", "sha", "gho_bottoken")
	if err != nil {
		t.Fatalf("GetCompareDiff() error = %v, want nil", err)
	}
	if !truncated {
		t.Error("truncated = false, want true (the diff exceeded the cap)")
	}
	const wantLen = 4 << 20
	if len(diff) != wantLen {
		t.Errorf("len(diff) = %d, want exactly %d (cut at the cap)", len(diff), wantLen)
	}
}

// TestGetCompareDiff_4xxMapsToRealError mirrors
// TestGetPullRequestDiff_4xxMapsToRealError's own identical error-envelope
// discipline.
func TestGetCompareDiff_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Not Found"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, _, err := adapter.GetCompareDiff(context.Background(), "acme", "widgets", "main", "sha", "gho_bottoken")
	if err == nil {
		t.Fatal("GetCompareDiff() error = nil, want a *githubapi.APIError")
	}
	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("GetCompareDiff() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if apiErr.Status != http.StatusNotFound {
		t.Errorf("APIError.Status = %d, want %d", apiErr.Status, http.StatusNotFound)
	}
}

// TestGetCompareDiff_EscapesOwnerRepoBaseHead mirrors
// TestGetPullRequestDiff_EscapesOwnerAndRepo's own identical discipline,
// extended to base/head -- both are caller-suppliable (base from a PR's
// own reported BaseRef, head from HeadSHA), so both must be escaped too.
func TestGetCompareDiff_EscapesOwnerRepoBaseHead(t *testing.T) {
	t.Parallel()

	var gotEscapedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPath = r.URL.EscapedPath()
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("diff"))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, _, err := adapter.GetCompareDiff(context.Background(), "acme/evil", "widgets#v1", "main#ref", "feature/x", "gho_bottoken")
	if err != nil {
		t.Fatalf("GetCompareDiff() error = %v, want nil", err)
	}

	want := "/repos/acme%2Fevil/widgets%23v1/compare/main%23ref...feature%2Fx"
	if gotEscapedPath != want {
		t.Errorf("request EscapedPath = %q, want %q (owner/repo/base/head must all be escaped, not interpolated raw)", gotEscapedPath, want)
	}
}

// TestNew_DefaultsAPIBaseURL proves an empty apiBaseURL falls back to
// GitHub's own real API host rather than an empty/unusable base.
func TestNew_DefaultsAPIBaseURL(t *testing.T) {
	t.Parallel()

	adapter := githubapi.New(nil, "")
	if adapter == nil {
		t.Fatal("New(nil, \"\") = nil, want a non-nil *Adapter")
	}
}

func asCreatePRError(err error, target **githubapi.CreatePRError) bool {
	pe, ok := err.(*githubapi.CreatePRError)
	if !ok {
		return false
	}
	*target = pe
	return true
}

// TestResolveBranchSHA_ExplicitBranch proves an explicit branch resolves
// directly via GET /repos/{owner}/{repo}/commits/{branch}, with NO call to
// the repo-info endpoint at all (the default-branch lookup is only ever
// needed when Branch is empty).
func TestResolveBranchSHA_ExplicitBranch(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{"sha": "abc123def456"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	sha, resolvedBranch, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner:  "acme",
		Repo:   "widgets",
		Branch: "feature-x",
		Token:  "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveBranchSHA() error = %v, want nil", err)
	}
	if sha != "abc123def456" {
		t.Errorf("ResolveBranchSHA() sha = %q, want %q", sha, "abc123def456")
	}
	if resolvedBranch != "feature-x" {
		t.Errorf("ResolveBranchSHA() resolvedBranch = %q, want %q (explicit branch echoed back verbatim)", resolvedBranch, "feature-x")
	}
	if gotPath != "/repos/acme/widgets/commits/feature-x" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/commits/feature-x")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
}

// TestResolveBranchSHA_EmptyBranchResolvesDefault proves an empty Branch
// first resolves the repo's own REAL default_branch (never a hardcoded
// "main"/"master" guess), then resolves THAT branch's commit SHA.
func TestResolveBranchSHA_EmptyBranchResolvesDefault(t *testing.T) {
	t.Parallel()

	var gotPaths []string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPaths = append(gotPaths, r.URL.Path)
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		switch r.URL.Path {
		case "/repos/acme/widgets":
			_ = json.NewEncoder(w).Encode(map[string]any{"default_branch": "trunk"})
		case "/repos/acme/widgets/commits/trunk":
			_ = json.NewEncoder(w).Encode(map[string]any{"sha": "def789"})
		default:
			t.Errorf("unexpected request path %q", r.URL.Path)
		}
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	sha, resolvedBranch, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner: "acme",
		Repo:  "widgets",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveBranchSHA() error = %v, want nil", err)
	}
	if sha != "def789" {
		t.Errorf("ResolveBranchSHA() sha = %q, want %q", sha, "def789")
	}
	if resolvedBranch != "trunk" {
		t.Errorf("ResolveBranchSHA() resolvedBranch = %q, want %q (the repo's own real default branch, not left empty)", resolvedBranch, "trunk")
	}
	wantPaths := []string{"/repos/acme/widgets", "/repos/acme/widgets/commits/trunk"}
	if len(gotPaths) != len(wantPaths) || gotPaths[0] != wantPaths[0] || gotPaths[1] != wantPaths[1] {
		t.Errorf("requested paths = %v, want %v (in order)", gotPaths, wantPaths)
	}
}

// TestResolveBranchSHA_4xxMapsToRealError proves a realistic GitHub 4xx
// failure (e.g. repo not found / no access) maps to a real, structured
// *githubapi.APIError, never a panic or a silently-empty SHA mistaken for
// success.
func TestResolveBranchSHA_4xxMapsToRealError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Not Found"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, _, err := adapter.ResolveBranchSHA(context.Background(), ports.ResolveBranchSHASpec{
		Owner:  "acme",
		Repo:   "widgets",
		Branch: "main",
		Token:  "gho_realtoken",
	})
	if err == nil {
		t.Fatal("ResolveBranchSHA() error = nil, want a *githubapi.APIError")
	}

	var shaErr *githubapi.APIError
	if !errors.As(err, &shaErr) {
		t.Fatalf("ResolveBranchSHA() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if shaErr.Status != http.StatusNotFound {
		t.Errorf("APIError.Status = %d, want %d", shaErr.Status, http.StatusNotFound)
	}
	if shaErr.Message == "" {
		t.Error("APIError.Message is empty, want GitHub's own error message")
	}
}

// TestResolveContractsFingerprint_DirectoryExists proves a real contents
// listing (several files) fingerprints to EXACTLY contractdrift.
// Fingerprint's own output over the identical path->sha map -- proving
// this adapter builds that map correctly, not re-implementing its own
// hashing.
func TestResolveContractsFingerprint_DirectoryExists(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path + "?" + r.URL.RawQuery
		gotAuth = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"path": "contracts/api/openapi.yaml", "sha": "sha-openapi", "type": "file"},
			{"path": "contracts/api/README.md", "sha": "sha-readme", "type": "file"},
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	fingerprint, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveContractsFingerprint() error = %v, want nil", err)
	}
	if !exists {
		t.Fatal("ResolveContractsFingerprint() exists = false, want true")
	}

	want := contractdrift.Fingerprint(map[string]string{
		"contracts/api/openapi.yaml": "sha-openapi",
		"contracts/api/README.md":    "sha-readme",
	})
	if fingerprint != want {
		t.Errorf("ResolveContractsFingerprint() fingerprint = %q, want %q", fingerprint, want)
	}

	if gotPath != "/repos/acme/widgets/contents/contracts/api?ref=abc123" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets/contents/contracts/api?ref=abc123")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
}

// TestResolveContractsFingerprint_404_ExistsFalseNoError proves a 404 (no
// contracts directory at that path/ref -- the common case) maps to
// (exists=false, err=nil), never a real error -- per ports.SourceControl's
// own doc comment, callers MUST be able to tell this apart from a genuine
// API failure.
func TestResolveContractsFingerprint_404_ExistsFalseNoError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusNotFound)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Not Found"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	fingerprint, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveContractsFingerprint() error = %v, want nil on a 404", err)
	}
	if exists {
		t.Error("ResolveContractsFingerprint() exists = true, want false on a 404")
	}
	if fingerprint != "" {
		t.Errorf("ResolveContractsFingerprint() fingerprint = %q, want empty on a 404", fingerprint)
	}
}

// TestResolveContractsFingerprint_NonNotFoundErrorPropagates proves a
// non-404 failure (e.g. a real 500, or no access at all) is a genuine
// error -- exists=false AND err != nil, never silently treated the same
// as "no directory here".
func TestResolveContractsFingerprint_NonNotFoundErrorPropagates(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Internal Server Error"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	_, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err == nil {
		t.Fatal("ResolveContractsFingerprint() error = nil, want a real error on a 500")
	}
	if exists {
		t.Error("ResolveContractsFingerprint() exists = true, want false on a real error")
	}

	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("ResolveContractsFingerprint() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if apiErr.Status != http.StatusInternalServerError {
		t.Errorf("APIError.Status = %d, want %d", apiErr.Status, http.StatusInternalServerError)
	}
}

// TestResolveContractsFingerprint_NestedSubdirectoryNotRecursedInto proves
// a listing containing a nested subdirectory entry is fingerprinted using
// THAT entry's own sha as-is -- never recursed into -- by asserting the
// server sees exactly ONE request even though the fake listing includes a
// "dir"-typed entry, and that the resulting fingerprint matches
// contractdrift.Fingerprint's own direct computation over the identical
// flat map (which itself never recurses either).
func TestResolveContractsFingerprint_NestedSubdirectoryNotRecursedInto(t *testing.T) {
	t.Parallel()

	var requestCount int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		requestCount++
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode([]map[string]any{
			{"path": "contracts/api/openapi.yaml", "sha": "sha-openapi", "type": "file"},
			{"path": "contracts/api/schemas", "sha": "sha-subdir-tree-hash", "type": "dir"},
		})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	fingerprint, exists, err := adapter.ResolveContractsFingerprint(context.Background(), ports.ResolveContractsFingerprintSpec{
		Owner: "acme",
		Repo:  "widgets",
		Ref:   "abc123",
		Path:  "contracts/api",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("ResolveContractsFingerprint() error = %v, want nil", err)
	}
	if !exists {
		t.Fatal("ResolveContractsFingerprint() exists = false, want true")
	}

	if requestCount != 1 {
		t.Errorf("server received %d requests, want exactly 1 (no recursion into the subdirectory entry)", requestCount)
	}

	want := contractdrift.Fingerprint(map[string]string{
		"contracts/api/openapi.yaml": "sha-openapi",
		"contracts/api/schemas":      "sha-subdir-tree-hash",
	})
	if fingerprint != want {
		t.Errorf("ResolveContractsFingerprint() fingerprint = %q, want %q (the subdirectory's own sha used as-is)", fingerprint, want)
	}
}

// TestCheckRepoAccess_200MeansAllowed proves a real 2xx GET
// /repos/{owner}/{repo} response reports (true, nil) -- the token can read
// this repo.
func TestCheckRepoAccess_200MeansAllowed(t *testing.T) {
	t.Parallel()

	var gotPath, gotAuth string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{"default_branch": "main"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	allowed, err := adapter.CheckRepoAccess(context.Background(), ports.CheckRepoAccessSpec{
		Owner: "acme",
		Repo:  "widgets",
		Token: "gho_realtoken",
	})
	if err != nil {
		t.Fatalf("CheckRepoAccess() error = %v, want nil on a 200", err)
	}
	if !allowed {
		t.Error("CheckRepoAccess() allowed = false, want true on a 200")
	}
	if gotPath != "/repos/acme/widgets" {
		t.Errorf("request path = %q, want %q", gotPath, "/repos/acme/widgets")
	}
	if gotAuth != "Bearer gho_realtoken" {
		t.Errorf("Authorization header = %q, want %q", gotAuth, "Bearer gho_realtoken")
	}
}

// TestCheckRepoAccess_404And403MeanDeniedNoError proves both a 404 (no
// access, or the repo doesn't exist) and a 403 (access blocked for some
// other reason -- e.g. rate-limited or an org policy) report a definitive,
// non-error (false, nil) -- exactly ports.SourceControl.CheckRepoAccess's
// own documented "a legitimate, expected answer, not a failure" contract.
func TestCheckRepoAccess_404And403MeanDeniedNoError(t *testing.T) {
	t.Parallel()

	for _, status := range []int{http.StatusNotFound, http.StatusForbidden} {
		t.Run(http.StatusText(status), func(t *testing.T) {
			t.Parallel()

			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(status)
				_ = json.NewEncoder(w).Encode(map[string]any{"message": "denied"})
			}))
			defer server.Close()

			adapter := githubapi.New(server.Client(), server.URL)

			allowed, err := adapter.CheckRepoAccess(context.Background(), ports.CheckRepoAccessSpec{
				Owner: "victim-org",
				Repo:  "private-repo",
				Token: "gho_noaccess",
			})
			if err != nil {
				t.Fatalf("CheckRepoAccess() error = %v, want nil on a %d", err, status)
			}
			if allowed {
				t.Errorf("CheckRepoAccess() allowed = true, want false on a %d", status)
			}
		})
	}
}

// TestCheckRepoAccess_5xxIsARealErrorNeverADenial proves a real server
// failure (never a 404/403) is reported as a genuine error -- allowed
// MUST be false alongside it, but callers must distinguish this from a
// definitive deny via the non-nil error (ports.SourceControl.
// CheckRepoAccess's own doc comment: "err != nil means the check itself
// could not be completed... callers MUST NOT treat that as a definitive
// no").
func TestCheckRepoAccess_5xxIsARealErrorNeverADenial(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Internal Server Error"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	allowed, err := adapter.CheckRepoAccess(context.Background(), ports.CheckRepoAccessSpec{
		Owner: "acme",
		Repo:  "widgets",
		Token: "gho_realtoken",
	})
	if err == nil {
		t.Fatal("CheckRepoAccess() error = nil, want a real error on a 500")
	}
	if allowed {
		t.Error("CheckRepoAccess() allowed = true, want false alongside a real error")
	}

	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("CheckRepoAccess() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if apiErr.Status != http.StatusInternalServerError {
		t.Errorf("APIError.Status = %d, want %d", apiErr.Status, http.StatusInternalServerError)
	}
}

// TestCheckRepoAccess_403RateLimited_IsErrorNeverADefinitiveDenial proves
// the audit fix (security-adversarial, findings #1/#4): a 403 that carries
// GitHub's own real rate-limit/abuse-detection signal (checked via
// X-RateLimit-Remaining: "0", a Retry-After header, or -- as a fallback --
// a message mentioning "rate limit"/"abuse detection") must be reported as
// a genuine ERROR, exactly like a 5xx, NEVER as a definitive (false, nil)
// deny -- so imageresolve.go's own repoAccessAllowedForSpawn treats it as
// indeterminate (deny only THIS spawn, never cached), not a sticky,
// cacheable "no access" verdict for a token that merely got rate-limited.
func TestCheckRepoAccess_403RateLimited_IsErrorNeverADefinitiveDenial(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		headers map[string]string
		body    map[string]any
	}{
		{
			name:    "primary rate limit via X-RateLimit-Remaining header",
			headers: map[string]string{"X-RateLimit-Remaining": "0"},
			body:    map[string]any{"message": "API rate limit exceeded for xxx.xxx.xxx.xxx."},
		},
		{
			name:    "secondary rate limit via Retry-After header",
			headers: map[string]string{"Retry-After": "60"},
			body:    map[string]any{"message": "You have exceeded a secondary rate limit. Please wait a few minutes before you try again."},
		},
		{
			name:    "no rate-limit headers at all, message-only fallback",
			headers: map[string]string{},
			body:    map[string]any{"message": "You have exceeded a secondary rate limit and have been temporarily blocked from content creation."},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()

			server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
				for k, v := range tc.headers {
					w.Header().Set(k, v)
				}
				w.Header().Set("Content-Type", "application/json")
				w.WriteHeader(http.StatusForbidden)
				_ = json.NewEncoder(w).Encode(tc.body)
			}))
			defer server.Close()

			adapter := githubapi.New(server.Client(), server.URL)

			allowed, err := adapter.CheckRepoAccess(context.Background(), ports.CheckRepoAccessSpec{
				Owner: "acme",
				Repo:  "widgets",
				Token: "gho_ratelimited",
			})
			if err == nil {
				t.Fatal("CheckRepoAccess() error = nil, want a real error on a rate-limited 403 (never a definitive denial)")
			}
			if allowed {
				t.Error("CheckRepoAccess() allowed = true, want false alongside the error")
			}

			var apiErr *githubapi.APIError
			if !errors.As(err, &apiErr) {
				t.Fatalf("CheckRepoAccess() error = %v (%T), want *githubapi.APIError", err, err)
			}
			if apiErr.Status != http.StatusForbidden {
				t.Errorf("APIError.Status = %d, want %d", apiErr.Status, http.StatusForbidden)
			}
			if !apiErr.RateLimited {
				t.Error("APIError.RateLimited = false, want true")
			}
		})
	}
}

// TestCheckRepoAccess_403EdgePageBody_MessageFallbackStillDetectsRateLimit
// is doGet's own regression test for the classifier's "wrong direction"
// bug (docs/TECHNICAL_PLAN.md §17's own adversarial review): a 403 whose
// body is NOT GitHub's JSON error envelope at all -- an edge/WAF HTML
// page ("error code: 1015 (you are being rate limited)"), carrying
// NEITHER GitHub's own X-RateLimit-Remaining NOR Retry-After header
// (plausibly stripped by whatever intercepted the response before this
// adapter ever saw it) -- must still classify as RateLimited via
// isRateLimitedResponse's own documented message-text fallback. Before
// this fix, doGet overwrote the body text with a fixed placeholder
// string BEFORE handing it to isRateLimitedResponse, so that fallback --
// documented as existing "in case a header got stripped somewhere
// between GitHub and this adapter (a proxy, a test double)" -- could
// never fire for exactly the case it names.
func TestCheckRepoAccess_403EdgePageBody_MessageFallbackStillDetectsRateLimit(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html")
		w.WriteHeader(http.StatusForbidden)
		_, _ = w.Write([]byte("<html><body>error code: 1015 (you are being rate limited)</body></html>"))
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	allowed, err := adapter.CheckRepoAccess(context.Background(), ports.CheckRepoAccessSpec{
		Owner: "acme",
		Repo:  "widgets",
		Token: "gho_edgepage",
	})
	if err == nil {
		t.Fatal("CheckRepoAccess() error = nil, want a real error -- a WAF/edge rate-limit page must never be treated as a definitive permission denial")
	}
	if allowed {
		t.Error("CheckRepoAccess() allowed = true, want false alongside the error")
	}

	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("CheckRepoAccess() error = %v (%T), want *githubapi.APIError", err, err)
	}
	if !apiErr.RateLimited {
		t.Error("APIError.RateLimited = false, want true -- the message-text fallback must see the RAW body, not a placeholder string overwriting it")
	}
}

// TestCheckRepoAccess_403WithoutRateLimitSignal_StillDeniedNoError proves a
// plain 403 carrying NEITHER a rate-limit header NOR a rate-limit-shaped
// message (an ordinary "you cannot read this" denial) still reports the
// pre-existing (false, nil) definitive-deny contract -- this fix narrows
// which 403s are treated as errors; it must not turn every 403 into one.
func TestCheckRepoAccess_403WithoutRateLimitSignal_StillDeniedNoError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusForbidden)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Must have admin rights to Repository."})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	allowed, err := adapter.CheckRepoAccess(context.Background(), ports.CheckRepoAccessSpec{
		Owner: "acme",
		Repo:  "widgets",
		Token: "gho_noaccess",
	})
	if err != nil {
		t.Fatalf("CheckRepoAccess() error = %v, want nil on a plain, non-rate-limited 403", err)
	}
	if allowed {
		t.Error("CheckRepoAccess() allowed = true, want false")
	}
}

// TestCheckRepoAccess_EscapesOwnerAndRepo proves Owner/Repo are each
// url.PathEscape'd before being interpolated into the request path --
// mirrors CreatePR/ResolveBranchSHA's own identical escaping tests.
func TestCheckRepoAccess_EscapesOwnerAndRepo(t *testing.T) {
	t.Parallel()

	var gotEscapedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPath = r.URL.EscapedPath()
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_ = json.NewEncoder(w).Encode(map[string]any{"default_branch": "main"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	if _, err := adapter.CheckRepoAccess(context.Background(), ports.CheckRepoAccessSpec{
		Owner: "acme/evil",
		Repo:  "widgets#v1",
		Token: "gho_realtoken",
	}); err != nil {
		t.Fatalf("CheckRepoAccess() error = %v, want nil", err)
	}

	want := "/repos/acme%2Fevil/widgets%23v1"
	if gotEscapedPath != want {
		t.Errorf("request EscapedPath = %q, want %q (owner/repo must be escaped, not interpolated raw)", gotEscapedPath, want)
	}
}

// TestCreateCommitStatus_Success proves CreateCommitStatus ("RWX
// provider + previews", §4.1.2 point 3) posts the right shape to
// /repos/{owner}/{repo}/statuses/{sha}.
func TestCreateCommitStatus_Success(t *testing.T) {
	t.Parallel()

	var gotPath, gotMethod, gotAuth, gotAccept string
	var gotBody map[string]any

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotMethod = r.Method
		gotPath = r.URL.Path
		gotAuth = r.Header.Get("Authorization")
		gotAccept = r.Header.Get("Accept")
		if err := json.NewDecoder(r.Body).Decode(&gotBody); err != nil {
			t.Fatalf("decode request body: %v", err)
		}
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusCreated)
		_ = json.NewEncoder(w).Encode(map[string]any{"id": 1, "state": "success"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	err := adapter.CreateCommitStatus(context.Background(), "acme", "widgets", "abc123sha",
		"success", "https://myapp-pr-7--acme.rwx.run", "Preview deployed via RWX (ephemeral).", "narvi/preview", "bot-token")
	if err != nil {
		t.Fatalf("CreateCommitStatus() error = %v, want nil", err)
	}

	if gotMethod != http.MethodPost {
		t.Errorf("method = %q, want POST", gotMethod)
	}
	if gotPath != "/repos/acme/widgets/statuses/abc123sha" {
		t.Errorf("path = %q, want %q", gotPath, "/repos/acme/widgets/statuses/abc123sha")
	}
	if gotAuth != "Bearer bot-token" {
		t.Errorf("Authorization = %q, want %q", gotAuth, "Bearer bot-token")
	}
	if gotAccept != "application/vnd.github+json" {
		t.Errorf("Accept = %q, want %q", gotAccept, "application/vnd.github+json")
	}
	if gotBody["state"] != "success" {
		t.Errorf("body[state] = %v, want %q", gotBody["state"], "success")
	}
	if gotBody["target_url"] != "https://myapp-pr-7--acme.rwx.run" {
		t.Errorf("body[target_url] = %v, want the friendly preview URL", gotBody["target_url"])
	}
	if gotBody["context"] != "narvi/preview" {
		t.Errorf("body[context] = %v, want %q", gotBody["context"], "narvi/preview")
	}
	if gotBody["description"] != "Preview deployed via RWX (ephemeral)." {
		t.Errorf("body[description] = %v, want the ephemerality caveat", gotBody["description"])
	}
}

// TestCreateCommitStatus_HTTPError proves a non-2xx GitHub response
// surfaces a real error via doPost's shared error-envelope parsing.
func TestCreateCommitStatus_HTTPError(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnprocessableEntity)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "Validation Failed"})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)

	err := adapter.CreateCommitStatus(context.Background(), "acme", "widgets", "abc123sha",
		"success", "https://example.rwx.run", "desc", "narvi/preview", "bot-token")
	if err == nil {
		t.Fatal("CreateCommitStatus() error = nil, want non-nil")
	}
}

// TestCreateCommitStatus_EscapesOwnerRepoSHA proves owner/repo/sha are each
// escaped as opaque path segments, mirroring PostIssueComment's own
// identical discipline.
func TestCreateCommitStatus_EscapesOwnerRepoSHA(t *testing.T) {
	t.Parallel()

	var gotEscapedPath string
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		gotEscapedPath = r.URL.EscapedPath()
		w.WriteHeader(http.StatusCreated)
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)
	if err := adapter.CreateCommitStatus(context.Background(), "acme/evil", "widgets", "sha#v1",
		"success", "", "", "narvi/preview", "tok"); err != nil {
		t.Fatalf("CreateCommitStatus() error = %v", err)
	}

	want := "/repos/acme%2Fevil/widgets/statuses/sha%23v1"
	if gotEscapedPath != want {
		t.Errorf("request EscapedPath = %q, want %q", gotEscapedPath, want)
	}
}

// TestCreateBranch_403RateLimited_APIErrorCarriesRateLimited is doPost's
// own regression test for docs/TECHNICAL_PLAN.md §17's own adversarial
// review: "doPost/doPatch never compute RateLimited, so a textbook
// primary-rate-limited 403 through either unwraps to
// ErrPermissionDenied." doPost previously never computed
// APIError.RateLimited at all, so this 403 -- flagged by GitHub's own
// X-RateLimit-Remaining header -- would have unwrapped straight to
// ports.ErrPermissionDenied via APIError.Unwrap's own Status==403 branch.
func TestCreateBranch_403RateLimited_APIErrorCarriesRateLimited(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("X-RateLimit-Remaining", "0")
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusForbidden)
		_ = json.NewEncoder(w).Encode(map[string]any{"message": "API rate limit exceeded for xxx.xxx.xxx.xxx."})
	}))
	defer server.Close()

	adapter := githubapi.New(server.Client(), server.URL)
	err := adapter.CreateBranch(context.Background(), ports.CreateBranchSpec{
		Owner: "acme", Repo: "widgets", Branch: "feature/x", SHA: "abc123", Token: "tok",
	})
	if err == nil {
		t.Fatal("CreateBranch() error = nil, want a genuine error on a rate-limited 403")
	}
	if errors.Is(err, ports.ErrPermissionDenied) {
		t.Error("errors.Is(err, ports.ErrPermissionDenied) = true, want false -- a rate-limited 403 must never classify as a permanent denial")
	}

	var apiErr *githubapi.APIError
	if !errors.As(err, &apiErr) {
		t.Fatalf("CreateBranch() error = %v (%T), want an error wrapping *githubapi.APIError", err, err)
	}
	if !apiErr.RateLimited {
		t.Error("APIError.RateLimited = false, want true -- doPost must compute it exactly like doGet/doPut do")
	}
}
